Updated RModelParser_PyTorch.cxx -Fixes the bug related to build
root-project/root pull request #10223
Opened 2022-03-24 06:36 UTC by Neel-Shah-29

# This Pull request: Fixes the bug to build ROOT in Ubuntu 20.04
![image](https://user-images.githubusercontent.com/84740927/159856024-8b399e36-d835-4726-b6dc-9d1a5b90dbc3.png)

The above bug was noticed by me when i was building boost in my local computer. This can be resolved by just removing example_outputs argument from PyRunString function over [here](https://github.com/root-project/root/blob/master/tmva/pymva/src/RModelParser_PyTorch.cxx#L422)

## Changes or fixes:
Bug-issue related to build

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2022-03-28 10:00 UTC, lmoneta reviewed
Which PyTorch version are you using ? 
With 1.10 it still works for me, but I think looking at 
https://github.com/pytorch/pytorch/blob/master/torch/onnx/utils.py 
the master version has the _model_to_graph interface changed to not pass anymore example_outputs. 
@sanjibansg , can we remove example_outputs also for older PyTorch versions ?

2022-03-28 10:23 UTC, sanjibansg commented on tmva/pymva/src/RModelParser_PyTorch.cxx
It was deprecated in v1.10 and was completely removed with this PR https://github.com/pytorch/pytorch/pull/62815 for v1.11, but I think it was a required argument in the earlier versions.

2022-03-28 10:38 UTC, sanjibansg requested changes
I think if we are restricting to use the current version of PyTorch with example_outputs removed, then this line can be removed as well.
https://github.com/root-project/root/pull/10223/files/cb144c0f3939dd5a357fe9cba748d1d44ed395cd#diff-358c76d81a2584d32938feea96f50f0ef04b3ef051a8adc124847a1ff5d29743R418

2022-03-28 10:39 UTC, lmoneta commented on tmva/pymva/src/RModelParser_PyTorch.cxx
Thanks Sanjibang. I will check the PR with an older PyTorch version

2022-03-28 10:55 UTC, Neel-Shah-29 commented
> Which PyTorch version are you using ? With 1.10 it still works for me, but I think looking at https://github.com/pytorch/pytorch/blob/master/torch/onnx/utils.py the master version has the _model_to_graph interface changed to not pass anymore example_outputs. @sanjibansg , can we remove example_outputs also for older PyTorch versions ?

![image](https://user-images.githubusercontent.com/84740927/160382712-cbb6265d-682b-4260-b10e-cc5c1b5006d0.png)
Hello, My Pytorch version is 1.11 and I think for 1.10 it works fine but for higher versions it gives the above error i will make the changes proposed by @sanjibansg and @lmoneta . Thankyou for reviewing my PR.

2022-03-28 11:04 UTC, Neel-Shah-29 commented on tmva/pymva/src/RModelParser_PyTorch.cxx
I have removed the line 418 as suggested. Thankyou.

2022-04-04 09:50 UTC, Neel-Shah-29 commented
Hello @lmoneta can you merge this PR if everything is alright?

2022-04-05 09:56 UTC, lmoneta approved these changes
LGTM!
Thank you for this fix!

2022-04-05 09:56 UTC, merged