added missing snapshot creation
root-project/root pull request #10293
Opened 2022-04-01 12:06 UTC by cburgard

# This Pull request:

Fixes a bug where snapshots were not imported from JSON.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2022-04-01 12:07 UTC, cburgard commented
@guitargeek please take a look at this small bugfix. does this qualify to be backported?

2022-04-01 12:08 UTC, cburgard commented
@guitargeek please take a look at this small bugfix. does this qualify to be backported?

2022-04-04 14:26 UTC, Axel-Naumann requested changes

2022-04-04 14:26 UTC, Axel-Naumann commented on roofit/hs3/src/RooJSONFactoryWSTool.cxx
> +	 RooArgSet vars;
No tabs, please.

2022-04-04 14:36 UTC, cburgard commented
done, I hope

2022-04-05 10:03 UTC, cburgard commented on roofit/hs3/src/RooJSONFactoryWSTool.cxx
> +	 RooArgSet vars;
done (I hope)

2022-04-08 08:34 UTC, cburgard commented
Is there still anything left to be done? I see the check failing, but I can't see why.

2022-04-11 11:07 UTC, guitargeek commented
The failing checks are unrelated, I'll merge now. Thanks for the PR :+1:

2022-04-11 11:07 UTC, guitargeek approved these changes

2022-04-11 11:08 UTC, merged