Ignore warnings
root-project/root pull request #10303
Opened 2022-04-04 07:46 UTC by ellert

# This Pull request:

## Changes or fixes:

The RNTuple LargeFile test can trigger a warning about uring not being available.
This PR adds a CheckDiagsRAII to allow this.
The custom RAII doesn't inherit the default list of warnings to ignore (why?) so I had to add some of those as well to the RAII.

Many RooFit test fails on s390x due to a warning about RooNaNPacker not being implemented for big endian.
There are too many of them to add RAIIs for each of them, so I added the warning to the default list in this PR.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2022-04-05 07:26 UTC, jblomer commented
I leave the review of the RooNaNPacker warning to @guitargeek

2022-04-05 07:28 UTC, jblomer commented
@ellert It is strange that the uring warning appears only in this unit test. Other unit tests use uring, too, and I would expect all of them to report uring issues consistently.  Could you give me the full printout of the failed unit test?

2022-04-17 02:56 UTC, ellert commented
> @ellert It is strange that the uring warning appears only in this unit test. Other unit tests use uring, too, and I would expect all of them to report uring issues consistently. Could you give me the full printout of the failed unit test?

```
 472/1232 Test  #423: gtest-tree-ntuple-v7-test-ntuple-extended ...........................***Failed   29.66 sec
Running main() from /builddir/build/BUILD/googletest-release-1.11.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from RNTuple
[ RUN      ] RNTuple.RealWorld1
Warning in [ROOT.NTuple] Warning /builddir/build/BUILD/root-6.26.02/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&) The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in [ROOT.NTuple] Warning /builddir/build/BUILD/root-6.26.02/tree/ntuple/v7/src/RNTupleSerialize.cxx:1105 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&) Pre-release format version: RC 1
[       OK ] RNTuple.RealWorld1 (8502 ms)
[ RUN      ] RNTuple.RandomAccess
Warning in [ROOT.NTuple] Warning /builddir/build/BUILD/root-6.26.02/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&) The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in [ROOT.NTuple] Warning /builddir/build/BUILD/root-6.26.02/tree/ntuple/v7/src/RNTupleSerialize.cxx:1105 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&) Pre-release format version: RC 1
[       OK ] RNTuple.RandomAccess (113 ms)
[ RUN      ] RNTuple.LargeFile
Warning in [ROOT.NTuple] Warning /builddir/build/BUILD/root-6.26.02/tree/ntuple/v7/src/RPageStorageFile.cxx:51 in ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile(std::string_view, const ROOT::Experimental::RNTupleWriteOptions&) The RNTuple file format will change. Do not store real data with this version of RNTuple!
Warning in [ROOT.NTuple] Warning /builddir/build/BUILD/root-6.26.02/tree/ntuple/v7/src/RNTupleSerialize.cxx:1105 in static ROOT::Experimental::RResult<void> ROOT::Experimental::Internal::RNTupleSerializer::DeserializeHeaderV1(const void*, uint32_t, ROOT::Experimental::RNTupleDescriptorBuilder&) Pre-release format version: RC 1
/builddir/build/BUILD/root-6.26.02/test/unit_testing_support/ROOTUnitTestSupport.cxx:75: Failure
Failed
Received unexpected diagnostic of severity 2000 at 'RIoUring' reading 'io_uring is unexpectedly not available because:
batch 0: read failed for ReadEvent[1], error: Invalid argument'.
Suppress those using ROOTUnitTestSupport.h
/builddir/build/BUILD/root-6.26.02/test/unit_testing_support/ROOTUnitTestSupport.cxx:75: Failure
Failed
Received unexpected diagnostic of severity 2000 at 'RRawFileUnix' reading 'io_uring setup failed, falling back to blocking I/O in ReadV'.
Suppress those using ROOTUnitTestSupport.h
[  FAILED  ] RNTuple.LargeFile (20982 ms)
[----------] 3 tests from RNTuple (29599 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (29599 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RNTuple.LargeFile
 1 FAILED TEST
CMake Error at /builddir/build/BUILD/root-6.26.02/cmake/modules/RootTestDriver.cmake:227 (message):
  error code: 1
```

2022-05-04 09:10 UTC, jblomer commented
Thanks, @ellert! The warning should not be ignored because it indicates an unexpected behavior in uring on that platform. It could be either a bug in uring or it may be an issue in how we use uring that is not triggered on other platforms.

Which kernel version are you using? Would it be possible for me to get access to the node?

If you'd like to proceed with green unit tests, you can disable uring support at compile time with `cmake -During=off`.

2022-05-16 07:45 UTC, jblomer requested changes
As discussed in the comments, I think this error should not be ignored but there is an actual issue to fix.

2023-11-25 18:55 UTC, ellert commented
Hi. I have dropped the commit related to uring from this PR. Please consider merging the remaining commit related to RooNaNPacker.

2023-11-26 11:26 UTC, guitargeek commented
Hi @ellert, thanks for updating this PR!

My preferred solution would be to detect in the build system if the machine in big endian, and only build/execute the NaN - packer test if this is not the case. Would this be possible? Then we don't need to hack into the ROOT test system.

2023-11-26 12:13 UTC, ellert commented
> Hi @ellert, thanks for updating this PR!
> 
> My preferred solution would be to detect in the build system if the machine in big endian, and only build/execute the NaN - packer test if this is not the case. Would this be possible? Then we don't need to hack into the ROOT test system.

There is one explicit test for specifically checking the NaN feature:

gtest-roofit-roofitcore-test-testNaNPacker

This PR is not about this test. This test still correctly fails with this PR applied.

The PR is so that tests that are testing other things don't fail because they trigger this warning about the NaN feature not having been implemented. The warning says: fast recovery not implemented. As far as I can tell the tests fall back to some slower recovery method and succeed.

2023-11-27 16:47 UTC, guitargeek commented
Ok, thanks for the clarification! May I ask which tests are failing because of this warning? Normally, a warning should not make the test fail, so I'm curious to know what is exactly going on there.

2023-12-02 14:07 UTC, ellert commented
> Ok, thanks for the clarification! May I ask which tests are failing because of this warning? Normally, a warning should not make the test fail, so I'm curious to know what is exactly going on there.

This is a list of test that fail without this change:

	239 - gtest-roofit-hs3-test-testHS3SimultaneousFit (Failed)
	249 - gtest-roofit-roofit-test-testRooCrystalBall (Failed)
	250 - gtest-roofit-roofit-test-testRooJohnson (Failed)
	261 - gtest-roofit-roofitcore-test-testRooAddPdf (Failed)
	266 - gtest-roofit-roofitcore-test-testRooBinSamplingPdf (Failed)
	267 - gtest-roofit-roofitcore-test-testRooWrapperPdf (Failed)
	269 - gtest-roofit-roofitcore-test-testRooAbsPdf (Failed)
	273 - gtest-roofit-roofitcore-test-testRooProdPdf (Failed)
	277 - gtest-roofit-roofitcore-test-testRooAbsReal (Failed)
	279 - gtest-roofit-roofitcore-test-testTestStatistics (Failed)
	280 - gtest-roofit-roofitcore-test-testGlobalObservables (Failed)
	281 - gtest-roofit-roofitcore-test-testInterface (Failed)
	282 - gtest-roofit-roofitcore-test-testLikelihoodSerial (Failed)
	283 - gtest-roofit-roofitcore-test-testRooAbsL (Failed)
	287 - gtest-roofit-roofitcore-test-testRooRealL (Failed)
	290 - gtest-roofit-roofitcore-test-testRooSimultaneous (Failed)
	292 - gtest-roofit-roofitcore-test-testSumW2Error (Failed)
	294 - gtest-roofit-roofitcore-test-testLikelihoodGradientJob (Failed)
	295 - gtest-roofit-roofitcore-test-testLikelihoodJob (Failed)
	298 - gtest-roofit-roostats-test-testSPlot (Failed)

Here is an example failure:
```
 331/1268 Test  #292: gtest-roofit-roofitcore-test-testSumW2Error ...............................***Failed    0.58 sec
Running main() from /builddir/build/BUILD/googletest-1.14.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RRawFile.Remote:RSqliteDS.Davix:TChainParsing.RemoteGlob:TFile.ReadWithoutGlobalRegistrationNet:TFile.ReadWithoutGlobalRegistrationWeb:RNTuple.TClassEBO
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SumW2Error
[ RUN      ] SumW2Error.BatchMode
/builddir/build/BUILD/root-6.30.02/core/testsupport/src/TestSupport.cxx:77: Failure
Failed
Received unexpected diagnostic of severity 2000 at 'RooNaNPacker' reading 'Fast recovery from undefined function values only implemented for little-endian machines. If necessary, request an extension of functionality on https://root.cern'.
Suppress those using ROOT/TestSupport.hxx
[  FAILED  ] SumW2Error.BatchMode (408 ms)
[ RUN      ] SumW2Error.ExtendedFit
[       OK ] SumW2Error.ExtendedFit (112 ms)
[----------] 2 tests from SumW2Error (521 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (521 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SumW2Error.BatchMode
 1 FAILED TEST
CMake Error at /builddir/build/BUILD/root-6.30.02/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: 1
```
Normally, when root issues a warning it is not fatal, and program execution continues. However, this is a test, and the ROOT::TestSupport installs a custum error handler that captures warnings and rethrow them as GTest failures. So it this contaext a warning is expected to generate a failure.

2024-05-20 14:14 UTC, guitargeek commented
Thanks for the explanation! Sorry for the late follow-up.

2024-05-20 14:15 UTC, guitargeek approved these changes

2024-05-20 14:16 UTC, merged