[DF] Teach `Vary` to accept `Stats`
root-project/root pull request #10567
Opened 2022-05-12 10:03 UTC by ikabadzhov

With this solution `TStatistic` never resets its result that is being varied.

Fix https://github.com/root-project/root/issues/10545.

2022-05-12 14:22 UTC, ikabadzhov commented
@phsft-bot build just on ROOT-debian10-i386/cxx14

2022-05-16 13:37 UTC, eguiraud requested changes

2022-05-16 13:37 UTC, eguiraud commented on tree/dataframe/test/dataframe_vary.cxx
> +   auto ss2 = VariationsFor(h);
```suggestion
   auto ss2 = VariationsFor(s);
```

2022-05-16 15:53 UTC, ikabadzhov commented on tree/dataframe/test/dataframe_vary.cxx
> +}
It does fail. I just checked. The exact same test fails  with:
```
394: [ ]/tree/dataframe/test/dataframe_vary.cxx:667: Failure
394: Expected equality of these values:
394:   hs2["x:0"].GetMean()
394:     Which is: 0.6
394:   -1
394: [ ]/tree/dataframe/test/dataframe_vary.cxx:668: Failure
394: Expected equality of these values:
394:   hs2["x:1"].GetMean()
394:     Which is: 1.2
394:   2
```

2022-05-16 15:56 UTC, ikabadzhov commented on tree/dataframe/test/dataframe_vary.cxx
> +TEST_P(RDFVary, FillHelperResets)
Only this remark remained open now: I added:
```
// check if the Fill action helper properly resets between event loops
```

2022-05-18 07:31 UTC, eguiraud approved these changes
Thanks Ivan, nice solution! Just a wording suggestion for your consideration, but this can go in.

2022-05-18 18:48 UTC, merged