[ntuple] `std::tuple` RField support
root-project/root pull request #10652
Opened 2022-05-25 15:05 UTC by jalopezg-r00t

This pull request adds `std::tuple<...>` RField support (see notes below).  Follow-up PR of #10631.

## Changes or fixes:
- Amend `RRecordField` offsets computation: account for padding inserted before each member to comply with the alignment requirements of the type.
- Add `std::tuple` RField support.  ISO C++ does not guarantee neither specific layout nor member names for `std::tuple`.
Therefore, for the type-erased `RTupleField`, we guess the offsets assuming that most implementations store it as a standard-layout type with members reversed w.r.t. the type list.
A test has been added to check that this renders usable `RTupleField`s in all CI configurations, even when padding is added (see `char` members). 
There is a question about whether there is a better way for computing these offsets.
- Update `specifications.md` accordingly.

## Checklist:
- [X] tested changes locally
- [X] updated the docs (if necessary)

This PR fixes #10632.

2022-06-01 21:29 UTC, jalopezg-r00t commented
@phsft-bot build just on windows10/cxx14

2022-06-14 08:34 UTC, jblomer requested changes
Great!  `RNTuple`'s support for `std::ntuple` at the very least gives aesthetic closure.

Just a few minor comments.

2022-06-14 08:34 UTC, jblomer commented on tree/ntuple/v7/test/ntuple_types.cxx
> +      auto tuple_field = model->MakeField<std::tuple<char, float, std::string, char>>({"myTuple", "4-tuple"});
Just to be sure, let's store and retrieve a nested tuple

2022-06-14 08:34 UTC, jblomer commented on tree/ntuple/v7/src/RField.cxx
> +   R__ASSERT(!result.empty()); // there is always at least one type
Check for non-empty `itemFields` at the beginning and throw in case of failure?

2022-06-14 08:34 UTC, jblomer commented on tree/ntuple/v7/src/RField.cxx
> +      R__ASSERT(member != nullptr);
Throw an `RException`

2022-06-14 09:17 UTC, jalopezg-r00t commented on tree/ntuple/v7/src/RField.cxx
> +   if (normalizedType.substr(0, 8) == "tuple<") normalizedType = "std::" + normalizedType;
Ouch!  Thanks for spotting!

2022-06-20 12:07 UTC, jblomer approved these changes
Great, LGTM!

2022-06-20 20:09 UTC, merged