[ntuple] Allow for vector commit of sealed pages
root-project/root pull request #10775
Opened 2022-06-16 16:49 UTC by jalopezg-r00t

This pull request extends `RPageSink` to allow for vector commit of sealed pages.  The prototype of the new functions is as follows:
```c++
virtual std::vector<RNTupleLocator> CommitSealedPagesImpl(const std::vector<RPageStorage::RSealedPageRange> &ranges);
void CommitSealedPages(const std::vector<RPageStorage::RSealedPageRange> &ranges);
```

These changes enable (parallel) vector writes in concrete backends, e.g. in DAOS.  Derived classes that do not override the base implementation will see a sequence of calls to `CommitSealedPage()`.

The refactor in this PR passes all the RPageSinkBuf tests.
 
## Changes or fixes:
- Add `CommitSealedPages()` to the public interface of `RPageSink`. This function carries out a vector write of a number of sealed page ranges.  Each range applies to a given columnId.
The default implementation of `CommitSealedPagesImpl()` sequentially calls `CommitSealedPageImpl()` for each page on each range, but derived classes can override it to provide an optimized implementation.
- Use `CommitSealedPages()` in RPageSinkBuf.  If a buffered column contains only sealed pages, commit the whole range
via `CommitSealedPages()`.
- If all buffered columns consist solely of sealed pages, coalesce all pages to be committed in a single `CommitSealedPages()` call that includes a sealed page range per column.

## Checklist:
- [X] tested changes locally
- [X] updated the docs (if necessary)

This PR fixes #10719.

2022-06-21 22:01 UTC, jblomer requested changes
Good work!  I have two name changes suggestions
  - `CommitSealedPages` --> `CommitSealedPageV` (same for the `Impl` method); this is in line with other vector signatures in RNTuple and I find the capital `V` easier to distinguish from the singular/scalar method call
  - `RSealedPageRange` --> `RSealedPageGroup`, since we call the set of pages of the same column in the same cluster a page group in the docs.

Other than that, let me have another look.  I have the feeling that the patch can still be simplified but I'm not yet sure about it.

2022-06-22 16:35 UTC, mxxo reviewed
Looks good to me!

2022-06-22 16:35 UTC, mxxo commented on tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
> +      // Pages that have been alredy sealed by a concurrent task. A vector commit can be issued if all
```suggestion
      // Pages that have been already sealed by a concurrent task. A vector commit can be issued if all
```

2022-06-22 19:36 UTC, jalopezg-r00t commented
> Looks good to me!

Thanks for reviewing, @mxxo!  During the first DAOS tests using the `ofi+tcp` provider, we measured over 2 GB/s for the default of 64 KiB pages (before it was ~200 MB/s).  :slightly_smiling_face:

2022-06-27 13:38 UTC, jblomer requested changes
I think it's essentially good to go, with some minor modifications.

Nice work!

2022-06-27 13:38 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
> +   virtual std::vector<RNTupleLocator> CommitSealedPageVImpl(const std::vector<RPageStorage::RSealedPageGroup> &ranges);
Should we rather use an `std::span` for the `ranges` input in this interface and in `CommitSealedPageV`?

2022-06-27 13:38 UTC, jblomer commented on tree/ntuple/v7/src/RPageSinkBuf.cxx
> +      auto hasSealedPagesOnly = bufColumn.HasSealedPagesOnly();
Let's make sure that we have unit tests for the three cases:
  - All pages sealed
  - All pages of a column sealed
  - Some pages sealed some not

2022-06-28 21:17 UTC, jblomer reviewed
The new unit tests do help but I meant something else: the buffered sink has quite a nice logic to try and make as much use as possible of vector writes.  However, I think that logic is not fully tested.  In practice, we have cases were only scalar writes are used and cases where everything is precompressed and we can submit one large vector write.  But the fine grained options in-between -- some columns in vector writes and some columns not -- are, I think, not tested.  I'm not even sure if such cases can occur in practice.
One option is to just add a comment on that possible optimization and to remove the more sophisticated parts of the vector write logic - i.e. either one big vector write or all scalar writes.

2022-06-28 23:01 UTC, jalopezg-r00t commented
> But the fine grained options in-between -- some columns in vector writes and some columns not -- are, I think, not tested. I'm not even sure if such cases can occur in practice.
> One option is to just add a comment on that possible optimization and to remove the more sophisticated parts of the vector write logic - i.e. either one big vector write or all scalar writes.

Those cases could occur, but I think it is (probably) a misuse of the current API; I have updated the test cases to include that.  Let me know what you think; otherwise, as you said, we could just remove that possible per-column vector write optimization.

2022-06-29 07:52 UTC, jblomer commented
> Those cases could occur, but I think it is probably a misuse of the API. I have updated the test cases to include that. Let me know what you think; otherwise, as you said, we could just remove that possible per-column vector write optimization.

That's a nice way to test it! Still, for reasons of maintainability I'd be more in favor of removing the per-column vector write optimization.  It's quite some code that is most likely never executed.

2022-06-30 20:48 UTC, jblomer approved these changes

2022-06-30 20:58 UTC, merged