[RF] Translate RooStats tutorial rs101_limitexample.C to Python
root-project/root pull request #10853
Opened 2022-06-29 14:02 UTC by busorgin

# This Pull request:

## Changes or fixes:
Add rs101_limitexample.py - Converted from rs101_limitexample.C

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes # Part of [8758](https://github.com/root-project/root/issues/8758)

2022-06-29 17:42 UTC, guitargeek commented on tutorials/roostats/rs101_limitexample.py
> +## \author Kyle Cranmer
```suggestion
## \date June 2022
## \authors Artem Busorgin, Kyle Cranmer (C++ version)
```
Please add also the date, and you can also add your name here to get some credits :)

2022-06-29 17:45 UTC, guitargeek commented on tutorials/roostats/rs101_limitexample.py
> +assert chain
```suggestion
```
No asserts in tutorials

2022-06-29 17:46 UTC, guitargeek commented on tutorials/roostats/rs101_limitexample.py
> +    # print("{}  {}  {}  {}".format(ievt, x, y, z))
```suggestion
```
It's not good to have commented out code in tutorials.

2022-06-29 17:47 UTC, guitargeek commented on tutorials/roostats/rs101_limitexample.py
> +all = ROOT.RooArgSet(s, ratioBkgEff, ratioSigEff)
```suggestion
```
`all` is never used. You should delete this line

2022-06-29 17:49 UTC, guitargeek commented on tutorials/roostats/rs101_limitexample.py
> +obs = wspace.var("obs") # get the observable
```suggestion
modelWithConstraints = wspace["modelWithConstraints"] # get the model
obs = wspace["obs"] # get the observable
```

In PyRoot, you can universally get anything from a RooWorkspace with the `[]`-operator. You should use this everytime you see `var()`, `pdf()`, or `function()` in C++ (there are also more occurences of `var()` to replace in the lines below).

2022-06-29 17:50 UTC, guitargeek commented on tutorials/roostats/rs101_limitexample.py
> +data = ROOT.RooDataSet("exampleData", "exampleData", ROOT.RooArgSet(obs))
```suggestion
data = ROOT.RooDataSet("exampleData", "exampleData", {obs})
```

2022-06-29 17:56 UTC, guitargeek requested changes
Hi @busorgin thank you so much for this contribution, which is really appreciated :+1: I which context are you doing this? Are you a RooFit user who wants to contribute, or you were just browsing GitHub for issues you could address?

Please address the requests I have (mostly about Pythonic code, and one fix for the destruction order fiasco).

2022-06-29 23:00 UTC, guitargeek commented
@phsft-bot build

2022-06-29 23:03 UTC, guitargeek commented
Alright, thank you very much! That's very nice you chose ROOT to contribute to!

If you need any guidance on what you could help with, just ask me. Sometimes it's not easy to find the issues that are actually easy to work on, as the code is quite complex.

Are you looking only Python-related issues, or would you also be interested in doing some C++ contributions to beef up your C++ skills and experience?

As for this PR, I'll merge it if the CI bot tests pass.

2022-06-30 10:50 UTC, busorgin commented
Thanks, I'll keep that in mind.

I was looking for both C++ and Python. I found #9859, seemed like a good starter item on the C++ side. Open to suggestions if there are other good issues to look into.

2022-06-30 11:34 UTC, guitargeek commented
Hi @busorgin, okay sounds great! The issue you linked is indeed a very good one to get started with RooFit C++ development. If you have any questions about it, we can follow up in the issue thread there.

Of course, it would also be of great help if you continue doing these RooStats tutorial translations! People use more Python than C++ now, and a better coverage of the Python tutorials is something requested by many users, in particular for RooStats. So among all the "easier" RooFit issues, the RooStats tutorial translations have the highest priority.

2022-06-30 11:41 UTC, merged