[RF] Speed up `RooAbsRealLValue::setBin` by removing `inRange` check
root-project/root pull request #11090
Opened 2022-08-02 10:13 UTC by HannaOlvhammar

Replaced `RooAbsVar::setVal` with `RooRealVar::setValFast` in
`RooAbsRealLValue::setBin`, which does not call `RooAbsRealLValue::inRange`.
This led to a big improvement in speed for `RooAbsRealLValue::setBin`.

# This Pull request:

## Changes or fixes:

## Checklist:

- [X ] tested changes locally
- [ ] updated the docs (if necessary)

2022-08-02 11:54 UTC, guitargeek commented
@phsft-bot build

2022-08-02 11:57 UTC, guitargeek requested changes
Hi Hanna, thank you very much for the PR!

Code changes look fine, but can you please change the commit message to explain why it was possible to use `setValFast` in `setBin`? That it's redundant to do the range, check in `getVal`, because the value you pass to `setBin` is a bin center which is in the variable range by definition anyway.

2022-08-02 12:08 UTC, HannaOlvhammar commented
> Hi Hanna, thank you very much for the PR!
> 
> Code changes look fine, but can you please change the commit message to explain why it was possible to use `setValFast` in `setBin`? That it's redundant to do the range, check in `getVal`, because the value you pass to `setBin` is a bin center which is in the variable range by definition anyway.

Thank you for the comment, I hope the new commit message is clearer!

2022-08-02 12:49 UTC, guitargeek commented
@phsft-bot build

2022-08-03 11:52 UTC, guitargeek approved these changes
LGTM, thanks a lot for this improvement and cleaning up the old `setBinFast` function :+1:

2022-08-03 11:53 UTC, merged