fix verbose printing of proxies in 6.26
root-project/root pull request #11313
Opened 2022-09-04 13:27 UTC by will-cern

# This Pull request:

## Changes or fixes:
Fixes verbose printout of roofit object that uses RooListProxy (lots of classes do). 

## Checklist:

- [x ] tested changes locally
- [x ] updated the docs (if necessary)

This PR fixes #

2022-09-05 08:00 UTC, hageboeck requested changes
Hey Will,
good idea! I added a suggestion to save a few CPU cycles

2022-09-05 10:02 UTC, will-cern commented on roofit/roofitcore/src/RooAbsArg.cxx
> +      dynamic_cast<RooAbsCollection*>(proxy)->printStream(os,kName,kStandard,moreIndent.Data()) ;
thanks - I was too lazy to check if there was any virtual inheritance anywhere but I trust you that there isn't!

2022-09-05 11:51 UTC, hageboeck commented on roofit/roofitcore/src/RooAbsArg.cxx
> +      dynamic_cast<RooAbsCollection*>(proxy)->printStream(os,kName,kStandard,moreIndent.Data()) ;
Oh, there might be, but the compiler will complain if you cannot cross-cast. 🙂

2022-09-05 11:51 UTC, hageboeck commented
@phsft-bot build

2022-09-05 15:22 UTC, hageboeck commented on roofit/roofitcore/src/RooAbsArg.cxx
> +      dynamic_cast<RooAbsCollection*>(proxy)->printStream(os,kName,kStandard,moreIndent.Data()) ;
OK, I'll take it back! 🙂

2022-09-05 15:24 UTC, hageboeck commented
@will-cern Given that my idea didn't work, can we clean up the commit history using an interactive rebase or `git reset --hard <commit-hash>` to make the two extra commits disappear? It's safe to force-push to your current branch, so we merge only the first commit.

2022-09-05 16:49 UTC, will-cern commented
do MR not have their commits squashed?

2022-09-06 08:36 UTC, hageboeck commented
> do MR not have their commits squashed?

That's a viable option, indeed. 🙂 
@guitargeek Ready to merge (+squash)?

2022-09-06 08:36 UTC, hageboeck approved these changes
LGTM, but please squash on merge.

2022-09-06 14:08 UTC, merged

2022-09-06 14:09 UTC, hageboeck commented
@will-cern thanks for the fix!