[TMVA][SOFIE] Fix the Softmax operator
root-project/root pull request #11379
Opened 2022-09-15 15:17 UTC by axmat

## This Pull request

Add a missing attribute to the Softmax operator. the axis attribute describes the dimension along which the softmax will be computed as specified in the ONNX documentation https://github.com/onnx/onnx/blob/main/docs/Operators.md#Softmax.

## Checklist:

- [x] tested changes locally

2022-09-16 08:39 UTC, sanjibansg requested changes

2022-09-16 08:39 UTC, sanjibansg commented on tmva/sofie/inc/TMVA/ROperator_Softmax.hxx
> +         bool notHeigt = (size == 5 && axis != 3) || (size == 4 && axis != 2);
notHeight?

2022-09-16 09:20 UTC, axmat commented on tmva/sofie/inc/TMVA/ROperator_Softmax.hxx
> +         bool notHeigt = (size == 5 && axis != 3) || (size == 4 && axis != 2);
Fixed, thanks.

2022-09-19 13:42 UTC, lmoneta commented
@phsft-bot build just on ROOT-ubuntu2204/default, ROOT-ubuntu18.04/default with flags -Dtmva-sofie=On

2022-09-20 10:00 UTC, merged