Force storing of StreamerInfo for nested non-split but memberwise streamed collection.
root-project/root pull request #11446
Opened 2022-09-27 18:20 UTC by pcanal

This fix #11436# This Pull request:

2022-09-28 06:14 UTC, Axel-Naumann requested changes
Just making sure you saw the crucial functional change that's required...

2022-09-28 06:14 UTC, Axel-Naumann commented on io/io/src/TStreamerInfo.cxx
> +      if (false && valueClass)
```suggestion
      if (TClass *valueClass = fClass->GetCollectionProxy()->GetValueClass())
```

2022-09-29 11:39 UTC, pcanal commented
@phsft-bot build

2022-10-04 15:46 UTC, pcanal commented
All test passes as reported my the related roottest PR: https://github.com/root-project/roottest/pull/906#issuecomment-1265687117.

2022-10-04 15:46 UTC, merged