[rmkdepend] Use snprintf against warning (GCC 12.2):
root-project/root pull request #11861
Opened 2022-12-08 15:47 UTC by Axel-Naumann

```
build/rmkdepend/include.c:306:28: warning: ‘%s’ directive writing up to 8190 bytes into a region of size between 1 and 8191 [-Wformat-overflow=]
  306 |          sprintf(path, "%s/%s", *pp, include);
      |                            ^~
```

# This Pull request:

## Changes or fixes:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2022-12-08 15:52 UTC, pcanal approved these changes

2022-12-09 09:30 UTC, linev requested changes
Linking on mac is not working,
Probably, changing of `_POSIX_SOURCE` definition in `def.h` has side effect.

2022-12-13 09:28 UTC, Axel-Naumann commented
> Linking on mac is not working,

Can you share the linker error? I only see compilation errors (that I know how to take care of).

2022-12-13 10:05 UTC, linev commented
Maybe I was not precise - compiler cannot find `snprintf`. It is seen in error messages

2023-01-19 07:10 UTC, Axel-Naumann commented
@phsft-bot build just on ROOT-performance-centos8-multicore/cxx17

2023-01-19 07:11 UTC, Axel-Naumann commented
The windows "failure" isn't a failure but had just a warning, which is the usual mis-parse of the commit log.

2023-01-19 08:09 UTC, linev approved these changes

2023-01-19 11:53 UTC, merged

2023-01-23 16:51 UTC, Axel-Naumann commented
v6-28: https://github.com/root-project/root/pull/12099