GDML: Fix material properties
root-project/root pull request #11888
Opened 2022-12-13 16:48 UTC by MarkusFrankATcernch

# This Pull request:
- Eject material property refs as first child elements as required from the GDML schema
- Add the atomic number N to the `<atom>` attributes.
- Eject **const properties** as matrices in GDML with one element rather than constants.
- Consequently, when reading a 1x1 matrix, it will be declared as `const property` to the TGeoManager.

## Changes or fixes:
Creation of GDML files understood by Geant4

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2022-12-13 19:10 UTC, agheata commented
@phsft-bot build

2022-12-14 10:04 UTC, agheata requested changes
@MarkusFrankATcernch there are some changes related to units and clang-format-only that should not appear, can you please remove them?

2022-12-14 10:04 UTC, agheata commented on geom/gdml/src/TGDMLWrite.cxx
> +
This appears to be just a clang-format change

2022-12-14 10:04 UTC, agheata commented on geom/gdml/src/TGDMLWrite.cxx
> -   if ( gGeoManager->GetDefaultUnits() != TGeoManager::kRootUnits ) atom /= 1e19; // Correct for G4 unit system
This is unrelated to the PR

2022-12-14 10:04 UTC, agheata commented on geom/gdml/src/TGDMLWrite.cxx
> -   if ( gGeoManager->GetDefaultUnits() != TGeoManager::kRootUnits ) density /= 1e16; // Correct for G4 unit system
This is unrelated to the PR

2022-12-15 08:42 UTC, agheata commented
@phsft-bot build

2022-12-15 08:46 UTC, agheata commented
@MarkusFrankATcernch these commits should be squashed unless you want to do an interactive rebase and merge some of them manually. It does not make sense to have commits like "re-introducing bug to maximize number of commits" ;-)

2022-12-15 09:12 UTC, MarkusFrankATcernch commented
@agheata How is a "squash" done ? I am not at all a git expert....actually git is my outspoken enemy!

2022-12-15 09:21 UTC, agheata commented
> @agheata How is a "squash" done ? I am not at all a git expert....actually git is my outspoken enemy!

I can do it from the git web interface when merging, but this will squash all commits into one. Otherwise, if your branch started after say commit #N, you can locally rebase interactively the branch on top of that commit using `rebase -i #N`, which opens an editor and allows you to do actions like squashing commits. Then you must push the branch with --force, since you are altering history.

2022-12-15 09:39 UTC, MarkusFrankATcernch commented
@agheata In this case squashing all commits into the first one should be just perfect

2022-12-15 10:10 UTC, MarkusFrankATcernch commented
@agheata Will you do the "squash" please? I have no real clue what to type to get there ....

2022-12-15 10:11 UTC, agheata commented
> @agheata Will you do the "squash" please? I have no real clue what to type to get there ....

Sure, I will

2022-12-15 10:19 UTC, MarkusFrankATcernch commented
@agheata Thanks a lot!

2022-12-15 13:23 UTC, agheata approved these changes

2022-12-15 13:24 UTC, merged