[RelNotes] Add all known contributors with >1 commit (NFC).
root-project/root pull request #12131
Opened 2023-01-27 12:23 UTC by Axel-Naumann

Please lmk if you want affiliations changed. FYI, @HDembinski @SimeonEhrig @matthewfeickert @olifre @sayang14 @weliveindetail @ShamrockLee @Moelf @mrexodia @tapaswenipathak @dkpoult @mphschmitt @Neel-Shah-29 @petrstepanov @saisoma123 @andriish @fwinkl @junaire 

And thank you 💐 for your contributions to ROOT v6.28 - much appreciated!

2023-01-27 15:36 UTC, Axel-Naumann commented
You know what, let me just merge it; let's do iterations if something is not perfect!

2023-01-27 15:36 UTC, merged

2023-01-27 15:42 UTC, ShamrockLee requested changes
Thanks for including me in the contributor list! It's my honor to participate in such a great project!

2023-01-27 15:42 UTC, ShamrockLee commented on README/ReleaseNotes/v628/index.md
> + Shamrock Lee,\
My legal name is Yueh-Shun Li (李岳瞬 in Mandarin). I'm a graduate student in National Central University (in Taiwan) working on HEP data analysis using CMS dataset.

```suggestion
 Shamrock Lee,\
 Yueh-Shun Li, National Central University,\
```

2023-01-27 15:46 UTC, Axel-Naumann commented on README/ReleaseNotes/v628/index.md
> + Shamrock Lee,\
> My legal name is

You can freely choose the name you want to see here; I take your comment that you want to see "Yueh-Shun Li, National Central University"; I'll add "Taiwan/CMS", i.e.
```suggestion
 Yueh-Shun Li, National Central U Taiwan/CMS,\
```
OK?

2023-01-27 15:49 UTC, ShamrockLee commented on README/ReleaseNotes/v628/index.md
> + Shamrock Lee,\
Sure. Thank you!

2023-01-27 17:53 UTC, Axel-Naumann commented on README/ReleaseNotes/v628/index.md
> + Shamrock Lee,\
Thanks, that's now 58d14187f09e2f0a6a0fd08174dec3ad5e3a6c12

2023-01-28 18:31 UTC, ShamrockLee commented
Just found that the above change is made in the 6.26 release note on the `v6-28-00-patches` branch, and the 6.28 release note is still waiting for the update.

2023-01-29 14:49 UTC, Axel-Naumann commented
Thanks @ShamrockLee fixed!