[build] Add Python executable to root-config
root-project/root pull request #12299
Opened 2023-02-13 14:11 UTC by vepadulano

To allow
```
vpadulan@fedora [~/programs/rootproject/rootinstall]: root-config --python-executable
/usr/bin/python3.10
vpadulan@fedora [~/programs/rootproject/rootinstall]: root-config --python3-executable
/usr/bin/python3.10
vpadulan@fedora [~/programs/rootproject/rootinstall]: root-config --python2-executable
/usr/bin/python2.7
vpadulan@fedora [~/programs/rootproject/rootinstall]: `root-config --python2-executable` -c "import ROOT; print(ROOT.__version__)"
6.29/01
vpadulan@fedora [~/programs/rootproject/rootinstall]: `root-config --python-executable` -c "import ROOT; print(ROOT.__version__)"
6.29/01
```

2023-05-16 11:48 UTC, Axel-Naumann approved these changes

2023-05-16 11:48 UTC, Axel-Naumann commented
But consider removing python2 support from master (instead).

2023-11-13 14:13 UTC, guitargeek commented
@vepadulano what is the plan now that this PR didn't make it to 6.30, and Python 2 support will  be removed from 6.32 anyway?

2023-11-13 14:18 UTC, vepadulano commented
@guitargeek I believe the best course of action is remove Python2 usage first, then provide the `python3` executable path only, via `root-config`, in 6.32 as well

2024-04-08 01:44 UTC, guitargeek requested changes
@vepadulano, why do we need this again? Hardcoding executable paths like that is usually not ideal

2024-05-09 10:15 UTC, guitargeek commented
Closing after private discussion with @vepadulano

2024-05-09 10:15 UTC, closed without merging