Batch generator c++
root-project/root pull request #12485
Opened 2023-03-14 13:49 UTC by DanteNiewenhuis

# This Pull request:

## Changes or fixes:

- Added the BatchGenerator, BatchLoader, and ChunkLoader C++ classes.
  Used to generate batches from a RDataset for Machine Learning purposes

- Added _batchgenerator.py used to interact with the BatchGenerator class from Python.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2023-03-14 14:43 UTC, jalopezg-git commented on tmva/tmva/inc/TMVA/BatchGenerator.hxx
> +                   std::vector<std::string> _filters, size_t _chunk_size, size_t _batch_size, std::vector<size_t> _vec_sizes = {}, double _validation_split=0.0,
Is it intended that some of the arguments are pass-by-value; passing (const) l-value references should avoid some additional unneeded copies.

2023-03-14 14:43 UTC, jalopezg-git commented on tmva/tmva/inc/LinkDef1.h
> +#pragma link C++ class TMVA::Experimental::ChunkLoader;
@lmoneta can tell whether this is needed at all; in principle only if introspection or I/O of these classes is required.

2023-03-14 14:43 UTC, jalopezg-git commented on tmva/tmva/inc/TMVA/BatchLoader.hxx
> +    TMVA::Experimental::RTensor<float>* GetTrainBatch()
Consider moving some (if not all) the member functions below to a dedicated translation unit, i.e. a `.cxx` file.

2023-03-14 14:43 UTC, jalopezg-git commented on tmva/tmva/inc/TMVA/ChunkLoader.hxx
> +template <typename First, typename... Rest>
I see that all the member functions are templated and the `First` and `Rest` arguments of this class template are unused.  Can we fix that, e.g. demoting to non-class-template, or any other fix that is appropriate?

2023-07-10 09:36 UTC, lmoneta commented
@phsft-bot build!

2023-07-10 12:49 UTC, lmoneta commented
@phsft-bot build on ROOT-debian10-i386/soversion

2023-07-10 13:35 UTC, lmoneta commented
@phsft-build build

2023-07-10 13:36 UTC, lmoneta commented
@phsft-bot build

2023-07-11 08:03 UTC, DanteNiewenhuis commented
@phsft-bot build

2023-07-11 08:29 UTC, vepadulano commented
@phsft-bot build

2023-07-11 09:07 UTC, vepadulano requested changes
Hi Dante, thanks a lot for all this work! So nice to see that now we have a working feature, and kudos for adding all the tutorials! Splendid!

The design and functionality look very good. I have left comments that involve style, code correctness, formatting. Also there are many spurious changes probably leftover from previous iterations of your work. Please take some time to address them so that this PR could get to a well deserved polished status.

2023-07-11 09:07 UTC, vepadulano commented on tmva/tmva/inc/TMVA/RChunkLoader.hxx
> +         // TODO: return passed_events
I think you now return passed events right?

2023-07-11 09:07 UTC, vepadulano commented on tmva/tmva/inc/TMVA/RChunkLoader.hxx
> +#endif // TMVA_CHUNKLOADER
Missing newline at end of file. This should be configurable in your editor

2023-07-11 09:07 UTC, vepadulano commented on tree/dataframe/src/RLoopManager.cxx
>     if (r != nullptr) {
Spurious

2023-07-11 09:07 UTC, vepadulano commented on tutorials/tmva/RBatchGenerator_TensorFlow.py
> +##############################################################################
Probably unnecessary

2023-07-11 09:07 UTC, vepadulano commented on tutorials/tmva/RBatchGenerator_filters_vectors.py
> +ROOT.EnableThreadSafety()
Ugly, needed?

2023-07-11 09:07 UTC, vepadulano requested changes
Hi Dante, thanks a lot for all this work! So nice to see that now we have a working feature, and kudos for adding all the tutorials! Splendid!

The design and functionality look very good. I have left comments that involve style, code correctness, formatting. Also there are many spurious changes probably leftover from previous iterations of your work. Please take some time to address them so that this PR could get to a well deserved polished status.

2023-07-11 09:14 UTC, DanteNiewenhuis commented on bindings/pyroot/pythonizations/python/ROOT/_facade.py
>      """
I think it is my autoformatter that adheres to the sonartype-lift formatting (everything less than 80 lines)

2023-07-11 09:16 UTC, DanteNiewenhuis commented on tutorials/tmva/RBatchGenerator_PyTorch.py
> +ROOT.EnableThreadSafety()
I think you are pointing to the EnableThreadSafety? Because that is not needed indeed. I will remove it

2023-07-11 09:29 UTC, DanteNiewenhuis commented on bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
> +from ._tree_inference import SaveXGBoost, pythonize_tree_inference
I don't know what this is.
I am not aware that I added this line.

2023-07-11 09:43 UTC, DanteNiewenhuis commented on tmva/tmva/inc/TMVA/RChunkLoader.hxx
> +   // Add a label to the end of the row if given
Old functionality that has been removed for this PR. 
I will remove the comment for now

2023-07-11 15:08 UTC, vepadulano commented
@phsft-bot build

2023-07-12 08:30 UTC, vepadulano commented
@phsft-bot build

2023-07-14 09:10 UTC, vepadulano commented
@phsft-bot build

2023-07-17 10:22 UTC, vepadulano commented
@phsft-bot build

2023-07-17 12:49 UTC, vepadulano commented
`datasetspec` test failure is unrelated, fixing it at https://github.com/root-project/root/pull/13263

The tutorial failure on mac12arm looks very real, but unfortunately it's in cling and I don't think fixing it is in the scope of this PR.

2023-07-17 13:49 UTC, vepadulano commented
@phsft-bot build just on mac12arm/cxx20 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug

2023-07-17 19:41 UTC, vepadulano commented
@phsft-bot build just on mac12arm/cxx20 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug

2023-07-18 07:46 UTC, vepadulano commented
@phsft-bot build just on mac12arm/cxx20 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug -DCTEST_TEST_EXCLUDE_NONE=On

2023-07-18 12:52 UTC, vepadulano commented
@phsft-bot build just on mac12arm/cxx20 with flags -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=Debug -DCTEST_TEST_EXCLUDE_NONE=On

2023-07-19 11:46 UTC, vepadulano approved these changes
Thank you @DanteNiewenhuis, this is a lot of nice work, congrats!

Merging the PR, the test failures are unrelated (the ones regarding the tutorials seem to be triggered by some not-well-understood issue in TClass & friends, possibly regarding thread-safety, to be investigated)

2023-07-19 11:47 UTC, merged

2023-07-19 13:33 UTC, hahnjo commented
> Merging the PR, the test failures are unrelated (the ones regarding the tutorials seem to be triggered by some not-well-understood issue in TClass & friends, possibly regarding thread-safety, to be investigated)

Unrelated or not, these will now fail in every PR. That's not good, it is still your responsibility to keep the builds green...

2023-07-20 11:28 UTC, hahnjo commented
This also broke configuration without Python, fix in https://github.com/root-project/root/pull/13292