[c++20] Fix several tests and tutorials with -std:c++20
root-project/root pull request #12526
Opened 2023-03-22 11:39 UTC by bellenot

2023-03-24 18:09 UTC, Axel-Naumann approved these changes
This likely requires different fixes - not just on the caller side. But it's a great compilation of what we need to do, thanks, @bellenot !

So please don't merge (that's why I'm setting "request changes") - but also please don't spend time on this for the time being.

2023-03-24 18:09 UTC, Axel-Naumann commented on hist/histv7/test/fill.cxx
> +   hist.FillN({{0.1111, 0.3333}});
Could you remove this file from this PR? This will make it fail on clang - I will provide a solution that works for everyone, in a separate PR.

2023-03-24 18:09 UTC, Axel-Naumann commented on tree/dataframe/test/dataframe_interface.cxx
> +   RDataFrame tdf("t", {{"f1"}, {"f2"}});
This might not be what we want. @eguiraud ? (I.e. yes it might fix the build but we might want to change the API.)

2023-03-24 18:10 UTC, Axel-Naumann requested changes
Wrong button, I mean to block this :-)

2023-03-24 19:39 UTC, Axel-Naumann commented on tree/dataframe/test/dataframe_interface.cxx
> +   RDataFrame tdf("t", {{"f1"}, {"f2"}});
At least according to MSVC: indeed.

I don't think GCC or clang complained about that (and as a consequence they _will_ likely complain about this change).

2023-03-24 22:52 UTC, bellenot commented
Don't worry, that was mostly for me to check other platforms, I was not going to merge

2023-03-27 08:16 UTC, Axel-Naumann commented
FYI @eguiraud , GCC 12.2, C++20, and RDF shows e.g.
```
tree/dataframe/test/dataframe_regression.cxx: In member function ‘virtual void RDFRegressionTests_UniqueEntryNumbers_Test::TestBody()’:
tree/dataframe/test/dataframe_regression.cxx:145:48: error: call of overloaded ‘RDataFrame(const char* const&, <brace-enclosed initializer list>)’ is ambiguous
  145 |    ROOT::RDataFrame df(treename, {fname, fname});
      |                                                ^
```
Possibly similar / related?

2023-03-29 13:56 UTC, Axel-Naumann commented
This is now addressed in https://github.com/root-project/root/pull/12519

2023-03-29 13:56 UTC, closed without merging