[ntuple] Add `RNTupleInspector::Create` for ntuple name and source path
root-project/root pull request #12574
Opened 2023-03-29 13:11 UTC by enirolf

This PR adds a new `Create` factory method to the `RNTupleInspector` that takes the name and source path of the `RNTuple` to be inspected as its arguments. This removes the need for the user to open the relevant `TFile` and load the `RNTuple` manually, which can be useful in case one is only interested in inspecting an `RNTuple`.

Additionally, a check is added to the existing `Create(RNTuple *sourceNTuple)` method to make sure the pointer that was passed does not refer to null.

2023-03-30 12:12 UTC, Axel-Naumann commented
@phsft-bot build

2023-03-30 12:13 UTC, Axel-Naumann commented
(I've added @enirolf to the team, FYI @jblomer )

2023-05-13 13:18 UTC, jblomer requested changes
Looks good to me! Just two nits.

2023-05-13 13:18 UTC, jblomer commented on tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
> +   std::unique_ptr<TFile> fSourceFile;
We should forward-declare `TFile`

2023-05-13 13:18 UTC, jblomer commented on tree/ntupleutil/v7/test/ntuple_inspector.cxx
> +      RNTupleWriter::Recreate(std::move(model), "ntuple", fileGuard.GetPath());
```suggestion
      RNTupleWriter::Recreate(RNTupleModel::Create(), "ntuple", fileGuard.GetPath());
```

2023-05-17 14:44 UTC, merged