Updating RDatasetSpec docs with Cpp MWE
root-project/root pull request #12859
Opened 2023-05-19 15:42 UTC by edfink234

# This Pull request:

## Changes or fixes:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2023-05-25 13:18 UTC, vepadulano requested changes
Hi @edfink234 ,

Thanks for giving this a shot. I have placed some comments below. I think the idea of placing detailed explanation about how to create an `RDatasetSpec` should be placed in its own documentation. I don't think this constructor should publicize this too much. Maybe a link to the class itself could be enough. See the rest of the comments below as well.

2023-05-25 13:18 UTC, vepadulano commented on tree/dataframe/src/RDataFrame.cxx
> +/////First, create a dummy root file with two trees,
The example code should have a whitespace between the three forward slashes that are needed for doxygen and the rest of the body, as found in lines above

2023-05-25 13:18 UTC, vepadulano commented on tree/dataframe/src/RDataFrame.cxx
> +///columns.Snapshot("outputTree2", "outputFile.root", {"z"}, opts);
I am curious as to why you think that adding this portion of the example is relevant for this particular constructor. This looks more like the beginning of a short tutorial, doesn't it?

2023-05-25 13:18 UTC, vepadulano commented on tree/dataframe/src/RDataFrame.cxx
> +///df.Display({"x","y","z"}, 10)->Print(); //all three columns are printed
The inner details of the creation of an `RDatasetSpec` are probably better off in the documentation of `RDatasetSpec` itself. I don't think that this interface will anyway be the "suggested" one for 99% of users, that's going to be creating the RDF via `FromSpec`.

2023-06-06 13:58 UTC, vepadulano requested changes
Admittedly the example is not the most common one, having one main file with the main tree and one separate friend file with the friend tree would be more common I believe. Still, it is a good example and written in the correct place, thanks for that!

Before merging, can you squash the 2 commits into one? Afterwards, we can merge this PR.

2023-06-08 17:16 UTC, edfink234 commented
I think I did it...

2023-06-09 07:54 UTC, vepadulano approved these changes

2023-06-09 07:54 UTC, merged