[DF] Use FromSpec in df106_HiggstoFourLeptons.py tutorial
root-project/root pull request #12929
Opened 2023-06-01 09:01 UTC by martamaja10

Now one RDF is used instead of a number of individual ones
and users can see what a dataset specification file looks like
and how to access the metadata information.

2023-06-02 15:37 UTC, eguiraud commented
Hi @martamaja10 , please note that merging master into the feature branch is usually discouraged as it complicates the git history. It's typically better to rebase your feature branch on top of latest master if you need to fix conflicts or similar.

2023-06-02 15:57 UTC, eguiraud commented
See also https://chris.beams.io/posts/git-commit for the usual conventions around git commit messages.

To play nice with `git --oneline` or other ways to visualize git logs it should look something like this:

```
[DF] Use FromSpec in df106_HiggstoFourLeptons.py tutorial

Now one RDF is used instead of a number of individual ones
and users can see what a dataset specification file looks like
and how to access the metadata information.
```

2023-06-05 08:12 UTC, vepadulano requested changes
See some minor style comments. The Jenkins build is already green. I agree with Enrico about improving the commit history. Once these things are taken care of we can merge.

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
> +df = ROOT.RDF.Experimental.FromSpec(my_spec) #creates a single dataframe for all the samples
Just a small typo
```suggestion
df = ROOT.RDF.Experimental.FromSpec(my_spec) # Creates a single dataframe for all the samples
```

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
> +df = df.DefinePerSample("xsecs", 'rdfsampleinfo_.GetD("xsecs")') #GetD for "double"
I don't think we should place comments like `GetD for double` and similar here. For the documentation users should refer to `RDFSampleInfo` or `RMetaData`. What maybe we can do is writing above the first call to `DefinePerSample` a comment similar to

```
# The metadata contained in the JSON file is accessible within a `DefinePerSample` call, through the `RDFSampleInfo` class
```

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
> +df = df.DefinePerSample("sample_category", 'rdfsampleinfo_.GetS("sample_category")') #GetS for "string"
Again here I would remove the comment

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
>      # irrespective of the charge.
These comments should be properly deindented to respect the following lines

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
> +             .Filter("goodlep_sumtypes == 44 || goodlep_sumtypes == 52 || goodlep_sumtypes == 48")
The indentation here looks a bit weird. Can it be so that every new line is aligned with the `.Define` of the first line?

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
> +    histos.append(df.Filter(f"sample_category == \"{sample_category}\"").Histo1D(ROOT.RDF.TH1DModel(f"\"{sample_category}\"", "m4l", 24, 80, 170), "m4l", "weight"))
I don't think the title of the `TH1DModel` needs the quotes right?

```suggestion
    histos.append(df.Filter(f"sample_category == \"{sample_category}\"").Histo1D(ROOT.RDF.TH1DModel(f"{sample_category}", "m4l", 24, 80, 170), "m4l", "weight"))
```

2023-06-05 08:12 UTC, vepadulano commented on tutorials/dataframe/df106_HiggsToFourLeptons.py
> +print("Saved figure to df106_HiggsToFourLeptons.png")
Missing newline at end of file

2023-06-19 14:45 UTC, vepadulano approved these changes
Looks good, thanks a lot Marta!

2023-06-19 14:54 UTC, merged