Implementation of Mollweide projection for TH2 histograms
root-project/root pull request #13212
Opened 2023-07-07 16:07 UTC by xKZL

# This Pull request:
It is an attempt to implement Mollweide projection for drawing 2D histograms in standard ROOT (and web-based ROOT).
https://github.com/root-project/root/pull/13211

## Changes or fixes:
I implemented a version of Mollweide projection today based on the litterature.

## Checklist:

- [X] tested changes locally
- [X] updated the docs (if necessary)

This PR fixes a missing features

2023-07-07 16:33 UTC, xKZL commented
Hi @linev, here we are. Please let me know about JS. there is no way to PR in root-project/jsroot 
So I just changed files contained in ./js/gpad here. maybe it needs to be rebuilt ?

2023-07-07 16:36 UTC, linev commented
I will check PR begin of next week.
PR to jsroot can be created separately.
But do not warry - I will copy necessary changes by hand.

2023-07-10 08:34 UTC, linev commented
Hi,

Your code in JSROOT was not working.  
I add commit to JSROOT with proper implementation:

https://github.com/root-project/jsroot/commit/3fa5882ebb8aa17eaa704bcc7319a0dac4eb1258

I also used second variant of iteration mentioned in https://en.wikipedia.org/wiki/Mollweide_projection#cite_note-6
It avoids infinite values. 

Also there are unnecessary scaling coefficients, which are vanishing at the end.

2023-07-10 08:35 UTC, linev requested changes
Please modify PR that only C++ code is changed. 
Changes in JSROOT I will merge later

2023-07-10 08:36 UTC, linev commented
And please adjust C++ implementation that it corresponds to modified JavaScript code

2023-07-10 08:38 UTC, linev commented
> How should I proceed, just rollback or open a new PR again ?

You always can rebase your branch and do `git push --force`.

For the future - it is better not to use `master` branch to create your PRs.

2023-07-11 07:49 UTC, closed without merging

2023-07-11 09:22 UTC, xKZL commented
too many commit ahead, i opened a new PR.. https://github.com/root-project/root/pull/13226