[ntuple] add chain support for RDF data source
root-project/root pull request #13329
Opened 2023-07-26 13:15 UTC by jblomer

Adds a new constructor to the RNTuple RDF data source that takes an ntuple name and a list of files. The data source then treats these files as a chain. This is a transitional solution until chains are supported by the underlying RNTuple layer.

Also slightly simplifies the prototype construction in the RNTuple data source: instead of constructing full column reader prototypes, only the corresponding field prototypes are constructed.

2023-07-26 14:26 UTC, jblomer commented
There is still the non-trivial question of how to distribute work to slots. So while this change makes it possible to process RNTuple chains with RDF, it's rather sub optimal because parallelization is only within a single file and it is not respecting cluster boundaries.

2023-07-28 15:03 UTC, eguiraud commented
About work distribution, IIUC currently each sub-rntuple in a chain is processed sequentially, with parallelism possible within the processing of each sub-rntuple.

Unfortunately with the current RDataSource API we cannot pull a trick like distRDF does, distributing ranges as file %'s and figuring out exact event-level splitting later. One pass over the full chain might be necessary, at least for now.

2023-11-30 09:44 UTC, enirolf commented on tree/dataframe/inc/ROOT/RNTupleDS.hxx
> +   std::vector<REntryRange> fNextRanges;    ///< Basis for the ranges returned by the next GetEntryRanges() call
```suggestion
   std::vector<REntryRange> fNextRanges;    ///< Basis for the ranges populated by the PrepareNextRanges() call
```

2023-11-30 10:42 UTC, enirolf requested changes
Many thanks! I've added a few comments and clarifying questions. Maybe a general question: there are a few `R__ASSERT`s. Is there any way these could be hit by users, and should those be turned into exceptions instead?

2023-12-05 10:26 UTC, jblomer commented on tree/dataframe/src/RNTupleDS.cxx
> +         fField->SetOnDiskId(
Two fields (`RFieldBase` objects) created for RDataFrame can end up having the same field ID if they represent the same underlying physical field in different ways. For instance, for a `vector<float>` field, the field as `vector<float>` has the same ID than the field that represents the size of the vector.

On disk, all fields have their own, unique ID.

2023-12-07 13:33 UTC, vepadulano approved these changes
Thank you so much for this! I have a couple of comments regarding parts of the logic, we can iterate over these also in a separate PR, so feel free to merge.

2023-12-07 15:22 UTC, enirolf approved these changes

2023-12-07 19:30 UTC, merged