[tree] Clarify error message
root-project/root pull request #13386
Opened 2023-08-02 18:22 UTC by eguiraud

2023-08-03 13:18 UTC, jalopezg-git approved these changes

2023-08-03 13:22 UTC, jalopezg-git requested changes
Uh, I was too quick to approve, `tree/dataframe/test/dataframe_snapshot.cxx` has to be changed too :slightly_smiling_face:!

2023-08-04 07:56 UTC, vepadulano approved these changes
Yep, makes sense, thank you!

2023-08-04 11:24 UTC, Axel-Naumann approved these changes

2023-08-04 11:24 UTC, Axel-Naumann commented on tree/tree/src/TTree.cxx
>                         "bit manually if you know what you are doing.";
```suggestion
                       "bit manually if you know what you are doing; you risk associating wrong TTree entries of the friend wrt the main TTree!";
```
or similar would be even nicer :-)

2023-08-04 13:56 UTC, eguiraud commented on tree/tree/src/TTree.cxx
>                         "bit manually if you know what you are doing.";
done!

2023-08-06 18:07 UTC, merged

2023-08-07 23:35 UTC, pcanal commented on tree/tree/src/TTree.cxx
> +         "main tree has a TTreeIndex on the friend tree '%s'. You can also unset the bit manually if you know what you "
I am not understanding the wording "the main tree has a TTreeIndex on the friend tree".   If I remember correctly in order for a friend to be properly read when "out of order", the index needs to be build in the friend. as the index contains the entry number corresponding to a given `Major/Minor' (eg Run Number /  Entry Number).   So we call `BuildIndex` on the friend (referring to column with the same names in both) and the main tree does not (directly) know about the index .