Add test coverage using codecov
root-project/root pull request #13394
Opened 2023-08-03 17:21 UTC by AniqJaved

# This Pull request:

## Changes or fixes:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2023-08-03 17:56 UTC, AniqJaved commented
Kindly run the ROOT CI TEST action in order to avoid conflicts.

2023-08-03 19:54 UTC, Axel-Naumann commented
This was waiting for a team member to trigger the CI run - I did that just now.

2023-08-03 20:05 UTC, Axel-Naumann requested changes
Awesome, @AniqJaved - thanks a lot for all your work! 
- Could you please reduce the number of commits to something like 5 max? I'm happy to. show you how to rewrite the commit history.
- `.github/workflows/root-ci-config/__pycache__/build_utils.cpython-39.pyc`, `patch.txt`, and `.github/workflows/root-ci-config/test_file.py` won't be needed in the repo, please don't add them.
- `.github/workflows/test-coverage.yml` needs only one platform iiuc? Why does it have e.g. `build-macos`?

2023-08-04 13:50 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +name: 'ROOT CI TEST'
"Test Coverage"?

2023-08-04 15:21 UTC, Axel-Naumann requested changes
Very nice, several things we'll want to discuss next week, but it's an amazing first step!

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +                    --incremental    ${{ inputs.incremental }}
See above.

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +
Please remove.

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +
We don't need / want this.

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +        if: ${{ matrix.image == 'fedora38-cov' && !cancelled() }}
```suggestion
        if: ${{ !cancelled() }}
```
As this file is now *only* about coverage we know this is a coverage build :-)

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +      #   timeout-minutes: ${{ github.event.pull_request && 40 || 20 }}
Can this commented block go away? It doesn't seem to add much...

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +        path: ${{ github.event_path }}
I don't think we need this section. But we do want a newline at the end of the file :-)

2023-08-04 15:21 UTC, Axel-Naumann commented on .github/workflows/test-coverage.yml
> +        uses: codecov/codecov-action@v3
How is this authenticated? I suspect this needs a token? But that token won't be exposed to `pull_request` builds. Please have a look [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), where they build with minimal credentials (`pull_request`), store the result as an artifact (we don't even need that!), and finally run the step that needs more permissions (in our case: to read secrets) to work just on the generated artifact. We can simply access that file in the `pull_request_target` part after the `pull_request` part building, testing, and generating the XML file has finished.

Let's discuss next week!

2023-08-08 11:38 UTC, closed without merging