[GSOC][TMVA][SOFIE] Elu ONNX operator implemented
root-project/root pull request #13544
Opened 2023-08-25 14:37 UTC by Neel-Shah-29

2023-08-30 16:02 UTC, lmoneta commented
@phsft-bot build

2023-08-31 08:33 UTC, sanjibansg requested changes
Looks good overall, just a minor change with formatting.

2023-08-31 08:33 UTC, sanjibansg commented on tmva/sofie/inc/TMVA/ROperator_Elu.hxx
> +		}
nit: fix the formatting here

2023-09-02 10:14 UTC, sanjibansg approved these changes
LGTM!

For the future, for coding styles, prefer using a formatting tool like clang-format or style
ref: https://root.cern/contribute/coding_conventions/#astyle

2023-12-11 11:24 UTC, merged