[cling,v6-28] DeclUnloader: fix unloading of member functions of templated classes
root-project/root pull request #13618
Opened 2023-09-06 12:47 UTC by jalopezg-git

This pull request is a backport of PR #13534 (a NFC; makes the code more readable) and PR #13565 (actual fix for unloading member functions of templated classes).
The aforementioned PRs have been reviewed separately.

## Changes or fixes:
For the actual list of changes, see
- https://github.com/root-project/root/pull/13534
- https://github.com/root-project/root/pull/13565

## Checklist:
- [x] tested changes locally
- [x] updated the docs (if necessary)
- [x] Passes cling test suite 

This PR fixes #10049, #6439, #7970, [ROOT-10848](https://sft.its.cern.ch/jira/browse/ROOT-10848) and [ROOT-8084](https://sft.its.cern.ch/jira/browse/ROOT-8084) and (hopefully also [ROOT-8245](https://sft.its.cern.ch/jira/browse/ROOT-8245)).

2023-09-26 02:35 UTC, pcanal approved these changes

2023-10-06 08:49 UTC, hahnjo requested changes
to make it explicit: this is causing failures of `stressInterpreter` on macOS and must not be merged for now.

2023-10-18 19:42 UTC, jalopezg-git commented
> to make it explicit: this is causing failures of `stressInterpreter` on macOS and must not be merged for now.

That's true; I'll have to check how to fix this...  Currently, it seems non-trivial: we probably need to judge whether to unload a declaration or not by looking at the whole chain of (implicit) instantiations :man_shrugging:.

2023-12-05 13:35 UTC, jalopezg-git commented
Unsure as to whether backporting to v6.28 is still needed.  Feel free to close the PR otherwise :slightly_smiling_face:.

2023-12-05 13:43 UTC, hahnjo commented
> Unsure as to whether backporting to v6.28 is still needed. Feel free to close the PR otherwise 🙂.

I think we want to backport, I will take care of updating the PR in the next days. Also, we definitely want a backport to v6.30, also to come in the next days.

2023-12-13 09:05 UTC, hahnjo approved these changes
All green now :smiley:

2023-12-13 09:06 UTC, merged