[ntuple] Add `GetColumnTypeInfoAsHist` to `RNTupleInspector`
root-project/root pull request #13715
Opened 2023-09-25 09:39 UTC by enirolf

This PR adds the feature to get a histogram representing different possible column type-related properties. These properties are the type count, number of elements per type, compressed size per type and uncompressed size per type.

The current version automatically sets the histogram title based on the information it shows. The title can be changed after returning it using `TH1::SetTitle`. An alternative could be to add another argument which has the default value that is currently used but can be used to provided an alternative title.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

2023-09-25 13:33 UTC, vepadulano requested changes
Thanks for this nice improvement! I wanted to discuss with you the possibilities regarding histogram name and title. The current `std::string_view histName` parameter is optional, but in the added test you always specify it. Instead, the histogram title is chosen based on the type of histogram that is being requested. So, let's imagine I call the function like so
```
   auto inMemSizeHist = inspector->GetColumnTypeInfoAsHist(
      ROOT::Experimental::ENTupleInspectorHist::kInMemSize)
```
Then I would get `columnTypeHist` as the histogram name and `Uncompressed size by column type`. So the name is too generic w.r.t. the title.

Here is my proposal:
```cpp
GetColumnTypeInfoAsHist(
   ENTupleInspectorHist histKind,
   std::optional<std::string> histName,
   std::optional<std::string> histTitle);
```
And in the implementation, if any of the two optional values is passed, the `switch` statement is not even triggered (one switch for the name, one for the title) otherwise the user gets sensible default values.

2023-09-26 07:26 UTC, enirolf commented
Thanks for your suggestion, that makes total sense!

2023-09-26 08:51 UTC, enirolf commented on tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
> +   /// type present in the inspected RNTuple.
N.B. I will change the documentation for the other methods to this format in another PR.

2023-09-26 16:27 UTC, vepadulano approved these changes
LGTM thank you!

2023-10-04 11:43 UTC, merged