[skip-ci] [core] Add rpath on MacOS in TSystem::CompileMacro
root-project/root pull request #13737
Opened 2023-09-27 14:07 UTC by vepadulano

The generated compiler invocation in TSystem::CompileMacro doesn't add the `-rpath` option. The output of `root-config --libs` contains that option on MacOS, so we should also have it here. This should fix errors seen in MacOS 14 when loading a shared library obtained via ACLiC.

Fixes #13734

2023-09-27 14:08 UTC, vepadulano commented
@phsft-bot build also on macbeta/cxx20

2023-09-27 15:09 UTC, guitargeek commented
Hi, thanks for the quick fix :+1:

I'm not sure if this is really the sustainable solution though. As you see in the [root-config script](https://github.com/root-project/root/blob/master/config/root-config.in#L399), there are also other platforms that might use `-rpath`.

Is there maybe a way to get these `root-config --auxlibs` directly into the ACLiC command, without hardcoding the flags again behind various preprocessor guards for different platforms?

2023-09-27 15:53 UTC, vepadulano commented
> Is there maybe a way to get these root-config --auxlibs directly into the ACLiC command, without hardcoding the flags again behind various preprocessor guards for different platforms?

I do believe that is the right question to ask! Unfortunately, I have no idea about the answer :/

2023-09-28 03:07 UTC, pcanal commented
The source of information for `ACLiC` is the generated `compiledata.h`.  We need the update the generation (done via CMake) to include `-Wl,-rpath,$ROOTSYS/lib` when needed (instead of changing `CompileMacro` itself).

2023-09-28 03:07 UTC, pcanal requested changes
See comment

2023-09-29 09:29 UTC, vepadulano commented
@phsft-bot build also on macbeta/default

2023-09-29 11:54 UTC, merged