[core] Copy gitinfo.txt to the install directory
root-project/root pull request #13794
Opened 2023-10-03 14:46 UTC by vepadulano

2023-10-04 06:31 UTC, Axel-Naumann requested changes

2023-10-04 06:31 UTC, Axel-Naumann commented on core/CMakeLists.txt
> +  COMMAND ${CMAKE_COMMAND} -DSRCDIR=${CMAKE_SOURCE_DIR} -DBINDIR=${CMAKE_BINARY_DIR} -DINSTALL_DIR=${CMAKE_INSTALL_PREFIX} -P ${CMAKE_SOURCE_DIR}/cmake/modules/UpdateGitInfo.cmake
Instead of using the script to write the file, shouldn't we simply use the `installl()` CMake function to install it?

2023-10-04 06:32 UTC, Axel-Naumann commented
I think apart from the installation I need to teach `TROOT` (or whoever else is reading this file) to read it from the build directory if we cannot read it from the install directory (e.g. because ROOT hasn't been installed yet). What do you think?

2023-10-04 16:02 UTC, vepadulano commented
> What do you think?

I think it makes sense if and only if ROOT hasn't been installed yet. But I'm also thinking about the case of a packaged ROOT installation, there's no build directory there. So the logic that needs to read this file should be able to distinguish which is the "current" path at which the file must be read from.

2023-10-06 08:58 UTC, Axel-Naumann approved these changes

2023-10-06 13:46 UTC, merged