[relnotes] Add missing contributors
root-project/root pull request #14006
Opened 2023-11-01 23:21 UTC by vepadulano

Backport of #14005

2023-11-24 20:22 UTC, Axel-Naumann requested changes

2023-11-24 20:22 UTC, Axel-Naumann commented on README/ReleaseNotes/v630/index.md
> + Silia Taider, CPE Lyon and CERN EP-SFT
Alphabetical order, please!

2023-12-27 07:13 UTC, dpiparo commented
@vepadulano, an easy one to merge

2024-01-12 13:37 UTC, dpiparo approved these changes
Thanks @vepadulano !

2024-01-12 13:40 UTC, merged