[skip-ci] Update fonts' documentation (CMS request)
root-project/root pull request #14049
Opened 2023-11-14 10:23 UTC by couet

Better description of fonts' names.

2023-11-15 13:15 UTC, vepadulano requested changes
The update looks good, thanks! Can we try to make it even more clear for external users by pointing to where these nomenclatures were originally defined?

2023-11-15 13:15 UTC, vepadulano commented on core/base/src/TAttText.cxx
> +   Font number         X11 Names             TTF Names                  PDF Names
The new names look good, but could we add some documentation or links to the original source for `X11` names or `TTF` or `PDF` names. From my perspective, reading `TTF Names` or the others doesn't really tell me much about these names. Who decided what `TTF Names` are? Is there some documentation somewhere in the original protocols/repositories? Similarly for X11 and PDF

2023-11-17 09:59 UTC, couet commented
I can add the explanations I put here: https://github.com/root-project/root/issues/14064

2023-11-17 12:31 UTC, couet commented
I have revisited this part of the doc.

2023-11-21 09:56 UTC, vepadulano approved these changes
Thanks Olivier, looks good to me now!

2023-11-21 13:00 UTC, merged