Test glitches
root-project/root pull request #14112
Opened 2023-11-25 19:21 UTC by ellert

# This Pull request:

## Changes or fixes:

Fix some issues with test dound in 6.30.00

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2023-11-27 11:55 UTC, guitargeek commented on bindings/pyroot/pythonizations/test/rtensor.py
> +            ((platform.system() == "Linux") and (sys.maxsize < 2**32))) :
What if we scrap this extra check to alter the `cpptypes`, and directly define them to be what they are?

```c++
    cpptypes = ["int32_t", "int64_t", "uint32_t", "uint64_t", "float", "double"]
```
At least this is what I understand from the numpy docs:
https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int64

2023-11-27 13:01 UTC, guitargeek commented on bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py
> +        table = np.array([[1,2], [3,4]], dtype="int64")
Similar to the other test, should we maybe better use `df.Take['int64_t']` further down to be consistent with NumPy?

2023-11-27 13:10 UTC, guitargeek requested changes
Thanks @ellert. I just have some suggestions about the integer types.

2023-12-03 05:05 UTC, ellert commented on tutorials/CMakeLists.txt
> +                fit/exampleFit3D.C)
There is no request for changes here, so I will resolve this.

2024-05-20 16:01 UTC, guitargeek commented
Hi @ellert, sorry that my suggestions made things even worse and the tests don't pass anymore.

I'll revive this PR myself, updating the commits as necessary before merging and backporting.

2024-05-20 23:05 UTC, guitargeek commented on bindings/pyroot/pythonizations/test/rtensor.py
> +        "int64": "int64_t" if platform.system() != "Darwin" else "long",
I don't understand why the obvious mapping of `int64` to `int64_t` doesn't work on macOS, but on Windows and Linux it works fine.

Therefore, I'm treating macOS/Darwin as the special case now.

2024-05-20 23:06 UTC, guitargeek approved these changes
Thanks for the initiative! I'll merge this once the CI is green (the backport is also ready).

Please let us know with a GitHub issue or a new PR if there should be still failures on Linux 32 bit in your case.

2024-05-21 02:32 UTC, merged