[root-config] Fix --git-revision:
root-project/root pull request #14231
Opened 2023-12-14 11:43 UTC by Axel-Naumann

Fixes https://github.com/root-project/root/issues/14229

# This Pull request:

## Changes or fixes:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2023-12-14 12:58 UTC, pcanal commented
Do we have a test for this?

2023-12-14 21:07 UTC, ferdymercury commented
A test would be a good idea, yeah.

2023-12-14 21:10 UTC, ferdymercury requested changes
sth is still weird with the gitinfo.txt on Ubuntu22 binary release

2023-12-14 21:10 UTC, ferdymercury commented on config/root-config.in
> +         out="$out `head -n 2 \"${etcdir}/gitinfo.txt\" | tail -n 1`"
I think the space between n and the numbers is not needed, but it does not harm either.

2023-12-14 21:10 UTC, ferdymercury commented on config/root-config.in
> +         out="$out `head -n 2 \"${etcdir}/gitinfo.txt\" | tail -n 1`"
Other than that, I think there is still a problem. The etc/gitinfo.txt file for Ubuntu 22.04 binary release says:

```
tags/v6-30-02

Nov 27 2023, 19:50:38
```

so `head -n2 etc/gitinfo.txt | tail -n1`

returns an empty string.

2023-12-14 21:11 UTC, ferdymercury commented on config/root-config.in
> +         out="$out `head -n 2 \"${etcdir}/gitinfo.txt\" | tail -n 1`"
So it clearly does not match with the content of etc/gitinfo.txt that @bellenot showed in his post for Windows.

2023-12-15 15:00 UTC, ferdymercury approved these changes

2024-01-08 11:14 UTC, guitargeek commented
@phsft-bot build

2024-01-09 12:44 UTC, guitargeek commented
Thanks for the fix and the review!

2024-01-09 12:45 UTC, merged

2024-01-09 13:04 UTC, ferdymercury commented
Thanks!
Is there a GitHub issue somewhere where we could collect 'future tests' ideas, so that they do not get lost inside issues?

Like:

- https://github.com/root-project/root/pull/14231#issuecomment-1855806343 
- https://github.com/root-project/root/pull/14275#issuecomment-1864499314
- https://github.com/root-project/root/pull/13217
- https://github.com/root-project/root/issues/14085

2024-01-09 13:26 UTC, guitargeek commented
No, we don't have such an issue, but I think it's a great idea to have it. We can mark it also with the "good for new contributors" label, because writing tests is always a good way to get familiar with the codebase. Can you open such an issue, please? :pray: