Make std::string_view comparison operators constexpr
root-project/root pull request #14245
Opened 2023-12-15 12:03 UTC by bachandi

# This Pull request:

## Changes or fixes:
Makes std::string_view comparison operators constexpr to be consistent with the std defintions.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes # 14244

2023-12-15 12:35 UTC, guitargeek commented
@phsft-bot build

2023-12-18 12:22 UTC, guitargeek requested changes
Hi @bachandi, thanks for bringing this up!

We have removed our `std::string_view` backport recently. That means these comparison operators should also be removed, but apparently I forgot to do that:
https://github.com/root-project/root/pull/13993

So the right thing to do here would be to remove the whole block of `#ifndef WIN32 ... #endif`.

Can you please do that in this commit? Thanks!

2023-12-18 15:27 UTC, bachandi commented
I see. 

> Can you please do that in this commit? Thanks!
Done. Please have a look.

2023-12-18 15:48 UTC, guitargeek commented
@phsft-bot build

2023-12-18 18:26 UTC, pcanal approved these changes

2023-12-20 00:13 UTC, guitargeek approved these changes
Thanks for addressing the review comment!

2023-12-20 00:13 UTC, merged