[ntuple] Pass RClusterIndex by value
root-project/root pull request #14406
Opened 2024-01-22 17:18 UTC by hahnjo

This follows the C++ Core Guidelines item F.16, 'For "in" parameters, pass cheaply-copied types by value and others by reference to const.' `RClusterIndex` consists of two 64-bit values which for most recent platforms with 64-bit pointers is cheap to copy and better to pass in two registers instead of passing a pointer to stack memory. This in turn helps some recursive calls in RNTuple, for example `RColumn::ReadV` (at the moment of writing).

In numbers, this scores a single-digit performance improvement in the usual ATLAS analysis benchmark, -5% analysis runtime on my system. The other usual benchmarks show no changes beyond fluctuations.

This changes was prepared by running
```
 $ git grep -l "RClusterIndex &" | \
     xargs sed -i "s/const \(.*\)RClusterIndex &/\\1RClusterIndex /g"
```
then reverting the change in `RNTupleUtil.hxx` for the copy-constructor and copy-assignment operator, and finally running clang-format.

2024-01-22 17:52 UTC, vepadulano requested changes
This is a very good idea! I just found one instance that slipped from the regex

2024-01-22 17:52 UTC, vepadulano commented on tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
> +   C *MapV(const RClusterIndex clusterIndex, NTupleSize_t &nItems)
```suggestion
   template <typename C = T, std::enable_if_t<Internal::isMappable<FieldT>, C *> = nullptr>
   const C *MapV(RClusterIndex clusterIndex, NTupleSize_t &nItems)
```

2024-01-23 08:42 UTC, jblomer approved these changes

2024-01-23 10:35 UTC, vepadulano approved these changes
Very nice thanks!

2024-01-23 10:39 UTC, merged