[ntuple] Add `Internal::RSealedPageHelper`
root-project/root pull request #14403
Opened 2024-01-22 12:39 UTC by enirolf

This enables getting the unpacked and uncompressed data from a sealed page outside of the `Detail::RPageSource` class. In turn, this can be used to get the contents of an individual column.

2024-01-23 08:35 UTC, jblomer requested changes
Looks in principle good to me but I think it would be simpler to use a free function in the Internal namespace, and drop the wrapper class.

2024-01-26 14:03 UTC, vepadulano commented
> Maybe we can just make RPageSource::UnsealPage a public method?

In principle yes, I guess for now it's ok to keep it private as it's not clear (to me at least) which use cases in the open this method would cater to. So we can avoid exposing an interface that we might want to take back/change at a later stage.

2024-01-26 14:50 UTC, hahnjo commented
I'm confused, `RSealedPageHelper` already makes it `public`, just via a wrapper function, no? Sure, it's in the `Internal` namespace, but if we want it `public` I don't really see the difference to `Detail::RPageSource`...

2024-01-26 20:38 UTC, jblomer commented
Since we likely move RPageSink/Source to Internal anyway, I think it's true that making `UnsealPage` public is the easiest.

2024-02-28 10:31 UTC, enirolf commented
Yes, indeed! I will close this PR and open another one to make `UnsealPage` public.

2024-02-28 10:31 UTC, closed without merging