[tree] Change return type of TBranch::GetAddress() to `void*`
root-project/root pull request #14444
Opened 2024-01-25 18:19 UTC by guitargeek

So far, the `TBranch::GetAddress` method returned a `char *`, even though the returned address member is actually a `void *`. This causes incompatibility with PyROOT, because `char *` is automatically converted to a Python string, which is the wrong thing to for an address.

This made the return value unusable in PyROOT. That's a bug that currently prevents us from reimplementing some pythonizations in native Python.

Therefore, the return type of `TBranch::GetAddress()` was changed to `void *` in this release. Even if this change is not backwards compatible for typing reasons, the returned value is the same.

2024-01-25 19:39 UTC, pcanal commented
@smuzaffar Could you check if this break any CMSSW code?

2024-01-25 19:39 UTC, pcanal requested changes
We need at least CMS's input.

2024-01-26 08:14 UTC, smuzaffar commented
> @smuzaffar Could you check if this break any CMSSW code?

@pcanal , cmssw tests started via https://github.com/cms-sw/root/pull/197

2024-01-26 09:26 UTC, guitargeek commented
I see now that one new restrictions after this change is that you can't do pointer arithmetics without compiler warnings, which cause the tests to fail. I think this could be fixed either by casting the returned address again to `char *` at the caller site, or we add an optional `offset` parameter to `GetObject()` and `GetAddress()` so that the arithmetics can be done internally before casting to `void *`.

Furthermore, there are also alternative solutions to making the branch addresses available in PyROOT:
   * Extending the API with new methods like `GetObjectAsVoidPtr()` and `GetAddressAsVoidPtr()`
   * A Pythonization implemented as a CPython extension, to do the conversion to `void *` at a low level before cppyy converts the `char *` to a string (*not* my preferred solution because we want to move away from requiring a Python extension for PyROOT)

2024-01-26 14:47 UTC, smuzaffar commented
This looks good for cmssw. No build error found and all unit tests/relvals/addon tests passed ( https://github.com/cms-sw/root/pull/197 )

2024-01-29 09:31 UTC, vepadulano commented
> Extending the API with new methods like GetObjectAsVoidPtr() and GetAddressAsVoidPtr()

If I can cast my vote, I would prefer this option. The new API can be used by our Pythonizations everywhere. Eventual Python users that might have been bitten in the past by the type of the return value of `TBranch::GetAddress()` may be redirected to this new API. Existing code bases which might rely on the existing `char *` return type will not be influenced by the change. Although already knowing that CMSSW does not strictly rely on that is a relief :)

2024-01-29 23:06 UTC, pcanal commented
> Extending the API with new methods like GetObjectAsVoidPtr() and GetAddressAsVoidPtr()

This is probably the best albeit there is yet another alternative:
```
template <typename T = char *>
T* GetObject();
```

2024-03-16 18:29 UTC, guitargeek commented
See:
https://github.com/root-project/root/pull/14441#issuecomment-2002079910

2024-03-16 18:29 UTC, closed without merging