Implement some missing "IsInside"
root-project/root pull request #14456
Opened 2024-01-26 15:34 UTC by couet

As said in [this issue](https://github.com/root-project/root/issues/14453) TEllipse was missing the IsInside method.
Some other classes were missing it too (TCrown) or some were wrong (TDiamond). This PR implements the missing ones and fi the wrong ones.

2024-01-29 10:02 UTC, vepadulano requested changes

2024-01-29 10:02 UTC, vepadulano commented on graf2d/graf/inc/TCrown.h
> +   void    Copy(TObject &crown) const override;
Spurious extra space

2024-02-01 10:05 UTC, couet commented on tutorials/graphics/inside.C
> +TCrown   *cr;
Because they are used by the inside() and InPoint()

2024-02-04 14:03 UTC, vepadulano requested changes

2024-02-04 14:03 UTC, vepadulano commented on graf2d/graf/inc/TCrown.h
> +   void    Copy(TObject &crown) const override;
Extra whitespace

2024-02-04 14:03 UTC, vepadulano commented on graf2d/graf/inc/TCrown.h
> +   Int_t   IsInside(Double_t x, Double_t y) const;
Missing `override`?

2024-02-04 14:03 UTC, vepadulano commented on graf2d/graf/inc/TEllipse.h
> +   Int_t                IsInside(Double_t x, Double_t y) const;
Missing `override`?

2024-02-29 17:43 UTC, hansenjo commented
Hi guys,
I suggest a rewrite of the `TEllipse::IsInside` method as follows:
```
Int_t TEllipse::IsInside(Double_t x, Double_t y) const
{
  x -= fX1;
  y -= fY1;
  Double_t th = fTheta*TMath::DegToRad();
  Double_t st = TMath::Sin(th);
  Double_t ct = TMath::Cos(th);
  Double_t xx =  ct*x + st*y;
  Double_t yy = -st*x + ct*y;

  if (TMath::Abs(xx) > fR1 || TMath::Abs(yy) > fR2)
    return 0;
  Double_t xn = xx/fR1;
  Double_t yn = yy/fR2;
  if (xn*xn + yn*yn > 1.)
    return 0;
  if (fPhimax - fPhimin >= 360.)
    return 1;
  Double_t phimin = std::fmod(fPhimin, 360.);
  Double_t phimax = std::fmod(fPhimax, 360.);
  Double_t phi = TMath::RadToDeg()*(TMath::Pi() + TMath::ATan2(-yy*fR1/fR2, -xx));
  if (phi < phimin || phi > phimax)
    return 0;

  return 1;
}
```
Rationale:
- The algorithm in the PR is mathematically incorrect. For points close to the edge, it may fail to report a point as being inside. (My middle school math teacher would have failed this solution.)
- The code in the PR is inefficient: 404 calls to trig functions vs. at most 3 in the solution above.

You may want to add extra consistency checking (`fPhimin` < `fPhimax`, divisors != 0.0 etc.) in case the object was constructed with unreasonable parameters. Then again, such checks probably should go in the `TEllipse` constructor.

2024-03-27 13:18 UTC, closed without merging