[http] implement `file.root` handler
root-project/root pull request #14614
Opened 2024-02-07 10:11 UTC by linev

For any registered to http server object
now one can sumbit request like:

http://localhost:8080/hpx/file.root

THttpServer will create file in memory and store
specified object there.
Either object name will be used or "object" when
name cannot be obtained.

This PR implement new feature from #14594

2024-02-07 10:21 UTC, bellenot approved these changes

2024-02-07 10:27 UTC, vepadulano requested changes
I am sorry, I do not understand what this feature is giving us. The context from the linked issue is not enough for me to understand the use case. Maybe a test would help?

2024-02-07 11:29 UTC, linev commented
@vepadulano 

All information is in the description of the PR.
THttpServer implements different kind of http requests.
Most of them described here:

https://root.cern/root/htmldoc/guides/HttpServer/HttpServer.html#data-access-from-command-shell

This PR adds one more.

2024-02-07 14:48 UTC, vepadulano commented
So it produces a ROOT file with any type of created object in it, then a user can download it? Is it a read-only file? What can users do with it?

2024-02-07 14:56 UTC, linev commented
@vepadulano 

It is ROOT file with ROOT object.
It only can be downloaded using `wget` or any other utility.  

> Is it a read-only file?

File does not exists on the server - it is temporary TMemFile instance during http request.

> What can users do with it?

??? Open, draw histogram, analyze, ???

2024-02-19 15:42 UTC, vepadulano approved these changes
So this PR is just allowing `myobj->SaveAs("obj.root")` in the web GUI context. At least, that's what I have understood now. To be honest, it is still not very clear to me, the fact these functions are implemented in `TRootSniffer` is surprising and unclear. And the linked issue as I said does not give me enough context to understand this PR. In any case, I think I see what the changes are giving us, and I don't want to block this PR any longer

2024-02-19 15:52 UTC, linev commented
@vepadulano 

`TRootSniffer` is class which can "sniff" ROOT objects around and convert them into image/json/xml/bin/root files.
`THttpServer` uses sniffer in processing http requests via different engines.
There is special "lightweight" sniffer which used together with webgui and does not includes all extras.

I do not like to include all kind of such basic infos in each PR.

2024-02-19 15:52 UTC, merged