[PyROOT] Add tests for stl containers pythonic behaviour
root-project/root pull request #14669
Opened 2024-02-13 09:42 UTC by lobis

# This Pull request:

Closes https://github.com/root-project/root/issues/14573.

## Changes or fixes:

The pythonization of stl containers should behave in a pythonic way: empty containers should evaluate to false in an `if` statement, etc.

While working on the issue I realized this is already the case, so this PR just adds some python tests that should cover this.

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

2024-02-13 09:44 UTC, enirolf commented
@phsft-bot build

2024-02-13 17:25 UTC, hahnjo commented
@phsft-bot build

2024-02-14 08:50 UTC, lobis commented
The CI is currently failing in windows due to some underlying issue.

2024-02-14 09:18 UTC, bellenot requested changes

2024-02-14 09:18 UTC, bellenot commented on bindings/pyroot/pythonizations/test/CMakeLists.txt
> +ROOT_ADD_PYUNITTEST(pyroot_pyz_stl_set stl_set.py)
It looks like `ROOT.std.set` doesn't work on WIndows. So for the time being I propose to disable it:
```suggestion
if(NOT MSVC OR win_broken_tests)
  ROOT_ADD_PYUNITTEST(pyroot_pyz_stl_set stl_set.py)
endif()
```

2024-02-14 09:19 UTC, hahnjo commented
@phsft-bot build

2024-02-14 09:36 UTC, vepadulano approved these changes
Thank you @lobis , this looks nice! I will approve the PR, once the tests are passing one member of the ROOT team will be able to merge.

2024-02-15 11:03 UTC, vepadulano commented
Failures unrelated, merging

2024-02-15 11:03 UTC, vepadulano approved these changes
Thanks again @lobis !

2024-02-15 11:32 UTC, bellenot approved these changes

2024-02-15 12:17 UTC, merged