[DF] Update functions to use ROOT::Internal::GetDemangledTypeName
root-project/root pull request #14676
Opened 2024-02-13 13:40 UTC by maximusron

@vepadulano 

This PR departs from using RDFInternal::TypeID2TypeName and obtains the Demangled name

Fixes 
- https://github.com/root-project/root/issues/14577

### Checklist:

- [x] tested changes locally

gtest-root-dataframe-test-norootextension fails but seems like it does not have anything to do with this change.

2024-02-13 13:53 UTC, vepadulano commented
@phsft-bot build

2024-02-13 17:21 UTC, hahnjo commented
@phsft-bot build

2024-02-14 09:27 UTC, dpiparo commented
Thanks for this attempt. There are a few issues remaining and those of course will have to be understood. On top of those, I would like to ask, if possible, to check that there is no lookup triggered by the new name discovering routine: we want to avoid slowdowns+memory allocations due to unwanted accesses to the interpreter.

2024-02-14 09:46 UTC, vepadulano commented
There is a lookup eventually in `TClassEdit::GetNormalizedName`, but this is not happening in the hot loop, so I believe we can bear it.

2024-02-14 15:50 UTC, dpiparo commented
I agree. Let's have the tests fixed though before approving and merging.

2024-02-14 22:11 UTC, vepadulano requested changes

2024-02-14 22:11 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> -      if (retTypeName.empty()) {
Check should probably be reintroduced

2024-02-14 22:11 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> -      if (retTypeName.empty()) {
Check should probably be reintroduced

2024-02-24 10:32 UTC, vepadulano commented
@phsft-bot build

2024-11-30 11:51 UTC, dpiparo commented
This was a great PR. However, the understanding of the underlying issues during the year improved, making changes not necessary anymore: see https://github.com/root-project/root/issues/14577

2024-11-30 11:51 UTC, closed without merging