[rcanvas] Comment out SaveAs() in last tutorial
root-project/root pull request #14750
Opened 2024-02-16 13:22 UTC by hahnjo

This is currently the only tutorial calling `RCanvas::SaveAs()` and it fails very often (more than 90% of the time) on fedora38 and fedora39 since the last update of chromium.

2024-02-19 07:32 UTC, linev requested changes
It is not good idea to remove the only (for now) test with headless browser.
If we want to have web graphics - there should be approx 500 of such tests.
Problem is virtual machine configuration where this test should runs

2024-02-19 07:37 UTC, hahnjo commented
Hi @linev, I understand that disabling the test is not the ideal action, but this one is failing in 90% of the builds since a week and this is not acceptable. It is now also seen failing on Jenkins (https://github.com/root-project/root/pull/14755#issuecomment-1951712063) which disproves the claim that it's the machine configuration - on Jenkins, there aren't the warnings about too little space on `/tmp`. If you are unhappy about disabling this test, please investigate with critical priority how to make the test pass. If that cannot be done within a day or two, I maintain that we should disable the test and go back to a green CI state.

2024-02-20 07:15 UTC, linev commented
@hahnjo 

How can I reproduce this build:

https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/196057/consoleFull

I only see that is executed on `olbdw-01` host, but no any docker/vm configurations.

2024-02-20 07:23 UTC, hahnjo commented
> @hahnjo
> 
> How can I reproduce this build:
> 
> https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/196057/consoleFull
> 
> I only see that is executed on `olbdw-01` host, but no any docker/vm configurations.

Because that one is the "old" Jenkins, ie no container. There the old procedure applies, ie logging in via SSH. For the container based CI, there's instructions at the end of every build how to reproduce it.

2024-02-20 07:57 UTC, linev commented
I download docker for fedora39 on my machine, rebuild ROOT and do:
```
ctest -R rline
Test project /github/home/ROOT-CI/build
    Start 1109: tutorial-rcanvas-rline.cxx
1/3 Test #1109: tutorial-rcanvas-rline.cxx .........   Passed    2.40 sec
    Start 1110: tutorial-rcanvas-rline_style.cxx
2/3 Test #1110: tutorial-rcanvas-rline_style.cxx ...   Passed    1.10 sec
    Start 1111: tutorial-rcanvas-rline_width.cxx
3/3 Test #1111: tutorial-rcanvas-rline_width.cxx ...   Passed    1.11 sec

100% tests passed, 0 tests failed out of 3
```

2024-02-20 07:57 UTC, linev commented
Also simply running `rline.cxx` macro in the docker also works.

2024-02-20 08:00 UTC, hahnjo commented
Yes fine, but that doesn't change the fact that it is regularly failing in the CI environment

2024-02-20 08:01 UTC, linev commented
One should try to return back shared memory config parameters for container.

2024-02-20 08:10 UTC, hahnjo commented
We are running in circles... As Axel explained on Mattermost, they were never active. Also:

> It is now also seen failing on Jenkins ([#14755 (comment)](https://github.com/root-project/root/pull/14755#issuecomment-1951712063)) which disproves the claim that it's the machine configuration - on Jenkins, there aren't the warnings about too little space on `/tmp`.

2024-02-20 08:19 UTC, linev commented
Some resources - `/tmp`, `/home`, memory - is not sufficient for the container.
Can it be 16 parallel jobs which are used to run ctest? Can one mark some macros not to run in parallel?

2024-02-20 08:19 UTC, linev commented
> As Axel explained on Mattermost, they were never active

I was not aware about this.

2024-02-20 08:36 UTC, hahnjo commented
> Can it be 16 parallel jobs which are used to run ctest? Can one mark some macros not to run in parallel?

https://github.com/root-project/root/pull/14771; I'm not really convinced that's a solution, but worth a try...

2024-02-27 09:04 UTC, closed without merging