REve: Re-enable remote connections
root-project/root pull request #14779
Opened 2024-02-20 19:42 UTC by alja

The loopback option has been removed in January release.
The change in  #14136 allows to disable loopback in REveManager.

2024-02-20 19:42 UTC, alja commented
@linev Please check.

2024-02-21 07:30 UTC, linev requested changes
It is not a proper place to disable authentication in REve.

Only in some specific application one should do so - 
when other protection mechanism is provided.

2024-02-27 17:55 UTC, alja commented
> It is not a proper place to disable authentication in REve.
> 
> Only in some specific application one should do so - when other protection mechanism is provided.
@linev Why this is not a proper place?

2024-02-28 07:30 UTC, linev commented
> Why this is not a proper place?

Why all REve examples and demos will run by default without key authentication.
As result - anybody can try attack and hijack such server.

You should put such code in CMS demo.
And there one should use tokens, https, user authentication.

2024-02-28 18:28 UTC, alja commented
@linev I now understand that changes are not needed. I can close this PR.

In the CMS web service we used RWebWindow::SetConnToken() with auto generated key.
The connection key stayed visible in the browsers URL and multiple connections were possible.

Now if I enable (which is the default):
``
   ROOT::RWebWindowsManager::SetUseSessionKey(true);
   ROOT::Experimental::gEve->GetWebWindow()->SetRequireAuthKey(true); 
```
I see the key in printed URL in terminal, but when past it to browser the key disappears in the browser. Also multiple connections are not possible with this same key.


Now I'm confused. What is the difference between ConnToken, AutKey, and SessionKey?

One more question. Are multiple connections possible in any of the combinations?

2024-02-28 18:52 UTC, alja commented
@linev I found out by testing that multiple connections are possible if I use session key and require auth key is disabled.

2024-02-28 18:54 UTC, linev commented
> I found out by testing that multiple connections are possible if I use session key and require auth key is disabled.

Session key is useless without connection key.

2024-02-28 19:43 UTC, alja commented
No changes are needed in REve sources. I will add documentation in reve/tutorials.

2024-02-28 19:43 UTC, closed without merging