[TTaskGroup] Use global task arena
root-project/root pull request #14807
Opened 2024-02-23 13:52 UTC by hahnjo

The user expects ROOT to honor their number of threads provided as argument to `ROOT::EnableImplicitMT()`, yet facilities using `TTaskGroup` (for example RNTuple) were not using the created task arena and therefore as many resources as they could get.

This reverts commit af25fb986 ("[TTaskGroup] Isolate work with tbb::arena::isolate and not task_arena") and adds changes to use `ROOT::Internal::GetGlobalTaskArena()`.

2024-02-24 00:13 UTC, vepadulano requested changes
Changes look good thanks! Some small massaging still needed

2024-02-24 00:13 UTC, vepadulano commented on core/imt/inc/ROOT/TTaskGroup.hxx
> +#include "RTaskArena.hxx"
```suggestion
#ifdef R__USE_IMT
#include "RTaskArena.hxx"
#else
namespace ROOT::Internal{
   class RTaskArenaWrapper;
}
#endif
```

2024-02-24 00:13 UTC, vepadulano commented on core/imt/src/TTaskGroup.cxx
> +#include "ROpaqueTaskArena.hxx"
Is this include necessary?

2024-02-26 21:24 UTC, makortel commented
In CMSSW
- we use `oneapi::tbb::global_control` to set the process' maximum number of threads usable by TBB
- we create a top-level `oneapi::tbb::task_arena` (with the same number of threads), and all data processing is run within one `task_arena::execute()` call
- every call to ROOT I/O is isolated with `oneapi::tbb::this_task_arena::isolate()` call

By adding (or using) a global task arena to ROOT, does this mean, if multiple `TFile`s are writing concurrently, can their tasks be intermingled? Our guess is that ROOT's global task arena would trump the use of `this_task_arena::isolate()`, and allow such intermingling, but we don't really know.

We are concerned that by sharing one task arena for unrelated activities it would cause synchronization of those activities because of task stealing. (assuming the explicit arena would trump the `this_task_arena::isolate()` call)

2024-02-27 07:43 UTC, hahnjo commented
So naturally, this has a performance impact: Obviously using only the number of threads that the user allowed ROOT to use will only be less than the entire machine (side note: this can also be a good thing because it means less idle threads if there isn't enough work...). Additionally removing the asynchronous decompression in `RClusterPool` isn't ideal (after this, decompression only starts when the cluster is actually requested instead of when it's done pre-loading and it's blocking the "main" thread) and it negatively impacts performance, but @jblomer and me discussed and we prefer going to a correct implementation first before re-introducing other optimizations.

2024-02-27 07:48 UTC, hahnjo commented
@makortel 

> In CMSSW
> 
>     * we use `oneapi::tbb::global_control` to set the process' maximum number of threads usable by TBB
> 
>     * we create a top-level `oneapi::tbb::task_arena` (with the same number of threads), and all data processing is run within one `task_arena::execute()` call
> 
>     * every call to ROOT I/O is isolated with `oneapi::tbb::this_task_arena::isolate()` call
> 
> 
> By adding (or using) a global task arena to ROOT, does this mean, if multiple `TFile`s are writing concurrently, can their tasks be intermingled?

Yes, but I think that's already the case right now because we (incorrectly) use the surrounding task arena for everything. That said, `TTaskGroup` and the wrapped TBB's `task_group` prioritize tasks belonging to that group in their `Wait()` / `wait()` functionality.

> Our guess is that ROOT's global task arena would trump the use of `this_task_arena::isolate()`, and allow such intermingling, but we don't really know.

Possible that ROOT's task arena "wins", I don't know enough about TBB's scheduling internals; I see that you opened an issue to investigate what this means.

> We are concerned that by sharing one task arena for unrelated activities it would cause synchronization of those activities because of task stealing. (assuming the explicit arena would trump the `this_task_arena::isolate()` call)

As argued above, it's not worse than before except that this fixes the bug that ROOT must only use the resources that it was allowed by the user.

2024-02-29 08:48 UTC, hahnjo commented
I had a deeper look here, and for the read path (via `TTreeCacheUnzip::CreateTasks()`) this PR doesn't change much because the created task just launches a `TThreadExecutor` which uses ROOT's global task arena anyway.

For the writing path, `TBranch::WriteBasketImpl` will just enqueue tasks via `TBranchIMTHelper`. These will indeed now end up in the same task arena from multiple threads. @makortel did you have a chance to find out how this interacts with `this_task_arena::isolate()`? What is a path forward here that doesn't negatively impact the experiment frameworks? In general, I really want this changed because right now ROOT doesn't respect the user's resource argument passed to `EnableImplicitMT` and that's a bug.

What we could maybe offer is calling `this_task_arena::isolate()` ourselves from `TTaskGroup::ExecuteInIsolation`. This should get you the same semantics even if ROOT uses its own task arena. Actually, this is also what `TThreadExecutor` does so that may be a good idea regardless...

2024-02-29 10:54 UTC, jblomer reviewed
The RNTuple changes look good to me (one tiny suggestion).

Not sure if we reached consensus on the `TTaskGroup` changes.

2024-02-29 10:54 UTC, jblomer commented on tree/ntuple/v7/src/RClusterPool.cxx
> +         fPageSource.UnzipCluster(cptr.get());
```suggestion
         // Noop unless the page source has a task scheduler
         fPageSource.UnzipCluster(cptr.get());
```

2024-02-29 12:35 UTC, hahnjo commented
> What we could maybe offer is calling `this_task_arena::isolate()` ourselves from `TTaskGroup::ExecuteInIsolation`. This should get you the same semantics even if ROOT uses its own task arena. Actually, this is also what `TThreadExecutor` does so that may be a good idea regardless...

So this doesn't work (easily) from the ROOT side because we would need the same isolation tag when submitting tasks and when waiting for them. We could get this with an `isolated_task_group`, but this requires at least TBB 2020 and is still in preview... So I would first be very interested to hear if this change is actually expected to break isolation.

2024-02-29 17:24 UTC, Dr15Jones commented
So I've created a test program that shows that the use of another arena does cause 'cross activity' contamination. The program is

```C++
#include "oneapi/tbb/task_arena.h"
#include "oneapi/tbb/task_group.h"
#include <iostream>
#include <thread>
#include <atomic>
#include <array>

//#define OTHER                                                                                                                                                                                                                                                               
#if defined(OTHER_ISOLATE) and !defined(OTHER)
#define OTHER
#endif
namespace {
  int activity_group(int i) {
    static thread_local int v=0;
    if (i != 0) {
      v = i;
    } if ( i == 100) {
      v=0;
    }
    return v;
  }

  std::atomic<int> activityID{0};
  std::atomic<int> waitingToStart{2};

  std::array<std::atomic<bool>, 2> otherThreadStarted ={false, false};
}

int main() {
#if defined(OTHER)
  std::cout <<"built with OTHER"<<std::endl;
#endif
#if defined(OTHER_ISOLATE)
  std::cout <<"built with OTHER_ISOLATE"<<std::endl;
#endif
#if defined(NO_ISOLATE)
  std::cout <<"built with NO_ISOLATE"<<std::endl;
#endif
  oneapi::tbb::task_arena main_arena(4);

  oneapi::tbb::task_arena other_arena(4);

  oneapi::tbb::task_group other_group;
  main_arena.execute([&other_arena, &other_group]()
  {
    oneapi::tbb::task_group group;

    auto activity = [&other_arena]()
    {
      auto id = activity_group( ++activityID );
      --waitingToStart;
      while(waitingToStart.load() > 0);

#if !defined(NO_ISOLATE)
      oneapi::tbb::this_task_arena::isolate([id, &other_arena]()
#endif
      {
#if defined(OTHER)
      other_arena.execute([id]() {
#endif
#if defined(OTHER_ISOLATE)
      oneapi::tbb::this_task_arena::isolate([id](){
#endif
      oneapi::tbb::task_group group;
      for( int i = 0; i < 10; ++i) {
        group.run([id]()
        {
          auto thread_id = activity_group(0);
          if(thread_id == 0 or thread_id != id) {
            otherThreadStarted[id-1]=true;
          }
          if (thread_id != 0 and thread_id != id) {
            std::cout <<"WRONG THREAD"<<std::endl;
          }
          if (thread_id !=0 and thread_id == id) {
            std::cout <<"on starting thread"<< id <<std::endl;
            while( not otherThreadStarted[id-1]);
            return;
          }
          using namespace std::chrono_literals;
          std::cout <<"start sleep "<<id<< std::endl;
          std::this_thread::sleep_for(3000ms);
          std::cout <<"end sleep"<<std::endl;
        });
      }
      group.wait();
#if defined(OTHER_ISOLATE)
      });
#endif
#if defined(OTHER)
      });
#endif
      }
#if !defined(NO_ISOLATE)
      );
#endif
      activity_group(100);
    };

    group.run(activity);
    group.run(activity);
    group.wait();

  });
  std::cout <<"main_arena execute finished"<<std::endl;
  other_group.wait();
  return 0;
}
```

This 'simulates' the CMSSW framework running to ROOT output modules concurrently (represented by the `group.run(activity)` calls ). Within each of those 'modules' 10 new identical TBB tasks are launched and the waited upon. If a task from one 'module' ever is run on the thread of the other module (i.e. the thread doing the `group.wait()`) the program prints "WRONG THREAD".

The program can be built with the options to
- Turn off task_arena isolation (-DNO_ISOLATE) at the 'module' level (this would represent removing such isolate calls in CMSSW)
- Add another task arena (-DOTHER) which represents the global ROOT arena.
- Add task_arena isolate within the other arena (-DOTHER_ISOLATE) which would represent what would happen if ROOT internally called isolate within your own arena.

The results are
- with only -DNO_ISOLATE see 'WRONG THREAD' message every time the program is run. This shows why CMS added the isolate
- with no other option, 'WRONG THREAD' is never seen
- with -DOTHER, see 'WRONG THREAD' every time >>> this is the case for what this PR does
- with -DOTHER_ISOLATE never see 'WRONG THREAD'

2024-02-29 20:18 UTC, hahnjo commented
Thanks @Dr15Jones for the nice reproducer! It confirms that this is a problem we need to handle, and that `tbb::isolated_task_group` is a solution (isolating into the IMT task arena will be quite hard for every ROOT API that might make use of IMT). As far as I can tell, CMSSW uses oneTBB 2021 so the latest commit should give us a path forward.

2024-03-01 07:40 UTC, hahnjo commented
So this seems to work. We may require TBB 2020 as a minimum in a second stage (https://github.com/root-project/root/pull/14862), but for now the isolation guarantees are conditional on the TBB version used for building ROOT.

2024-03-05 11:51 UTC, dpiparo approved these changes
thanks for this useful upgrade.

2024-03-11 18:32 UTC, merged