Relaxed rvec utils
root-project/root pull request #15101
Opened 2024-04-02 07:59 UTC by tmadlener

# This Pull request:

Makes it possible to call `VecOps::DeltaPhi`, `VecOps::DeltaR`, `VecOps::DeltaR2`, `VecOps::InvariantMass` and `VecOps::InvariantMasses` with different floating point types.

## Changes or fixes:

Previously all arguments where deduced to be the same types which does not allow to call these with mixed floating point type arguments. Now each argument get's its own template type, making it possible to call them with mixed floating point types. The return type and any intermediate calculations will be done by the largest necessary floating point type, as determined via `std::common_type`.

I tried to follow existing conventions, e.g. using `Common_t` as an additional defaulted template argument for a bit less typing in the implementations. This also requires at least c++14 as it uses the `common_type_t` helper type for a bit less typing.

Some of the functions now are quite heavily templated, I am not entirely sure the full combinatorial explosion is necessary for all of them.

I haven't added tests yet. There are some pre-existing where I could "attach" them. I could also just stick a bunch of `static_assert`s for the return types etc into the implementation directly if you prefer that.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #15077

2024-04-02 08:49 UTC, dpiparo commented
Hi @tmadlener , thanks for this PR. Could you please add coverage for this feature by extending the existing RVec tests? If that makes sense for you, once this is done, I will launch the builds for testing the new code.

2024-04-02 11:43 UTC, tmadlener commented
I have added a few tests that check he expected return types. They also give some information about the accuracy compared to a calculation done with all doubles, since there will always be some floating point promotion somewhere in mixed cases.

2024-04-02 12:48 UTC, dpiparo requested changes
Very good coverage. Thanks for adding it. I propose to apply a minimal change, to replace the static_asserts with gtest standard macros in order to make the code uniform. 
After that, we are ready to test.

2024-04-02 12:48 UTC, dpiparo commented on math/vecops/test/vecops_rvec.cxx
> +   static_assert(std::is_same_v<decltype(DeltaPhi(0.f, 0.0)), double>,
Could you use the gtest macro EXPECT_TRUE to uniform this smart check to the rest of the code?
For example
```cpp
EXPECT_TRUE(std::is_same_v<decltype(DeltaPhi(0.f, 0.0)), double>) << "DeltaPhi should return double if one of the arguments is double";
```
This applies to other places in the code.

2024-04-03 05:18 UTC, dpiparo commented
Hi,

The changes are properly picked up, but two tutorials now fail because the number of template arguments changed. Could you fix them?
```
tutorial-dataframe-df102_NanoAODDimuonAnalysis
tutorial-v7-ntuple-ntpl004_dimuon
```
Thanks!

2024-04-03 08:38 UTC, tmadlener commented
Ah, I didn't have the patience to run all the tests locally so I missed those. I have update the definitions of the template functions to only have one non-defaulted template argument. This should make for a truly transparent change. On the other hand in deduced contexts it should now be possible to have different floating point types.

Maybe there should be an actual test that checks that when invoked from an RDataFrame from python. I could not find an immediate best place for that, but maybe you have one in mind?

2024-04-03 19:43 UTC, merged