Add the objects from the list of functions in the Legend.
root-project/root pull request #15179
Opened 2024-04-09 13:19 UTC by couet

Add the objects from the list of functions as suggested here:
https://root-forum.cern.ch/t/multigraph-fit-not-showing-in-the-legend/58876

2024-04-15 12:01 UTC, linev requested changes

2024-04-16 13:07 UTC, couet commented on graf2d/gpad/src/TPad.cxx
> +   auto AddEntryFromListOfFunctions = [&]() {
but in that case `mes` and `leg` need also to be added as parameters. Why only `lof` ?

2024-04-16 13:28 UTC, linev commented on graf2d/gpad/src/TPad.cxx
> +   auto AddEntryFromListOfFunctions = [&]() {
> Why only lof?

While lamda called `AddEntryFromListOfFunctions` - logically one provides list as argument to it. 
`mes` is just string and not a parameter. 
`leg` can be add as second argument - why not.

2024-04-16 14:03 UTC, couet commented on graf2d/gpad/src/TPad.cxx
> +   auto AddEntryFromListOfFunctions = [&]() {
`mes` is also used externally, so it is also a parameter in that sense. I found simpler to simply put `[&]` to share the variables.

2024-04-16 14:30 UTC, linev approved these changes

2024-04-17 07:53 UTC, merged