[df] Add ChangeEntryRange
root-project/root pull request #15182
Opened 2024-04-09 14:30 UTC by kristupaspranc

2024-04-09 15:04 UTC, vepadulano requested changes

2024-04-09 15:04 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +void ChangeEntryRange(const RNode &node, const ULong64_t start, const ULong64_t end);
I would name this function (and the related one in RLoopManager) `ChangeBeginAndEndEntries` to be more specific of the different use case involved here. At some point we will need to decide how to provide a more coherent API for all the similar use cases

2024-04-09 16:34 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +void ChangeBeginAndEndEntries(const RNode &node, ULong64_t start, ULong64_t end);
The data members are `fBeginEntry` and `fEndEntry` so let's change the name of the function parameter for symmetry
```suggestion
void ChangeBeginAndEndEntries(const RNode &node, ULong64_t begin, ULong64_t end);
```

2024-04-25 08:28 UTC, kristupaspranc commented
Made the requested changes, added a test.
This function has nothing to do with `Foreach` as previously reported.
It only works with dataframes that are made out of `TTree` or `TChain` as intended, thus, it does not with a dataframe that is `Cache`d.

2024-11-30 14:01 UTC, vepadulano commented
Changes are implemented in master

2024-11-30 14:01 UTC, closed without merging