[tree] Warn about too long TTreeFormula and double limit
root-project/root pull request #15274
Opened 2024-04-19 10:02 UTC by ferdymercury

# This Pull request:

## Changes or fixes:

Fixes https://its.cern.ch/jira/browse/ROOT-8256

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2024-04-25 06:33 UTC, dpiparo commented
restarted the builds since they were red for other reasons.

2024-04-25 19:47 UTC, pcanal commented on tree/treeplayer/src/TTreeFormula.cxx
> +            "Length of leafname (%d) exceeds maximum allowed by the buffer (%d), output will be truncated.",
```suggestion
            "Length of leafname (%d) exceeds maximum allowed by the buffer (%d), formula will be truncated.",
```

2024-04-25 19:49 UTC, pcanal commented on tree/treeplayer/src/TTreeFormula.cxx
> +   }
There is no point is going on since the formula was truncated, we should return an error here.

2024-04-25 19:49 UTC, pcanal requested changes
See comments

2024-04-25 21:25 UTC, pcanal approved these changes
Thanks.

2024-04-25 22:59 UTC, merged

2024-04-26 06:06 UTC, ferdymercury commented
Thanks!! Gentle reminder to close associated JIRA issue