[TreeReader] Add value printers for TTreeReaderArray/Value
root-project/root pull request #15317
Opened 2024-04-23 13:33 UTC by dpiparo

Fixes ROOT-11006

2024-04-23 14:36 UTC, ferdymercury requested changes
Thanks for this!

I would also suggest adding security in this public method to prevent the crash on line 35 (stack trace by @amadio on Jira):

`return fImpl->GetSize(GetProxy());`
--> change to
`return fImpl ? fImpl->GetSize(GetProxy()) : 0;`

in analogy with what's done in the function GetReadStatus

2024-04-23 19:18 UTC, dpiparo commented
Yes, but in another PR, ok?

2024-04-23 20:50 UTC, ferdymercury approved these changes

2024-04-24 18:46 UTC, merged

2024-04-27 13:54 UTC, ferdymercury commented
See also https://its.cern.ch/jira/browse/ROOT-9181