Builtin CFITSIO: 3.45 -> 4.4.0
root-project/root pull request #15508
Opened 2024-05-14 14:10 UTC by guitargeek

This avoids the indirect dependence of ROOT on CURL, because the CURL dependence of CFITSIO is optional since version 3.49: https://github.com/HEASARC/cfitsio/blob/f220e6e2c570f19228609ee081f735df0ddb204b/docs/changes.txt#L199

2024-05-14 15:36 UTC, pcanal approved these changes
LGTM.  Thanks.

2024-05-14 19:16 UTC, pcanal requested changes
The incremental build might need a refresh to properly see the new cftios header files.

2024-05-14 22:55 UTC, guitargeek commented
> The incremental build might need a refresh to properly see the new cftios header files.

Good point! I asked the CI to do a clean build, and now it worked!

2024-05-14 22:55 UTC, guitargeek commented
Argh, clicked the wrong button again. Please GitHub, increase the space between "Close with comment" and "Comment" :laughing:

2024-05-15 07:58 UTC, couet approved these changes

2024-05-15 10:43 UTC, bellenot requested changes
The build type is missing for Windows, then the default will be used, and that might break the debug builds (`CMAKE_BUILD_TYPE` is not used on Windows).
I.e. This check is missing:
```
if(WIN32)
  if(winrtdebug)
    set(cfitsiobuild "Debug")
  else()
    set(cfitsiobuild "Release")
  endif()
endif()

```
and then the build command (for Windows only I think):
```
        BUILD_COMMAND ${CMAKE_COMMAND} --build . --config ${cfitsiobuild}
```

2024-05-15 10:54 UTC, guitargeek commented
Doesn't have setting the build type the same effect, which is what I do right now?
```
  CMAKE_ARGS -G ${CMAKE_GENERATOR}
             -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
```
I wonder if we can make the code more platform in-depended like this

2024-05-15 10:56 UTC, guitargeek commented
@bellenot, the zlib problem is fixed now also on Windows, but there are sill build errors related to something else:
```
      (compiling source file '../BUILTIN_CFITSIO/eval_y.c')
      
  C:\ROOT-CI\build\CFITSIO-prefix\src\BUILTIN_CFITSIO\cfortran.h(280,1): error C1189: #error:  "cfortran.h:  Can't find your environment among:    - GNU gcc (g77) on Linux.                                                - MIPS cc and f77 2.0. (e.g. Silicon Graphics, DECstations, ...)         - IBM AIX XL C and FORTRAN Compiler/6000 Version 01.01.0000.0000         - VAX   VMS CC 3.1 and FORTRAN 5.4.                                      - Alpha VMS DEC C 1.3 and DEC FORTRAN 6.0.                               - Alpha OSF DEC C and DEC Fortran for OSF/1 AXP Version 1.2              - Apollo DomainOS 10.2 (sys5.3) with f77 10.7 and cc 6.7.                - CRAY                                                                   - NEC SX-4 SUPER-UX                                                      - CONVEX                                                                 - Sun                                                                    - PowerStation Fortran with Visual C++                                   - HP9000s300/s700/s800 Latest test with: HP-UX A.08.07 A 9000/730        - LynxOS: cc or gcc with f2c.                                            - VAXUltrix: vcc,cc or gcc with f2c. gcc or cc with f77.                 -            f77 with vcc works; but missing link magic for f77 I/O.     -            NO fort. None of gcc, cc or vcc generate required names.    - f2c/g77:   Use #define    f2cFortran, or cc -Df2cFortran               - gfortran:  Use #define    gFortran,   or cc -DgFortran                              (also necessary for g77 with -fno-f2c option)               - NAG f90: Use #define NAGf90Fortran, or cc -DNAGf90Fortran              - Absoft UNIX F77: Use #define AbsoftUNIXFortran or cc -DAbsoftUNIXFortran     - Absoft Pro Fortran: Use #define AbsoftProFortran     - Portland Group Fortran: Use #define pgiFortran     - Intel Fortran: Use #define INTEL_COMPILER" [C:\ROOT-CI\build\CFITSIO-prefix\src\BUILTIN_CFITSIO-build\cfitsio.vcxproj] [C:\ROOT-CI\build\builtins\cfitsio\BUILTIN_CFITSIO.vcxproj]
      (compiling source file '../BUILTIN_CFITSIO/f77_wrap1.c')
```
This PR has been much less trivial than I thought :laughing:

2024-05-15 11:00 UTC, bellenot commented
@guitargeek there is no fortran compiler on Windows

2024-05-15 11:01 UTC, bellenot commented
> Doesn't have setting the build type the same effect, which is what I do right now?
> 
> ```
>   CMAKE_ARGS -G ${CMAKE_GENERATOR}
>              -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
> ```
> 
> I wonder if we can make the code more platform in-depended like this

As I said, `CMAKE_BUILD_TYPE` is meaningless on Windows

2024-05-15 11:03 UTC, bellenot commented
And BTW, I'm working on removing the custom `winrtdebug` flag, but too busy with many other tasks. And then all the Debug builds will fail.

2024-05-15 11:31 UTC, bellenot requested changes

2024-05-15 11:31 UTC, bellenot commented on builtins/cfitsio/CMakeLists.txt
> +  BUILD_COMMAND ${CMAKE_COMMAND} --build ${CFITSIO_BUILD_COMMAND_FLAGS} .
```suggestion
  BUILD_COMMAND ${CMAKE_COMMAND} --build . ${CFITSIO_BUILD_COMMAND_FLAGS}
```

2024-05-15 11:57 UTC, guitargeek commented
I'm making another attempt, just not compiling the fortran wrapper because we don't need it

2024-05-15 13:22 UTC, bellenot approved these changes
Thanks Jonas!

2024-05-15 14:06 UTC, merged