[ntuple] Add `kUnknownCompressionSettings`
root-project/root pull request #15698
Opened 2024-05-31 15:01 UTC by enirolf

Currently, the default compression setting for a column range is `0`, which is an actual, valid compression setting (i.e., no compression has been applied). We should distinguish between "no compression has been applied" and "we don't know the compression" (for example in the case of columns created through late model extension, where some ranges may not come from a physical storage location).

2024-06-02 13:00 UTC, jblomer requested changes
If possible, I think we should add a test where the inspector opens an ntuple with deferred columns in the second cluster.

2024-06-03 06:51 UTC, enirolf commented
> If possible, I think we should add a test where the inspector opens an ntuple with deferred columns in the second cluster.

Yes, my plan was to address the inspector (+ tests) in a separate PR!

2024-06-03 09:41 UTC, silverweed commented on tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
> +constexpr CompressionSettings_t kUnknownCompressionSettings(std::int32_t(-1));
Related to this: #15714

2024-06-03 09:41 UTC, silverweed commented
Should we add this value to `RCompressionSetting::EDefaults` ?

2024-06-05 07:21 UTC, jblomer approved these changes

2024-06-05 07:32 UTC, merged