[WIP][DF] Add snapshotting to RNTuple
root-project/root pull request #15750
Opened 2024-06-04 16:38 UTC by enirolf

# This Pull request:

## Changes or fixes:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2024-09-03 08:00 UTC, vepadulano requested changes
Thank you so much for this effort! It will be a great addition to RDF's capabilities.

2024-09-03 08:00 UTC, vepadulano commented on tree/dataframe/test/dataframe_snapshot_ntuple.cxx
> +TEST_F(RDFSnapshotRNTupleTest, ComplexFields)
These tests with complex fields are very nice to have! Can we also include checks for the actual values in the output RNTuple?

2024-09-06 12:16 UTC, hahnjo commented
Can you expand on why we cannot snapshot from TTree to RNTuple? In general, I'm not sure if it's a good idea to change the default behavior depending on the type of the datasource. Ideally, `kDefault` would for now always mean `kTTree` but be kind of deprecated from the beginning to get users to choose which snapshot format they want. Then at a later point, we could remove it entirely and force users to choose the wanted format, to eventually re-introduce `kDefault` in ROOT7 to mean `kRNTuple`...

2025-01-08 10:37 UTC, hahnjo commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +      fLoopManager->SetDataSource(std::make_unique<ROOT::Experimental::RNTupleDS>(fNTupleName, fFileName));
I know it's been a while, but why are we replacing the data source? I don't see this done for the existing `SnapshotTTreeHelper`, but maybe it is hidden somewhere because of how TTree is special in RDF...

I'm asking because I guess this one / the reason for the compatibility matrix in the PR summary. Also I'm not sure if this change of the data source is actually sound, I think with some `Redefine`s I can construct cases where filters are not idempotent and thus a snapshot + replacing the data source might change results.

2025-01-08 13:45 UTC, hahnjo commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +      fLoopManager->SetDataSource(std::make_unique<ROOT::Experimental::RNTupleDS>(fNTupleName, fFileName));
To answer myself: `Snapshot` directly calls `CreateLMFromTTree` with a non-existing file name that is then later written to during the action. See also Vincenzo's comment https://github.com/root-project/root/pull/15750/files#r1741566386

2025-01-08 13:57 UTC, pcanal commented on tree/dataframe/src/RDFActionHelpers.cxx
> +         outFile->Delete(ntupleName.c_str());
I think here and other `outFile->Delete` calls you might mean:
```suggestion
         outFile->Delete((ntupleName + ";*").c_str());
```
otherwise the `TTree` case is the only one deleting older cycles.

2025-01-08 13:59 UTC, pcanal commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
Do we intentionally not support storing the snapshot into a sub-directory?

2025-01-08 14:00 UTC, pcanal commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +void ValidateSnapshotRNTupleOutput(const RSnapshotOptions &opts, const std::string &ntupleName,
The function is missing a doc string and the name seems at odd with the functionality.  Most often a `validate` routine would return a 'bool' and leave its input unchanged (eg. `IsValid`)

2025-02-14 16:50 UTC, enirolf commented
> Can you expand on why we cannot snapshot from TTree to RNTuple? In general, I'm not sure if it's a good idea to change the default behavior depending on the type of the datasource. Ideally, `kDefault` would for now always mean `kTTree` but be kind of deprecated from the beginning to get users to choose which snapshot format they want. Then at a later point, we could remove it entirely and force users to choose the wanted format, to eventually re-introduce `kDefault` in ROOT7 to mean `kRNTuple`...

Snapshotting from TTree to RNTuple will require the same (non-trivial) machinery as the `RNTupleImporter` to properly handle all branch types. The intent is absolutely to enable this, but I believe it's out of scope for this particular PR.

To me it makes most sense to, as a default, have the snapshot output format match the input format, but I think it's good to collect opinions on this.

2025-02-14 17:10 UTC, vepadulano requested changes
Thanks for the updates! Some minor comments before a more thorough review

2025-02-14 17:10 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +         auto newRDF = std::make_shared<RInterface<RLoopManager>>(std::make_shared<RLoopManager>(0));
Comment for posterity. I believe the change is the best we can do with the current RLoopManager implementation. In general, I think we should introduce a default constructor to RLoopManager leaving it in a valid but unusable state. This method could then use that constructor instead of abusing of the empty data source constructor. Out of scope for this PR.

2025-02-14 17:10 UTC, vepadulano commented on tree/dataframe/src/RDFActionHelpers.cxx
> +   std::unique_ptr<TFile> outFile{TFile::Open(fileName.c_str(), "update")};
Fair enough 👍

2025-02-14 17:10 UTC, vepadulano commented on tree/dataframe/test/dataframe_snapshot_ntuple.cxx
> +   EXPECT_TRUE(gSystem->AccessPathName(fileGuard.GetPath().c_str()));
This might have got lost https://github.com/root-project/root/pull/15750#discussion_r1741596237

2025-02-17 14:07 UTC, enirolf commented on tree/dataframe/test/dataframe_snapshot_ntuple.cxx
> +   expected = {"jets_electrons", "jets_electrons.pt"};
It is when they are subfields that are not snapshotted as top-level fields! In this case, we snapshot `jets.electrons`, which will become a top-level field so it has to be saved as `jets_electrons`. However, it still has a subfield `pt` that are also included in the snapshot, which we can access as any other ordinary subfield (with the `"."`).

2025-02-24 10:33 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
It is supported for TTree, probably we should try to have at least some support for RNTuple (tests can be added in a follow-up PR too)

2025-02-24 10:35 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
> +                               "components enabled.");
We usually/try to prefix error messages in  RDF with `RDataFrame:`.

2025-02-24 10:49 UTC, vepadulano commented on tree/dataframe/test/dataframe_snapshot_ntuple.cxx
> +                              [](ROOT::RVec<ROOT::RVec<float>> nnlo) {
```suggestion
                              [](const ROOT::RVec<ROOT::RVec<float>> &nnlo) {
```

Just to speedup the test a bit, avoids extra copy

2025-02-24 10:51 UTC, vepadulano commented on tree/dataframe/test/dataframe_snapshot_ntuple.cxx
> +   expected = {"jets_electrons", "jets_electrons.pt"};
Ah, yes! Sorry I didn't catch this back when I commented! It's a very neat feature!

2025-02-24 16:58 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
The problem is that the current RNTuple interfaces barely support it. `RNTupleWriter::Append` does take TDirectory as its argument, but there is no interface to create an `RPageSource` for an RNTuple that's stored in a subdirectory. So I think this requires more thought outside of this PR. However, to make the user experience a bit friendlier, I will add a check and throw in case one attemps to snapshot to a subdirectory.

2025-02-26 15:46 UTC, pcanal commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
Where did the throw ended up?

2025-02-26 15:48 UTC, pcanal commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +void ValidateSnapshotRNTupleOutput(const RSnapshotOptions &opts, const std::string &ntupleName,
Was this addressed?

2025-02-26 16:02 UTC, enirolf commented on tree/dataframe/src/RDFActionHelpers.cxx
> +         outFile->Delete(ntupleName.c_str());
It has been changed to:

https://github.com/enirolf/root/blob/bf7088ea7bc4a25d41c36dec2e13280c3cda61e2/tree/dataframe/src/RDFActionHelpers.cxx#L282-L287

2025-02-26 16:02 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
I've added it in `RInterface.hxx`:

https://github.com/enirolf/root/blob/bf7088ea7bc4a25d41c36dec2e13280c3cda61e2/tree/dataframe/inc/ROOT/RDF/RInterface.hxx#L1357-L1360

and

https://github.com/enirolf/root/blob/bf7088ea7bc4a25d41c36dec2e13280c3cda61e2/tree/dataframe/inc/ROOT/RDF/RInterface.hxx#L3253-L3256

2025-02-26 16:02 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +void ValidateSnapshotRNTupleOutput(const RSnapshotOptions &opts, const std::string &ntupleName,
Yes, in [this commit](https://github.com/enirolf/root/commit/1d1aa6b66583bfd68509fe05c475f1e85539136b)

2025-02-27 07:24 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
> +                               "components enabled.");
Changed here and everywhere else :+1:

2025-02-27 14:16 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
> +      // TODO(fdegeus) Add MT snapshotting
Do we want to just throw an exception for now informing the user that Snapshot to RNTuple with IMT enabled is not supported?

2025-02-28 16:34 UTC, hahnjo reviewed
Looks good from what I can tell, but definitely no expert.

One more consideration for `kDefault`: I understand it can be expected that snapshotting RNTuple results in RNTuple, on the other hand it's surprising that RDF changes behavior when changing the input. Also given that IMT snapshotting doesn't work yet and to preserve today's working behavior, `kDefault` could (in the beginning) always snapshot to TTree. Then at some point, defaults could be switched...

2025-02-28 16:34 UTC, hahnjo commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
> there is no interface to create an `RPageSource` for an RNTuple that's stored in a subdirectory

Is that still the case? If you have an anchor it will natively work, and `RMiniFileReader::GetNTupleProper` parses forward slashes in the `ntuplePath` to mean that it should look in a sub-directory. Not necessarily required in this PR, just trying to understand what is actually needed.

2025-02-28 16:34 UTC, hahnjo commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   entry->BindValue(fieldName, std::make_shared<T>(value));
Note that I think this copies all values, including vectors and other "complex" containers. Would it be possible to `BindRawPtr`? I think `SetFields` gets non-`const` references, so that should not get into our way...

2025-02-28 16:34 UTC, hahnjo commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +      ROOT::Experimental::RNTupleWriteOptions writeOptions;
This should adapt to `ROOT::RNTupleWriteOptions` before merging (I think the deprecation warning is causing some test failures)

2025-02-28 16:34 UTC, hahnjo commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +
See my other comment; I believe this may just work (with `TFile` and `RNTupleWriter::Apend`)

2025-03-03 07:41 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   SnapshotRNTupleHelper(std::string_view filename, std::string_view ntuplename, const ColumnNames_t &vfnames,
That would be an option indeed, we could incorporate it into `RNTupleDS` first and then (re-)add the support here.

2025-03-03 07:44 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +
Writing works, indeed. But there's no non-power user way currently to read these files back, so until there is I would prefer to disallow it.

2025-03-03 09:37 UTC, vepadulano commented
>  I understand it can be expected that snapshotting RNTuple results in RNTuple, on the other hand it's surprising that RDF changes behavior when changing the input.

I believe this ultimately comes down to user preference/mental reasoning, we won't be able to make everyone happy. Also note that this approach will eventually lead to the need for breaking changes, although we could mitigate it by postponing to ROOT7 where breaking changes can be expected and properly communicated. All in all, we can decide to adopt the more conservative strategy at this moment

2025-03-03 10:15 UTC, enirolf commented
> I understand it can be expected that snapshotting RNTuple results in RNTuple, on the other hand it's surprising that RDF changes behavior when changing the input. Also given that IMT snapshotting doesn't work yet and to preserve today's working behavior, `kDefault` could (in the beginning) always snapshot to TTree. Then at some point, defaults could be switched...

Alright, I think this makes sense for now. The latest commit changes the default to TTree in all cases. When a user tries to snapshot from RNTuple with the default option, a warning is raised to let them know that the output format will be TTree, to prevent potential downstream code breakages when they actually expected the output to be RNTuple as well.

2025-03-03 10:19 UTC, enirolf commented on tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
> +   entry->BindValue(fieldName, std::make_shared<T>(value));
Added here:

https://github.com/root-project/root/blob/a3dbe5b83b31d449d8812ca29762a6cd3c43c298/tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx#L1893-L1898

2025-03-03 12:20 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +                    "want to Snapshot to RNTuple, set the appropriate fDataFormat option in RSnapshotOptions. Note "
Sorry for my oversight, the data member is called fOutputFormat and not fDataFormat

```suggestion
                    "want to Snapshot to RNTuple, set the appropriate fOutputFormat option in RSnapshotOptions. Note "
```

2025-03-03 19:51 UTC, pcanal commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +            Warning("Snapshot",
How does a user that is happy with the default (wants TTree) disable this warning?

2025-03-03 19:55 UTC, pcanal commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +                    "want to Snapshot to RNTuple, set the appropriate fOutputFormat option in RSnapshotOptions. Note "
```suggestion
                    "want to Snapshot to RNTuple or to suppress this warning, set the appropriate fOutputFormat option in RSnapshotOptions. Note "
```

2025-03-03 20:06 UTC, vepadulano commented on tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> +            Warning("Snapshot",
`fOutputFormat = kTTree` (modulo proper qualifying tokens)

2025-03-04 09:34 UTC, merged