Update build guide for cling
root-project/root pull request #15972
Opened 2024-07-02 14:28 UTC by LiAuTraver

# This Pull request:
I'm not sure if it's just me, but after spending an entire day building Cling, CMake kept notifying me that the target `nvptx` was not found.  It's really confused someone who has little experience with CMake like me. Then I searched the LLVM repository and found that the target name was capitalized as `NVPTX`. If it's not just me, then there's an issue with the build guide. 

## Changes or fixes:
Simply changed `nvptx` to `NVPTX`. Plus, CMake requires to pass `-DCMAKE_BUILT_TYPE` explicitly and I add it as well.
## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

2024-07-02 15:32 UTC, vgvassilev approved these changes
Lgtm!

2024-07-02 15:41 UTC, ferdymercury commented
@LiAuTraver
Thanks for this!

Could you also fix the couple of things that were proposed in this PR?

2024-07-02 15:58 UTC, ferdymercury requested changes
Thanks a lot! Please also include the mini-change from https://github.com/root-project/cling/pull/304/files

2024-07-02 16:03 UTC, ferdymercury approved these changes

2024-07-02 16:05 UTC, LiAuTraver commented
Sure, I'd like to help :) 
*(my fault to mistakenly created an unnecessary extra commit, sorry)*

2024-07-11 06:23 UTC, hahnjo commented
@vgvassilev @ferdymercury can we merge this?

2024-07-11 06:29 UTC, vgvassilev commented
Yes, let's do it.

2024-07-11 06:30 UTC, merged

2025-02-08 09:19 UTC, sparrowyang commented
it not run successfully in windows