[ntuple] Add `RNTupleModel` argument to `RNTupleProcessor` constructor
root-project/root pull request #15985
Opened 2024-07-04 12:56 UTC by enirolf

This PR adds the possibility to specify which fields should be read by the `RNTupleProcessor` by passing an `RNTupleModel` to its constructor. The processor will create and own an `REntry` based on this, but it will use the pointers from the model's default entry to hold the field values during iteration. This way, the pointers returned by `RNTupleModel::MakeField` can be used in the processor iteration to access the values being read.

Passing a model is optional; if not provided, one will be created from the descriptor of the first specified RNTuple.

A follow-up PR will add the possibility to change the model after the processor has been created (useful when the set of fields to read cannot be decided at compile-time).

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

2024-07-05 08:55 UTC, jblomer requested changes
In principle looks good to me, just one issue on handling bare models.

2024-07-05 08:55 UTC, jblomer commented on tree/ntuple/v7/src/RNTupleProcessor.cxx
> +   for (const auto &value : model->GetDefaultEntry()) {
We should handle the case when the provided model is a "bare model".

2024-07-07 20:47 UTC, vepadulano approved these changes
Nice improvement thanks!

2024-07-08 16:02 UTC, jblomer approved these changes

2024-07-08 16:04 UTC, merged