[ntuple] Add support for reconstructing projected fields
root-project/root pull request #16006
Opened 2024-07-09 12:05 UTC by jblomer

Projected fields, so far, were read back as plain fields. This is useful for typical reading use cases. When we want to merge, e.g., it is more useful however to reconstruct the model exactly as it was written, including the projected fields.

For this to work, the field mappings need to be written to disk (forward incompatible change). While projected fields use alias columns, not all fields have an attached column. So from the column relationship it is in general not possible to reconstruct the field relationship described by projected fields.

Note that we still don't support models with projected fields in the RNTuple reader. The reason is the mismatch between RNTupleReader and RNTupleWriter: the RNTupleWriter effectively writes all the fields, projected or not. The RNTupleReader, however, would only read back non-projected fields.

2024-07-09 13:02 UTC, silverweed requested changes

2024-07-09 14:43 UTC, jblomer commented on tree/ntuple/v7/doc/specifications.md
> +If `flag=0x01` (_repetitive field_) is set, the field represents a fixed-size array.
Used `==` for the time being

2024-07-10 06:51 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
> +      RResult<void> AddProjectedField(std::unique_ptr<RFieldBase> field, FieldMappingFunc_t mapping);
I may be mistaken here but being a public interface on a non-performance-critical path, I think we benefit from the added flexibility of `std::function`. For instance, in `RNTupleModel::CreateModel` we use more than a function pointer when we pass a lambda that binds the `this` pointer.

I guess the template argument would work, but it also seems to complicate the code more than perhaps necessary.

2024-07-15 10:06 UTC, silverweed approved these changes

2024-07-16 06:38 UTC, merged