[skip-ci][Core] Update TMethodCall documentation
root-project/root pull request #16026
Opened 2024-07-13 05:45 UTC by dpiparo

fixes ROOT-6968

2024-07-13 09:02 UTC, ferdymercury requested changes
Thanks, LGTM.

Please consider also fixing the typos on line 549 ("actual" is missing last char, and the closing parenthesis is missing).

2024-07-13 09:02 UTC, ferdymercury commented on core/meta/src/TMethodCall.cxx
>  /// ParamArr is an array containing the function argument values.
```suggestion
/// \brief Set pointers to parameters
/// \param paramArr an array containing the function argument values.
```

2024-07-13 09:02 UTC, ferdymercury commented on core/meta/src/TMethodCall.cxx
> +/// Nargs-NargsOpt <= nparam <= Nargs, where
```suggestion
/// \param nparam number of parameters should fulfill Nargs-NargsOpt <= nparam <= Nargs, where
```

2024-07-18 09:42 UTC, dpiparo commented
All implemented. Thanks a lot.

2024-07-18 09:42 UTC, merged