[DF] Remove extern template function declarations
root-project/root pull request #16176
Opened 2024-08-06 13:06 UTC by hahnjo

Clang 18 changed the name mangling of function templates, see https://releases.llvm.org/18.1.0/tools/clang/docs/ReleaseNotes.html#c-specific-potentially-breaking-changes

The first mentioned case is "When a template parameter in a function template depends on a previous template parameter", for example:
```
struct A {
    template <typename T, std::enable_if_t<std::is_integral_v<T>, int> = 0>
    void Member(T p) {}
};

template void A::Member(int);
```

With Clang < 18 and current versions of GCC, this will mangle to `_ZN1A6MemberIiLi0EEEvT_`, but Clang 18 and later will mangle it to `_ZN1A6MemberIiTnNSt9enable_ifIXsr3stdE13is_integral_vIT_EEiE4typeELi0EEEvS2_` (unless reverted for compatibility with `-fclang-abi-compat=17`).

For ROOT's use of Cling, this poses a bidirectional problem:
 * If building current master with Clang 18, the compiler will, by default, mangle according to the new rules. At runtime, Cling based on LLVM/Clang 16 will generate the old name, but that symbol cannot be found in the shared library.
 * Conversely, in the current attempt to upgrade to LLVM/Clang 18, the opposite situation will happen when building with an "older" compiler so the shared library has the old name.

In both cases, a failure of tutorial-tmva-tmva103_Application can be observed, when Cling cannot find the symbol.

Unfortunately, it is not easily possible to detect which symbol name is in the shared library because it depends on the host compiler and configuration. Furthermore, with the current LLVM/Clang 16, we do not have access to the new mangling. As such, the best approach in the current situation is to remove the `extern template` declarations and let Cling re-generate them as needed.

FYI @devajithvs

2024-08-06 14:42 UTC, pcanal commented
Should we also remove the explicit instantiation in `tree/dataframe/src/RDFActionHelpers.cxx`?

Alternatively, couldn't we rename those explicit instantiation and extern template and use something like:
```
private:
   template <typename T>
   void ExecImp(unsigned int slot, const T &vs)
   {
      .. current implementation ...
   }

public
   template <typename T, std::enable_if_t<IsDataContainer<T>::value, int> = 0>
   void Exec(unsigned int slot, const T &vs)
   {
      ExecImpl(slot, T);
   }
```

2024-08-06 14:42 UTC, pcanal requested changes
https://github.com/root-project/root/pull/16176#issuecomment-2271467984

2024-08-06 15:01 UTC, hahnjo commented
> Should we also remove the explicit instantiation in `tree/dataframe/src/RDFActionHelpers.cxx`?

Yes right, I forgot about the other part of the instantiations...

> Alternatively, couldn't we rename those explicit instantiation and extern template and use something like:
> 
> ```
> private:
>    template <typename T>
>    void ExecImp(unsigned int slot, const T &vs)
>    {
>       .. current implementation ...
>    }
> 
> public
>    template <typename T, std::enable_if_t<IsDataContainer<T>::value, int> = 0>
>    void Exec(unsigned int slot, const T &vs)
>    {
>       ExecImpl(slot, T);
>    }
> ```

So you mean `extern template` the new `ExecImp`? Maybe, but I doubt that it actually achieves the goal of reducing compile time because you still have to instantiate the "front-facing" `template` and neither the Kahan summation in `MeanHelper` nor the call to scalar `StdDevHelper::Exec` seems particularly expensive to generate. I think less complexity is better than highly sophisticated schemes here, without numbers I'm not convinced this is actually beneficial...

2024-08-06 15:15 UTC, pcanal commented
> So you mean extern template the new ExecImp?

Yes, this what I meant.

> because you still have to instantiate the "front-facing" template 

it is a trivial function, that we could even mark as 'force inline' to make it disappear.

> Maybe, but I doubt that it actually achieves the goal of reducing compile time .... and neither [of the functions] seems particularly expensive to generate. 

I started from the assumption that the existing code was there for a reason.  Indeed if the functions are also simple/trivial, the extern template are not needed, however then the git log need to be enhanced to justify/explain that the existing optimization was in fact not needed (assuming this is the case :) )

2024-08-07 21:44 UTC, vepadulano approved these changes
At least some of these `extern template` declaration were introduced by [this commit](https://github.com/root-project/root/commit/5cfb0853ada782f33641c22869d4de8235754cb2) which justifies them with the decreased number of templates instantiated.

Given that these changes:
* Do not affect the CI negatively
* They remove one more blocker for the upgrade to LLVM 18
* Do not introduce an obvious performance degradation and there is no benchmark pointing towards this possibility

I believe this PR should be merged

2024-08-08 13:21 UTC, dpiparo commented
I tend to agree with @vepadulano . @pcanal ?

2024-08-09 14:47 UTC, pcanal approved these changes

2024-08-11 09:32 UTC, merged