[treereader] Correctly treat empty trees with range loop iteration
root-project/root pull request #16257
Opened 2024-08-16 14:23 UTC by dpiparo

instead of allowing a spurious iteration with zero entries.

Fixes #16249

2024-08-16 16:07 UTC, pcanal requested changes

2024-08-16 16:07 UTC, pcanal commented on tree/treeplayer/inc/TTreeReader.h
> +         }
```suggestion
         if (fReader->GetTree()->GetEntriesFast() == 0 && fEntry == 0 && !lhs.IsValid()) {
            return true;
         }
         if (lhs.fReader->GetTree()->GetEntriesFast() == 0 && lhs.fEntry == 0 && !IsValid()) {
            return true;
         }
```
If `LoadTree(0)` has been called and there is really zero elements in the chain then `GetEntriesFast` will be zero.
If there is code path where we can get here and `LoadTree(0)` has not been called I suspect we could call it safely here (but hopefully we don't have this case).

2024-08-17 19:02 UTC, dpiparo commented on tree/treeplayer/inc/TTreeReader.h
> +   Iterator_t end() { return Iterator_t(*this, -1); }
thanks for the catch. It can remain const. This was a remnant of a previous attempt.

2024-08-17 19:05 UTC, dpiparo commented
all comments addressed, code updated, tests restarted.

2024-08-18 16:06 UTC, merged