[tmva][sofie]  Apply new operators and several improvements in SOFIE
root-project/root pull request #16313
Opened 2024-08-27 07:49 UTC by lmoneta

# This Pull request adds (see commits logs for more details)

- TopK, Tile and Split  operators
- If operator and support for subgraphs by parsing them from ONNX and dealing with subgraphs in RModel
- Add MatMul support for dim=1 tensors 
- Support output of operators as constant tensors

2024-09-11 00:04 UTC, sanjibansg requested changes
LGTM! 
Thanks for the implementation, all this is very helpful!
Just some small suggestions on commented code and codestyle

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie/inc/TMVA/ROperator_TopK.hxx
> +      // fShapeY[axis] = k[0]; //  [ 2 x m x n x K x p ... ]
same suggestion with the commented code here

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie/inc/TMVA/ROperator_TopK.hxx
> +      // std::cout<<"\ny size -> "<<fShapeY.size()<<std::endl;
```suggestion

```

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseConcat.cxx
> +   //case ETensorType::FLOAT:
```suggestion

```

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseConcat.cxx
> +  // }
```suggestion

```

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseReshape.cxx
> +   //                            ConvertTypeToString(input_type));
```suggestion

```

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseSlice.cxx
> +   //case ETensorType::FLOAT:
```suggestion
```

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseSlice.cxx
> +   //}
```suggestion
 
```

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseTopK.cxx
> +} // namespace TMVA
we might need to add a newline here?

2024-09-11 00:04 UTC, sanjibansg commented on tmva/sofie_parsers/src/ParseTile.cxx
> +} // namespace TMVA
same suggestion with the newline to follow the overall code style

2024-10-01 19:29 UTC, sanjibansg approved these changes
LGTM!
Thanks for this!

2024-10-02 12:37 UTC, dpiparo approved these changes
lgtm!

2024-10-02 12:40 UTC, merged