[cling] Replace all occurrences of TextInput with LineEditor
root-project/root pull request #16438
Opened 2024-09-16 08:54 UTC by devajithvs

# This Pull request:

- Replaces all occurrences of TextInput with LLVM's LineEditor library in CLING. This moves the codebase closer to clang-repl and might help in future changes.
- Corresponding replacement should also be made in `ROOT` for complete removal of TextInput, working on it. Will not be as straightforward as this.
- LineEditor does not support setting history size manually (with `CLING_HISTSIZE`) for now, we can add this functionality and add this upstream or deprecate this functionality (clang-repl does not have this feature, AFAIK). But ROOT might be relying on this feature - need to look into it.
- A couple of tests were adjusted to make the tests pass.

## Changes or fixes:

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2024-09-25 12:37 UTC, vgvassilev approved these changes
Pretty nice!

2024-09-25 12:41 UTC, hahnjo requested changes
We need to decide what to do with `CLING_HISTSIZE`. If we want to support it, the necessary changes should be upstreamed to LLVM first and then backported to our fork. Note that it would be a first and prevent building against a vanilla LLVM!

2024-09-25 13:09 UTC, vgvassilev commented
> We need to decide what to do with `CLING_HISTSIZE`. If we want to support it, the necessary changes should be upstreamed to LLVM first and then backported to our fork. Note that it would be a first and prevent building against a vanilla LLVM!

This was implemented to be able to set the history to 0 so that we do not get different pointers across gdb runs, iirc.

2024-09-26 07:28 UTC, devajithvs commented
> We need to decide what to do with `CLING_HISTSIZE`. If we want to support it, the necessary changes should be upstreamed to LLVM first and then backported to our fork. Note that it would be a first and prevent building against a vanilla LLVM!

From yesterday's discussion, it seems that this does not align with the idea of using a prebuilt vanilla LLVM. I'm tending towards deprecating `CLING_HISTSIZE`. The functionality was added here: https://github.com/root-project/root/pull/11286

Regardless, I think the ability to set a history size would be a nice feature for all the tools using it. So, I will try to upstream this anyways. `LineEditor` hardcodes history size to `800`: https://github.com/root-project/root/blob/99a126187f79163b7f5bfc506fa15903f784efbc/interpreter/llvm-project/llvm/lib/LineEditor/LineEditor.cpp#L224

2024-09-26 07:30 UTC, hahnjo commented
> > We need to decide what to do with `CLING_HISTSIZE`. If we want to support it, the necessary changes should be upstreamed to LLVM first and then backported to our fork. Note that it would be a first and prevent building against a vanilla LLVM!
> 
> This was implemented to be able to set the history to 0 so that we do not get different pointers across gdb runs, iirc.

Disabling the history can probably be implemented differently, maybe that's enough.

2024-09-26 11:06 UTC, devajithvs commented
> > > We need to decide what to do with `CLING_HISTSIZE`. If we want to support it, the necessary changes should be upstreamed to LLVM first and then backported to our fork. Note that it would be a first and prevent building against a vanilla LLVM!
> > 
> > 
> > This was implemented to be able to set the history to 0 so that we do not get different pointers across gdb runs, iirc.
> 
> Disabling the history can probably be implemented differently, maybe that's enough.

`LineEditor` doesn't seem to provide a way to do it though. I've opened a PR here: https://github.com/llvm/llvm-project/pull/110092

2025-11-03 08:05 UTC, devajithvs commented
This is marked draft because standalone cling repository will need `textinput` directory removed (which can go later but will need a separate commit in the standalone repository)

2025-11-07 12:38 UTC, hahnjo approved these changes
LGTM

2025-11-07 13:12 UTC, vgvassilev approved these changes
Nice improvement!

2026-01-13 09:55 UTC, hahnjo commented
@devajithvs this change is approved, can this go in?

2026-01-13 09:59 UTC, devajithvs commented
Yes, PR is ready (Ruff errors are unrelated to the changes). Will still need to remove `TextInput` completely from the standalone repository after merging this.

2026-01-19 12:52 UTC, merged