[skip-ci][DF] Add example how to correctly vs incorrectly run event-loop.
root-project/root pull request #16532
Opened 2024-09-26 08:24 UTC by martamaja10

Adding a very simple example (as we were showing in the student course) to showcase the difference between running the event loop vs running it multiple times. 

This PR fixes #13440.

2024-09-26 13:07 UTC, vepadulano requested changes
Thanks this is nice, some minor comments

2024-09-26 13:07 UTC, vepadulano commented on tree/dataframe/src/RDataFrame.cxx
> +For yet another example of the difference between the correct and incorrect running of the event-loop, see the following
I would add a paragraph title here, maybe like `How to properly exploit RDataFrame lazyness` or something like that

2024-09-26 13:07 UTC, vepadulano commented on tree/dataframe/src/RDataFrame.cxx
> +~~~{.cpp}
Thanks for the example, could I ask you to also provide the Python equivalent and write it before the C++, or maybe just the Python version?

2024-09-26 14:59 UTC, vepadulano reviewed
Sorry one last comment and it's good to go

2024-09-26 14:59 UTC, vepadulano commented on tree/dataframe/src/RDataFrame.cxx
> +print(f"How many times was the data set processed? {df_wrong.GetNRuns()} time/s.") # The answer will be 1 time.
Sorry I didn't notice before, I wouldn't use `time/s` as it may be read as "time per second" (at least that was my immediate reaction, might be biased). Maybe we can compute the extra "s" token by checking the number returned by `GetNRuns()`, or simply write `time(s)`.

2024-09-26 15:13 UTC, martamaja10 commented on tree/dataframe/src/RDataFrame.cxx
> +print(f"How many times was the data set processed? {df_wrong.GetNRuns()} time/s.") # The answer will be 1 time.
fair enough, it does look a bit funny indeed, I think for this example it can be just as simple as time for one case and times for the other case

2024-09-27 14:11 UTC, vepadulano approved these changes
Thank you!

2024-09-27 14:12 UTC, merged