[ntuple] add fwd compat test for unknown field structural role
root-project/root pull request #16602
Opened 2024-10-04 12:17 UTC by silverweed

Instead of throwing when deserializing a field with an unknown structural role, we assign to it structure == ENTupleStructure::kUnknown. 
FieldDescriptors with Unknown structural role will generate RInvalidFields upon calling CreateField(). 
This allows getting the descriptor for a future RNTuple from an old ROOT version.

A `fForwardCompatible` option is added to RCreateModelOptions to tell RNTuple to not throw when reconstructing the model for an RNTuple containing fields with an unknown structural role.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

2024-10-04 19:26 UTC, pcanal commented on tree/ntuple/v7/src/RNTupleDescriptor.cxx
> +         throw RException(R__FAIL("field \"" + field->GetQualifiedFieldName() + "\" could not be reconstructed"));
I think we should hint here that the message/exception can be ignored by setting a flag in a `RCreateModelOptions`, etc.

2024-10-04 19:26 UTC, pcanal commented on tree/ntuple/v7/src/RNTupleDescriptor.cxx
> +         throw RException(R__FAIL("field \"" + field->GetQualifiedFieldName() + "\" could not be reconstructed"));
(unless we should the reverse default and only throw when explicitly requested).

2024-10-06 17:46 UTC, jblomer requested changes
I think in principle the approach is valid but it's missing one more step: when we reconstruct the model in forward-compatibility mode, we need to propagate invalid fields up the schema to the top level field. I think we should skip top-level fields if anywhere in the field tree we find an invalid field. I don't think we can reliably read such top-level fields.

We should then test that if we have a model with an invalid field down the schema tree, that we can open the file in forward-compatibility mode and directly start reading data of those top-level fields that we understand.

2024-10-16 07:31 UTC, jblomer approved these changes
LGTM!

2024-10-16 08:53 UTC, merged