[TMVA] Fix warning on x86
root-project/root pull request #17147
Opened 2024-11-29 14:30 UTC by bellenot

Fix the following warning on 32 bit:
```
TMVA/ROperator_Reshape.hxx(82,74): warning GECC553F5: result of comparison of constant 9223372036854775807 with expression of type 'size_t' (aka 'unsigned int') is always false [-Wtautological-constant-out-of-range-compare]
            if ((output_length == 0 && fAllowZero == 0) || output_length > INT64_MAX) {
```

2024-11-29 16:12 UTC, lmoneta requested changes
This is not correct!
The idea here is that you get value larger than signed int because one of the inputs is negative. 
This line should  work if the sizes 
```
if ((output_length == 0 && fAllowZero == 0) || static_cast<long>(output_length)  < 0) {
```
 
since long is automatically 32 bits on 32 bit machines and 64 bits on 64 machines. In any case we don't expect to have arrays of size larger than 32 bits

2024-11-29 16:30 UTC, guitargeek commented
Thanks for saving the day Lorenzo, indeed I didn't review the PR carefully, since it's only one letter away from what I thought was the good solution (checking against the maximum of the corresponding signed type):
```c++
output_length > SSIZE_MAX
```

2024-11-29 17:02 UTC, bellenot commented
@lmoneta thanks for the clarification! But note that `long` is always 32 bit on Windows (both x64 and x86)... Is your test still valid in both cases?

2024-11-29 17:23 UTC, lmoneta commented
Thanks for pointing this out. It should still be fine as far the size of the array in question is not larger than a 32-bit integer.

2024-12-02 13:46 UTC, bellenot commented
@lmoneta I applied your suggestion. If you're sure it will work the way you want, feel free to approve this PR. Thanks!

2024-12-02 14:11 UTC, lmoneta approved these changes
LGTM!
Thank you Bertrand for fixing this warning!

2024-12-02 14:12 UTC, merged