[io] set TKey default title empty
root-project/root pull request #17236
Opened 2024-12-10 14:07 UTC by jblomer

Currently, the default title for a TKey is "object title". Objects that do not derive from TObject have no means to change this title. Change the default title to the empty string to save a few bytes per non-TObject object and to reduce the "noise" when listing directory contents.

2024-12-10 14:45 UTC, enirolf approved these changes
There is still a clang-format complaint about `TDirectory* motherDir` (pointer should attach to `motherDir`), otherwise LGTM, thanks!

2024-12-10 15:00 UTC, pcanal approved these changes
Thanks.

2024-12-11 09:04 UTC, hahnjo requested changes
There's a crash in `roottest-root-io-TFile-make` that might be related (?), and `roottest-root-meta-runnamespace-auto` needs an update of the reference file

2024-12-13 08:06 UTC, hahnjo approved these changes

2024-12-13 09:28 UTC, merged