[ntuple] allow RNTuple to emulate fields of unknown types via RecordFields
root-project/root pull request #17288
Opened 2024-12-17 16:15 UTC by silverweed

# This Pull request:
adds the option to "emulate" fields of unknown user-defined types (i.e. types for which we lack dictionaries) as RecordFields whose structure is reconstructed from the on-disk information. This is off by default but can be toggled via `RCreateModelOptions`.

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2024-12-18 09:51 UTC, silverweed commented
Unfortunately this approach doesn't work in all cases.

When replacing the InvalidFields we would also need to patch up stuff like fItemSize on the parent, which is brittle to do.
Probably the only robust way to go is to construct the field hierarchy bottom-up. To do so, my and Jakob's idea is:
- change RFieldBase::Create() so that it returns a "FieldGenerator" rather than a field. This is a functor that accepts a Descriptor for the field and returns a RFieldBase
- recursively construct a tree of Generators from RFieldBase::Create()
- from RFieldDescriptor::CreateField(), visit the tree of generators and replace all RInvalidField generators with the respective record field generators, then call the generators depth-first to construct the field tree.

2024-12-26 20:21 UTC, pcanal commented
I am confused.  Why do we need to emulate the case?  What is the usage pattern we are trying to emulated?  Isn't it enough to write the `RNTuple` in one process with the dictionary and read it in a different process without the dictionary?

2025-01-07 07:55 UTC, silverweed commented
@pcanal The use case is reading a RNTuple as best as possible when the dictionaries for some of the types stored are not available. For example we still want to be able to print out the schema of the RNTuple even when we have no clue about the specifics of the types stored.
Maybe the word "emulate" is not the best choice here, but the idea is adding the capability for RNTuple to reconstruct the type hierarchy without actually recreating the original classes, but "emulating" them with Record fields instead.

2025-01-09 07:55 UTC, hahnjo requested changes
I left some initial comments. In general, I find this PR hard to follow because some implementations get changed multiple times and some commits introduce options but only half implement them. Can you maybe try to clean this up a bit? Also many of the intermediate commits will probably not compile / pass the tests...

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_fork.hxx
> +#pragma once
We generally don't use `#pragma once` in ROOT and RNTuple

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_evolution.cxx
> +#define NTUPLE_FORK_MACROS
Eww, this is ugly. Can we just have all implementations in a header file that we can include into multiple tests?

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_fork.hxx
> +#ifdef NTUPLE_FORK_MACROS
Why do we need to protect these macro definitions? But see also my other comment if we can just have all implementations in a header file

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_evolution.cxx
> +   ExecInFork([&] {
These changes have to go into the commit that renamed the functions!

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_emulated.cxx
> +      } catch (ROOT::RException ex) {
has to go into the commit that added the test

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_evolution.cxx
> +   ExecInFork([&] {
has to go into the commit that renamed the functions

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
> +          DescriptorId_t fieldId = kTraitInvalidField);
This looks odd to me: Is `kTraitInvalidField` really (semantically) a `DescriptorId_t`?

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
> +
Do we need this generically in `RFieldBase` or can this move to `RRecordField`? potentially as a constructor option or with a factory method (was we have `RVectorField::CreateUntyped()`)

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/src/RFieldSequenceContainer.cxx
> +      R__ASSERT(fItemSize > 0);
This looks unrelated to the emulation itself

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_emulated.cxx
> +      } catch (RException ex) {
change to `ROOT::RException` needs to move here from another commit, and the compiler complains:
```
catching polymorphic type ‘class ROOT::RException’ by value
```

2025-01-09 07:55 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_emulated.cxx
> +      } catch (ROOT::RException ex) {
The compiler complains
```
catching polymorphic type ‘class ROOT::RException’ by value
```

2025-01-09 08:01 UTC, silverweed commented on tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
> +          DescriptorId_t fieldId = kTraitInvalidField);
No, this was an oversight: it was supposed to be kInvalidDescriptorId. Thanks for spotting it.

2025-01-09 08:02 UTC, silverweed commented on tree/ntuple/v7/src/RFieldSequenceContainer.cxx
> +      R__ASSERT(fItemSize > 0);
I found a crash while testing it and it didn't look like it was worth a separate PR (or even commit)...

2025-01-12 23:18 UTC, jblomer reviewed
Very nice! We should also add and test emulated collection proxies (probably in another PR).

2025-01-12 23:18 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
> +                                                      DescriptorId_t fieldId);
I think we should update the method documentation for the new parameters

2025-01-12 23:18 UTC, jblomer commented on tree/ntuple/v7/src/RFieldBase.cxx
> +      bool isInvalidField = f.GetTraits() & RFieldBase::kTraitInvalidField;
```suggestion
      const bool isInvalidField = f.GetTraits() & RFieldBase::kTraitInvalidField;
```

2025-01-12 23:18 UTC, jblomer commented on tree/ntuple/v7/src/RFieldBase.cxx
> +         return fieldDesc.GetLinkIds()[childIdx];
Let's access with bounds check, just in case the descriptor is corrupted.
```suggestion
         return fieldDesc.GetLinkIds().at(childIdx);
```

2025-01-12 23:18 UTC, jblomer commented on tree/ntuple/v7/src/RFieldBase.cxx
> +            assert(desc);
This option can be set through the public API and then we don't have a descriptor, no?

2025-01-13 09:13 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_evolution.cxx
> +   ExecInFork([&] {
still needs to go into the commit that renamed the function

2025-01-13 10:56 UTC, silverweed commented on tree/ntuple/v7/test/ntuple_evolution.cxx
> +   ExecInFork([&] {
I was sure I moved this, no idea how did this slip through.

2025-01-13 13:08 UTC, silverweed commented on tree/ntuple/v7/src/RFieldBase.cxx
> +            assert(desc);
With [e2c3074](https://github.com/root-project/root/pull/17288/commits/e2c3074bf4a2a3af219060f45f24ceb2da346dfa) the user cannot directly call `RFieldBase::Create()` with `fEmulateUnknownTypes == true`, so this code path is only taken when called by `RFieldDescriptor::CreateField` (which does pass down the descriptor)

2025-01-16 08:27 UTC, hahnjo commented on tree/ntuple/v7/src/RFieldBase.cxx
> +   return R__FORWARD_RESULT(RFieldBase::Create(fieldName, canonicalType, typeAlias, options));
Should this just forward to `Create(fieldName, typeName, options, nullptr, kInvalidDescriptorId)`?

2025-01-16 08:27 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_emulated.cxx
> +struct Inner {
You should uniquely prefix the `struct` names to prevent any caching in the parent process when reading the file.

2025-01-16 08:27 UTC, hahnjo commented on tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
> +                                                     const RCreateFieldOptions &options) const;
I think this `friend` declaration becomes redundant with the next commit

2025-01-16 08:27 UTC, hahnjo commented on tree/ntuple/v7/test/ntuple_emulated.cxx
> +struct Inner {
Should also be prefixed, see comment on a previous commit

2025-01-21 12:57 UTC, hahnjo approved these changes
LG from my side; there are some stray lines in commit messages that look like the result of squashing, and one comment about a non-compiling commit (not sure)

2025-01-21 12:57 UTC, hahnjo commented on tree/ntuple/v7/src/RNTupleDescriptor.cxx
> +      auto field = Internal::CallFieldBaseCreate(fieldName, typeName, typeName, options, &ntplDesc, fFieldId).Unwrap();
I'm not sure, but doesn't that mean that the previous commit doesn't compile?

2025-01-22 07:46 UTC, merged