[ntuple] set NEntries in RPagePersistentSink::InitFromDescriptor
root-project/root pull request #17306
Opened 2024-12-19 10:47 UTC by silverweed

Also add a bunch of `reserve()` where appropriate

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

2024-12-19 14:36 UTC, jblomer approved these changes
LGTM

2025-01-06 07:29 UTC, hahnjo requested changes
(also for the record, I'm getting less sure about all those `reserve`s sprinkled in; at least for me, they really decrease code readability for oftentimes questionable benefit...)

2025-01-06 07:29 UTC, hahnjo commented on tree/ntuple/v7/src/RPageStorage.cxx
> +      fDescriptorBuilder.AddNEntries(nEntries);
Can you comment on why we want this? This now makes `InitFromDescriptor` different from normal descriptor building where `NEntries` is only updated when adding a cluster group. This is also documented in the comment of `RNTupleDescriptor::fNEntries`, which would need at least some updating with this change. More generally, for knowing the number of "entries in flight", we can just look at `fPrevClusterNEntries`, no?

2025-01-07 08:49 UTC, silverweed commented on tree/ntuple/v7/src/RPageStorage.cxx
> +      fDescriptorBuilder.AddNEntries(nEntries);
The reason has to do with support for incremental merging with late model extension: currently if you open an existing RNTuple with the RNTupleMerger and you try to late-model extend it, it will call `RPageSink::UpdateSchema` passing the number of entries _processed so far_, which doesn't include the number of previously-existing entries in the destination. 

In theory this information is already stored in `fPrevClusterNEntries` when initting the Sink from the descriptor, but it's not accessible. I figured it would make more sense from a user standpoint to have `GetNEntries()` return the correct number of already-existing entries immediately after initting the descriptor, rather than creating a separate getter specifically for the Sink (which would only make sense for the PersistentSink at that).

2025-01-09 07:29 UTC, hahnjo commented on tree/ntuple/v7/src/RPageStorage.cxx
> +      fDescriptorBuilder.AddNEntries(nEntries);
As discussed offline, changing `fNEntries` in normal descriptor building earlier than the cluster group may give us problems later on with sharded clusters. We could also ignore them for now and worry later.

Looking at this again, I think we have two other options:
1. We could create a separate getter in the sink. After all, incremental merging was the use case I added `RPageSink::GetDescriptor()` for, which returns an empty descriptor for example for `RPageNullSink`. I think adding another one would be acceptable.
2. In `InitFromDescriptor`, we could in principle commit a cluster group at the end, which would update `fNEntries` in the descriptor. When I added support for incremental merging, we decided to fully flatten out all cluster groups in the input - we could potentially revisit this.

2025-01-13 07:54 UTC, hahnjo requested changes

2025-01-13 07:54 UTC, hahnjo commented on tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
> +
This method is not needed

2025-01-13 07:54 UTC, hahnjo commented on tree/ntuple/v7/src/RNTupleDescriptor.cxx
> +   });
Can you please remove, or at least separate out, unrelated changes?

2025-01-13 07:54 UTC, hahnjo commented on tree/ntuple/v7/src/RNTupleDescriptor.cxx
> +
not needed

2025-01-13 07:54 UTC, hahnjo commented on tree/ntuple/v7/src/RPageStorage.cxx
> +   fOpenPageRanges.reserve(fOpenPageRanges.size() + (nColumns - nColumnsBeforeUpdate));
Do these really provide any measurable improvement? IMHO it should at least be a separate commit, maybe even a separate PR

2025-01-13 12:24 UTC, silverweed commented on tree/ntuple/v7/src/RPageStorage.cxx
> +   fOpenPageRanges.reserve(fOpenPageRanges.size() + (nColumns - nColumnsBeforeUpdate));
Reserving an array when the size is known a priori is just the correct thing to do and there should be a very good reason *not* to do so, rather than having to justify doing it.  I don't agree with the fact that these hinder readability. Otherwise, for the same reasoning, we should provide measurements every time we choose to pass a `const std::string &` rather than a `std::string` and similar.

2025-01-14 07:56 UTC, hahnjo commented on tree/ntuple/v7/src/RPageStorage.cxx
> +   fOpenPageRanges.reserve(fOpenPageRanges.size() + (nColumns - nColumnsBeforeUpdate));
We can agree to disagree. It's an extra line with an argument that you need to use brain power to understand and hopefully get right, where in many cases it doesn't buy you anything measurable. I think the comparison to passing by reference doesn't make sense because that one a) is the same line, so it's not extra, and b) there is a semantic difference between passing a const-ref and creating a copy.

2025-01-14 08:32 UTC, merged