[hadd] [WIP] Adding posibility to only hadd listed directories
root-project/root pull request #4615
Opened 2019-11-05 10:31 UTC by Daniel-Dane

hadd (and TFileMerger) has been missing the possibility to only hadd certain directories (and their content) of a bunch of root files. This is my attempt.

2019-11-05 15:22 UTC, pcanal commented
@phsft-bot build

2019-11-05 15:23 UTC, pcanal commented
Thanks for this contribution.

Can you also add tests for this (new) feature?  Thanks.

2019-11-05 17:03 UTC, Daniel-Dane commented
Thanks for looking at my pull request. I initially only tested a few root files that all had the same histograms. Now, when I try to hadd files with histograms with different names, it crashes with:
`Fatal in <TFileMerger::RecursiveRemove>: Output file of the TFile Merger (targeting bla3.root) has been deleted (likely due to a TTree larger than 100Gb)`

I will return when I have fiddled some more with it. Unfortunately for this request, I have solved the issue that prompted this work by chaining `rootcp` for the specific folders to temp. files and `hadd`ing them.

2025-01-13 10:53 UTC, silverweed requested changes

2025-01-13 10:53 UTC, silverweed commented on main/src/hadd.cxx
> +            if (tmp == "SkipListed")
hadd should give an error if you try specifying the option twice. However I suggest you first rebase your PR on master because the argument parsing code has changed significantly and you should integrate your change with it.

2025-01-13 10:53 UTC, silverweed commented on main/src/hadd-argparse.py
> +	parser.add_argument("-objects", help="List of space-separated keys (folders, histograms) to either include or exclude from the input files")
I don't like much having space-separated keys in this context (it makes the parsing code harder than it could be and in general it intermingles with the space-separated top-level options), maybe it'd be better to choose a different separator like `,` or `;`.
However see my other comment about rebasing your PR first

2025-01-13 10:55 UTC, silverweed commented
I was added to this review so I added a couple of comments, but then I noticed it's from 2019...are we still interested in this @pcanal ?

2025-01-13 20:27 UTC, pcanal commented
@silverweed The author did not return to this and the patch is probably mostly obsolete code wise with the recent change.  The question(s) is indeed whether we do want this features and whether it is 'easy' to add to the current code (probably from scratch).

2025-01-14 07:40 UTC, silverweed commented
It should be fairly easy to add; whether we want it or not, I'm not sure: has this been requested anywhere else? Is anyone still interested in this?

2025-02-04 13:34 UTC, silverweed commented
Superseded by #17612

2025-02-04 13:34 UTC, closed without merging