Update TVirtualX.cxx
root-project/root pull request #6547
Opened 2020-10-02 20:57 UTC by andriish

This will partially fix #6543 
The full fix should include 
``
 if (fDefaultFont) gval.fFont       = fDefaultFont->GetFontHandle();
...
  if(fDocPropFont) gval.fFont       = fDocPropFont->GetFontHand
...   
if (fStatusFont) gval.fFont       = fStatusFont->GetFontHandle();
```
in the TGResourcePool.cxx
However, I don't know if that makes sense, so I don't include it.

Tag @couet  @lmoneta

2020-10-02 20:59 UTC, andriish commented
I mean of course 

```
if (fStatusFont) gval.fFont       = fStatusFont->GetFontHandle();
```
should be there, but I don't know if there should be something like
```
if (fStatusFont) gval.fFont       = fStatusFont->GetFontHandle(); else   gval.fFont       = ... 
```

2020-10-05 13:53 UTC, couet commented
You said:
This will partially fix #6543
But #6543 is a closed PR .... not an issue ...

2020-10-05 14:20 UTC, andriish commented
Hi @couet 

Yes, I mean:

#6483 

Clicked at wrong  github popping suggestion.


Best regards,
Andrii

2020-10-20 11:36 UTC, bellenot requested changes
Please give more details on what your patch is fixing

2020-10-20 11:36 UTC, bellenot commented on gui/gui/src/TGResourcePool.cxx
> +   gval.fFont       = fDefaultFont?fDefaultFont->GetFontHandle():FontH_t(0);
```suggestion
   gval.fFont       = fDefaultFont ? fDefaultFont->GetFontHandle() : FontH_t(0);
```

2020-10-20 11:36 UTC, bellenot commented on gui/gui/src/TGResourcePool.cxx
> +   gval.fFont       = fDocPropFont?fDocPropFont->GetFontHandle():FontH_t(0);
```suggestion
   gval.fFont       = fDocPropFont ? fDocPropFont->GetFontHandle() : FontH_t(0);
```

2020-10-20 11:36 UTC, bellenot commented on gui/gui/src/TGResourcePool.cxx
> +   gval.fFont       = fStatusFont?fStatusFont->GetFontHandle():FontH_t(0);
```suggestion
   gval.fFont       = fStatusFont ? fStatusFont->GetFontHandle() : FontH_t(0);
```

2020-10-20 12:13 UTC, andriish commented
Hi @bellenot ,

The patch fixes the crash in reproducer in #6483 .

The reason of the crash is that in a batch mode the ListFonts() from TVirtualX is called. The current version of ListFonts() does not return 0 fonts (but it should!)  and then the functions that try to deal with fonts crash everything.
Right now I cannot recall the exact call chain that leads to crash, but here are just some cases of undefined behaviour:
```
char **TGFontPool::GetFontFamilies()
{
   Int_t i, numNames;
   char *family, *end, *p;

   THashTable familyTable(100);
   familyTable.SetOwner();

   char **nameList;
   char **dst;

   // coverity[returned_null]
   // coverity[dereference]
   nameList = gVirtualX->ListFonts("*", 10000, numNames);

   for (i = 0; i < numNames; i++) {       <-- numNames is not initialized explicitly 

```

The second part of the fix is in the TGResourcePool.cxx . Basically the fix is for the case  when no fonts were given back, i.e. just avoiding null pointer dereference.

Best regards,

Andrii

2020-10-20 12:23 UTC, bellenot commented
OK, I see, thanks for the clarification @andriish !

2020-10-20 12:24 UTC, bellenot approved these changes

2020-11-12 12:40 UTC, merged