TClass::GetListOfDataMembers reload list for struct/class when needed.
root-project/root pull request #6668
Opened 2020-10-19 21:33 UTC by pcanal

The problem was due  the introduction (in commit f3f0f13) of a fast path in TClass::GetListOfDataMember which did not take in consideration the case:

c = GetClass(someclassname)
c->GetState() == TClass::kForwardDeclared
c->GetListOfDataMember() -> list is now created but empty.
load and parse header file for
c->GetState() == TClass::kInterpreted
c->GetListOfDataMember() -> list is still empty but should have been filled (loaded at this point).

The logic assumed incorrectly that if someclassname was indeed pointing to a class or struct and the list was created then it was loaded.

To keep the fast path and correct the logic, we need to 'promote' TListOfDataMembers::fIsLoaded to be an std::atomic

2020-10-20 09:44 UTC, jblomer requested changes
Looks good to me!

The example from the PR description should be added as a test case.

2020-10-20 13:19 UTC, pcanal commented
Yep.  The test is in https://github.com/root-project/roottest/pull/617

2020-10-20 13:21 UTC, pcanal commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2020-10-20 20:18 UTC, pcanal commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2020-10-21 07:47 UTC, jblomer approved these changes

2020-10-21 16:19 UTC, Axel-Naumann approved these changes

2020-10-22 20:42 UTC, pcanal commented
The macos failure is unrelated (complains about an on-going git rebase).

2020-10-22 20:42 UTC, merged