[RF] Purge old batch interface
root-project/root pull request #6841
Opened 2020-11-18 17:03 UTC by manolismih

This PR purges the old 
```c++
"evaluateBatch|getValBatch|getLogValBatch"(std::size_t begin, std::size_t batchSize)
```
interface of the roofit classes with the 
```c++
"evaluateSpan|getValues|getLogs"(BatchHelpers::RunContext& evalData, const RooArgSet* normSet)
```

To this point, both interfaces exist. In this PR the old methods are deleted and the code is cleared, with the exception of marking the purged methods as `= delete` in RooAbsReal.cxx, to prevent users that write their own PDF classes to use them or overwrite them. In the very few cases where users have already implemented such a deleted function, they will get a compilation error, so I will make sure that there's a detailed and easy walkthrough in the release notes of the next versions of how to port their code to use the new interface. The process is very simple, so the users that have used the old interface are more advanced than needed to make this change.

2020-11-18 17:59 UTC, manolismih commented
@phsft-bot build just on ROOT-debian10-i386/cxx14

2020-11-19 11:18 UTC, hageboeck requested changes
Nice to see that it finally disappears. A few things:
- The implementation of RooUniform will return wrong values.
- ROOT will not compile between the first commits. Reorder as follows*:
  1. Update from old to new interfaces. (No harm updating because we have a fallback function)  
  2. Removal of all code where the interface is *called*. That includes the tests.
  3. Removal of old interface **both** in header and cxx simultaneously (it's OK to do separate commits for roofitcore, roofit, etc)
  4. Removal of `BatchData.h`
- It would be nice if you rewrote the author in git where I cleaned up my own mess in `RooVectorDataStore::getWeightBatch()` :-). Use e.g. `git commit --amend --author="Stephan Hageboeck <stephan.hageboeck@cern.ch>" --no-edit` during an interactive rebase.

[*] Why is this important? If somebody tries to do a `git bisect` (look it up - it's amazing!), it might stop between those revisions because ROOT does not compile. You then force them to move forward or backward until ROOT compiles again, and then they can continue the bisect. Try to always make ROOT compile! You can e.g. start an interactive rebase, and stop at the commit in question, compile, and continue with the next commit etc if you see a risk that something might not compile. That's especially useful when you reorder commits.
(For tests, it doesn't need to be as strict. During a bisect, you usually only run one or a few tests that you are interested in. It *might* be acceptable if one test or so fails for a few commits, but obviously we prefer if everything works just fine.)

2020-11-19 11:18 UTC, hageboeck commented on roofit/roofitcore/inc/RooAbsReal.h
> +  virtual RooSpan<const double> getValBatch(std::size_t begin, std::size_t maxSize, const RooArgSet* normSet = nullptr) = delete;
A comment what happened to the function and how people who were using it can update is needed (if there are any :-) ).

2020-11-19 11:18 UTC, hageboeck commented on roofit/roofitcore/inc/RooAbsReal.h
> +  virtual RooSpan<double> evaluateBatch(std::size_t begin, std::size_t maxSize) = delete;
Same here. Comment what happened to the function.

2020-11-20 11:19 UTC, hageboeck reviewed
Can you try to remove the dead interface that I marked?

2020-11-20 11:19 UTC, hageboeck commented on roofit/roofitcore/inc/RooAbsCategory.h
> +  virtual RooSpan<const value_type> getValues(BatchHelpers::RunContext&, const RooArgSet* = nullptr) const {
Try to remove this. It think it's not needed. When batch values for categories are desired, it can easily be added.

2020-11-20 11:19 UTC, hageboeck commented on roofit/roofitcore/inc/RooAbsReal.h
> +  // please consult the release notes for ROOT 6.24 for a quick and easy walkthrough on how to make this transition.
Please use three slashes, so doxygen can display it on the [website](https://root.cern.ch/doc/master/classRooAbsReal.html).
```
/// \deprecated getValBatch() has been removed in favour of getValues(). If your code is affected by this change,
/// please consult the release notes for ROOT 6.24 for guidance on how to make this transition.
```
I prefer to not say that something is quick and easy. Some people might disagree. :-)

2020-11-20 11:19 UTC, hageboeck commented on roofit/roofitcore/inc/RooAbsReal.h
> +  // please consult the release notes for ROOT 6.24 for a quick and easy walkthrough on how to make this transition.
```
/// \deprecated evaluateBatch() has been removed in favour of evaluateSpan().
/// If your code is affected by this change, please consult the release notes for ROOT 6.24 for guidance on how to make this transition.
```

2020-11-20 11:19 UTC, hageboeck commented on roofit/roofitcore/inc/RooCategory.h
> +  virtual RooSpan<const value_type> getValues(BatchHelpers::RunContext&, const RooArgSet* = nullptr) const override{
Try to remove as well.

2020-11-23 11:18 UTC, hageboeck approved these changes
Nice!

There's one more thing that has to be done, and one optional suggestion. I'll approve nevertheless, so you can merge when done.

2020-11-23 11:18 UTC, hageboeck commented on roofit/roofitcore/inc/RooAbsCategory.h
> +}
Remove.

2020-11-23 11:18 UTC, hageboeck commented on roofit/roofitcore/src/RooAbsReal.cxx
> +  }
Trying to make as many helpers `const` as possible, one would write:
```c++
const std::size_t dataSize = std::max_element(leafValues.begin(), leafValues.end(),
    [](const RooSpan<const double>& span){ return span.size(); } )->size();
```
This requires probably `#include <algorithm>`, and I leave it to you to decide if that's readable enough to use it here.

2020-11-23 12:59 UTC, merged