Eve-7 Additional checks and minor corrections
root-project/root pull request #7153
Opened 2021-02-08 20:40 UTC by alja

These changes are needed for use of CMS web event display.

2021-02-08 20:41 UTC, alja commented
@linev Please check.

2021-02-09 07:28 UTC, linev commented
@phsft-bot build

2021-02-09 10:52 UTC, linev requested changes

2021-02-09 10:52 UTC, linev commented on graf3d/eve7/inc/ROOT/REveManager.hxx
> +
I recommend to use here `std::shared_ptr<RWebWindow>` as return value

2021-02-09 10:52 UTC, linev commented on graf3d/eve7/inc/ROOT/REveDataCollection.hxx
> +   void SetFillImpliedSelectedDelegate (std::function<void (REveDataItemList*, Set_t& impSelSet)> handler_func);
1. Please use typedefs for function types.
2. Use these typedefs also when declaring class members `_handler_items_change` and `_handler_fillimp`
3. Use default naming convention for these members like `fHandlerItemsChange`

2021-02-09 10:52 UTC, linev commented on graf3d/eve7/src/REveDataCollection.cxx
> +void REveDataItemList::FillImpliedSelectedSet( Set_t& impSelSet)
According to clang-format it should be `Set_t &impSelSet` - please use it like this

2021-02-09 10:52 UTC, linev commented on graf3d/eve7/src/REveDataCollection.cxx
> +   REveSelection* selection = (REveSelection*) ROOT::Experimental::gEve->FindElementById(selectionId);
Same clang-format problem here.
Also when doing explicit cast, one should better use `static_cast<REveSelection *>()`

2021-02-09 10:52 UTC, linev commented on graf3d/eve7/src/REveDataProxyBuilderBase.cxx
> +         return;
Please use correct indentation:
```
if (!m_collection->GetRnrSelf())
   return;
```

2021-02-09 19:08 UTC, alja commented
@lineve Thank you for the corrections!

2021-02-09 19:15 UTC, linev commented
@alja, can you provide and use typedef for functions:
```
 std::function<void (REveDataItemList*, const std::vector<int>&)> 
 std::function<void (REveDataItemList*, Set_t& impSel)>
```

2021-02-09 19:41 UTC, alja commented
@linev
I don't have an alias for a plain vector of integer which is used in ItemsChange callback. Alias Set_t is std:set of EveElement pointers and is used in FillImpliedSelected callback through REveSelection mechanism.
I agree Set_t can be confused with integer set. It is extensively used n eve and I would not change it right now.

2021-02-09 21:22 UTC, linev commented
I mean use 
```
typedef  std::function<void (REveDataItemList*, const std::vector<int>&)> ItemListVectorFunc_t;  
```
And then use ` ItemListVectorFunc_t` as type of data member and as type of setter argument

2021-02-10 06:51 UTC, linev commented
@phsft-bot build

2021-02-10 06:54 UTC, linev approved these changes

2021-02-10 17:05 UTC, merged

2021-02-10 18:18 UTC, alja commented
@linev The alias for the functions made code more readable. Thank You!