Fix a memory leak in TF1::Copy - backport to 6.22
root-project/root pull request #7193
Opened 2021-02-12 11:40 UTC by mrodozov

This is a request for backport of https://github.com/root-project/root/pull/7035
to 6-22 patches because of this ClassDef change:
`   ClassDef(TF1, 11) // The Parametric 1-D function` (previous was 10)
which we are checking in this test:
https://github.com/cms-sw/cmssw/blob/master/DQMServices/Components/test/testSchemaEvolution.cpp#L44
and should have one or the other version, and we better use this fix in 6-22 anyway.

2021-02-22 10:50 UTC, mrodozov commented
dears, any comment on this please ?

2021-02-22 12:09 UTC, couet commented
@lmoneta is the expert in this field. He will take care.

2021-02-22 14:58 UTC, lmoneta reviewed
The PR looks fine to me. But it is not only a back port of the fix in TF1::Copy ( #7183), 
it contains also the improvements in TF1::GetRandom ( PR #6257).
I think that should be  separate PR if needed, but for consistency it should include also the similar changes in TH1.

2021-02-23 17:17 UTC, pcanal commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-02-26 15:52 UTC, mrodozov commented
I added the TH1 changes, this leads to a lot of warnings,
I guess this comes from implementations expecting the old interfaces.
Should I keep the old interfaces as well so whatever was implementing them to "see" what's expected ? (excuse my ignorance but I haven't been coding consistently for some time to remember this much by heart)

2021-02-26 19:19 UTC, mrodozov commented
never mind the last question if the old ifaces are kept this leads to ambiguity and it doesn't compile

2021-03-01 09:20 UTC, mrodozov commented
@lmoneta did I understand correct how to get also the TH1 changes ?

2021-03-01 09:33 UTC, lmoneta commented
Hi, 
Do you need to have the changes in GetRandom in 6.22 ? 
These are more feature changes than bug fixes, so I will prefer avoiding the back port.
Anyway, yes this should be in case a separate PR to distinguish the two cases. 
Furthermore, if we back port the fix in TF1::Copy we should also back port this one too, 
https://github.com/root-project/root/pull/7274.

If you have trouble doing this back port, I can do it. But please confirm, what exactly you need to be back ported in 6.22

Cheers 
 Lorenzo

2021-03-01 09:48 UTC, mrodozov commented
I'd prefer avoiding it, too. All I need is the changes in TFormula and it's ClassDef 
change:

https://github.com/root-project/root/pull/7193/files#diff-ca4416e47d798b9a8d5fbf80c478df1437d0ea6a9def18939f8d9c6d29869906R254

If I take line 96 and 254 alone, where I assume 96 is the reason for incrementing the ClassDef 
will that be enough ? I need the TFormula ClassDef change, thats it

2021-03-01 12:24 UTC, mrodozov commented
@lmoneta I took only the TFormula changes that I need 
`std::unique_ptr<TMethodCall> fMethod`
this avoids the other backports

2021-03-01 13:21 UTC, lmoneta commented
Yes, this back port should be fine, also fMethod is transient so there will be no issue in the I/O. 
If you need the back port for the TF1 (memory leak fixes in TF1 Copy) we can add as a separate PR
I will run the CI before merging it 
Thank you for updating this PR

2021-03-01 13:21 UTC, lmoneta commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-03-01 13:29 UTC, mrodozov commented
No, we don't need TF1 changes. Only the TFormula ClassDef version to be consistent in 622 and master
We'll get the TF1 fix with 6.24

2021-03-01 15:01 UTC, mrodozov commented
Sorry this is all wrong . We need the TF1 in ClassDef in fact. I got confused of all this adjustments :/

2021-03-01 17:06 UTC, mrodozov commented
@lmoneta now it's fine . I got the changes also for TF1 without touching the GetRandom changes (just the pointer modifications as in TFormula)
 . sorry for the noise 😅 I'll squeeze the commits if necessary

2021-03-01 18:11 UTC, lmoneta commented
Yes, I think is ok now.
Maybe it would be better and more consitent to backport directly the version 12 of TF1 existing in master, which includes  this recent commit:
https://github.com/root-project/root/pull/7274/commits/6a70887d3e61f71070a1ab203810e751b1db5eae

2021-03-01 18:44 UTC, mrodozov commented
it's updated to the last version

2021-03-01 18:49 UTC, lmoneta commented
Thank you ! Looks good to me now. 
Before merging, let;s see the CI results

2021-03-01 18:49 UTC, lmoneta commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-03-01 23:00 UTC, mrodozov commented
I see the test values for stress test were increased in the same PR
https://github.com/root-project/root/pull/7274/commits/fe5c74b5ed6045eb72091bad693f7af1fdf2266e
but I don't see why the other test is failing :/

2021-03-02 08:28 UTC, mrodozov commented
@lmoneta can I do something to fix this test ?

2021-03-02 13:31 UTC, lmoneta commented
Hi, 
Yes this PR needs to include the changes in the stresss test of fe5c74b.
I will check and try to understand why the other test is failing

2021-03-02 14:45 UTC, mrodozov commented
limits are updated

2021-03-02 15:26 UTC, lmoneta requested changes

2021-03-02 15:26 UTC, lmoneta commented on hist/hist/inc/TF1.h
>     std::unique_ptr<TF1AbsComposition> fComposition; //! Pointer to composition (NSUM or CONV)
This should not be a transient member!! 

Please remove the `!` and change from 
```
std::unique_ptr<TF1AbsComposition> fComposition; //! Pointer to composition (NSUM or CONV)
```
to 
```
std::unique_ptr<TF1AbsComposition> fComposition; // Pointer to composition (NSUM or CONV)
```

2021-03-02 15:28 UTC, lmoneta commented on hist/hist/inc/TF1.h
>     std::unique_ptr<TF1AbsComposition> fComposition; //! Pointer to composition (NSUM or CONV)
I think this caused the failare observed in the TF1 test. 
Thank you for updating it. I will run then the builds again afterwards

2021-03-02 15:49 UTC, mrodozov commented
ok it's updated

2021-03-02 16:12 UTC, lmoneta commented
Thank you!

2021-03-02 16:12 UTC, lmoneta commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-03-02 20:56 UTC, merged