[ntuple] Add RField descriptions members
root-project/root pull request #7399
Opened 2021-03-06 21:18 UTC by mxxo

Allow setting RNTuple field descriptions. The immediate motivation for this PR is for use by the ongoing CMS RNTuple NanoAOD output module. The new APIs are a direct analogue to `TBranch::SetTitle`. Field descriptions are added at the `RNTupleModel` level. There currently is no way to adjust field descriptions after creation. 

There is a new  `RNTupleModel::AddField` overload that takes a description parameter and a new `RNTupleModel::MakeFieldWithDescription` method. The latter was added because of difficulties overloading the existing variadic template method `MakeField`.

2021-03-08 13:00 UTC, jblomer requested changes
Very nice!  My only concern is the name `MakeFieldWithDescription`, which is a little long for my taste.  How about `MakeField` and `AddField` overloads that take a tuple as a first parameter, so that you can write

    MakeField<float>({"pt", "transverse momentum"}, 0.0);

2021-03-08 13:02 UTC, jblomer commented on tree/ntuple/v7/test/ntuple_basics.cxx
> +   ASSERT_EQ(fieldDescriptions.size(), 3);
Arguments of `ASSERT_EQ` and `EXPECT_EQ` should be reversed

2021-03-09 15:35 UTC, mxxo commented
I like the tuple approach much better! I'm struggling to build master right now but will rebase with this change as soon as I can.

2021-03-10 21:15 UTC, jalopezg-r00t reviewed
I was wondering where the field description was [already] serialized/deserialized; I found it in `RNTupleDescriptor.cxx: SerializeField()`.

LGTM.  :-)

2021-03-12 13:45 UTC, jblomer approved these changes

2021-03-12 13:45 UTC, merged