[ntuple] Add RNTupleModel::HasField
root-project/root pull request #7480
Opened 2021-03-11 22:57 UTC by mxxo

Add a helper method to check whether a model has a field with the
given name. We're using `string_view` on the API boundary, but this
unfortunately requires a `std::string` temporary to check if the name
exists in the unordered_set of field names until P0919R3 lands in
C++20. Switching to a plain `std::set` would also avoid this problem.

2021-03-12 13:22 UTC, jblomer requested changes
We should clarify if this is only for top-level fields or also for subfields, e.g. "jets.pt".  The string temporary is acceptable, this should not be performance-critical code.

2021-03-12 17:19 UTC, mxxo commented
Thank you Jakob, that's an important case. It seems useful to be able to look up any name, not just top level ones, so I added that in 81063cf.

2021-03-17 17:59 UTC, mxxo commented
As discussed, this PR isn't ready because it doesn't handle class subfields correctly, e.g. this test fails: 
```cpp
struct CustomStruct {
   float a = 0.0;
   std::vector<float> v1;
   std::vector<std::vector<float>> v2;
   std::string s;
};
... 
auto ptrKlass = model->MakeField<CustomStruct>("klass");
// fails
EXPECT_TRUE(model->HasField("klass.a")); 
```
A better approach might be to traverse the model tree to check field names.

2021-03-25 19:36 UTC, mxxo commented
Updated with a full tree search, which also lets us remove the `RNTupleModel` field name set member entirely.

2021-03-26 16:43 UTC, mxxo commented
This API's use case is somewhat addressed by the existing method `Get<T>`, ie: 
 `HasField("field.name") ~ model->Get<T>("field.name") != nullptr`
but `Get` requires a template parameter and I think `HasField` is a nice surface-level API (if the type is wrong but a field with that name exists, what does `Get` return?).

2021-03-30 07:59 UTC, jblomer requested changes
That looks all correct but I wonder if it's worthwhile using the visitor. After all, there is no dispatch based on the field type.

Wouldn't it be easier to have a simple recursive function, taking an `RFieldBase` and a name prefix?  That would also allow us concatenating the fully qualified field name instead of stripping the top level field name (which is slightly more complicated).

2025-05-16 13:51 UTC, closed without merging