Follow HTTP redirects when using curl
root-project/root pull request #7725
Opened 2021-03-29 06:48 UTC by MrCarroll

curls default behaviour is to not follow HTTP redirects, resulting in some of the tutorials not functioning as users attempt to operate on HTML error pages rather than valid ROOT files. A specific example prior to this commit would be the URL for ClassificationKeras.py

Since it's impossible to know in advance which URL's might end up having redirects in the future, I've simply added '-L' to every invocation of CURL (including in a few tests) which should prevent any issues in the future and otherwise work exactly the same for files which don't have redirects today.

(curl behaviour tested on Ubuntu 20.04)

2021-03-29 09:29 UTC, stwunsch requested changes
Thanks for contribution! :)

I'd propose to write `curl -OL http://<url>` in all places rather than attaching the `-L` flag to the end. I think it makes it more concise, especially for the cases in Python!

2021-03-29 12:57 UTC, stwunsch commented
@phsft-bot build

Let's see whether the current impl works in our CI.

2021-03-29 13:06 UTC, MrCarroll commented
Personally I avoid merging parameters, the GNU/getopts standards might allow it, but I personally think it's a source of confusion for new users.

Regardless I'll do it, but @lmoneta has mentioned on the forums that he might be making a seperate PR swapping the protocol from HTTP to HTTPS, since this actually seems to be what the redirect is doing to begin with. Incidentally every instance of curl in this PR does seem to be using http.

Personally I think the best approach would be to use both, since it ensures the security guarantees of HTTPS whilst also proactively fixing any potential redirects in the future just on the off chance. Would you like me to handle HTTPS in this PR?

2021-03-29 16:23 UTC, Axel-Naumann commented
We cannot use `https` as some of the tools we use (Davix) don't have access to the system CA store on macOS for now - we first need to check whether it has arrived now, and then we need to upgrade them. So let's stick with just `-L` for now!

2021-03-29 16:24 UTC, Axel-Naumann commented
I prefer `-L -O http://....` as the best of both worlds and a potentially viable compromise ;-)

2021-04-06 18:13 UTC, pcanal commented
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-04-08 01:03 UTC, pcanal commented
@phsft-bot build just on mac1014/python3, ROOT-ubuntu16/nortcxxmod,windows10/cxx14 with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-04-08 01:03 UTC, pcanal commented
@phsft-bot build just on mac1014/python3,ROOT-ubuntu16/nortcxxmod,windows10/cxx14 with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-04-08 01:04 UTC, pcanal commented
@phsft-bot build just on mac1014/python3, ROOT-ubuntu16/nortcxxmod, windows10/cxx14 with flags -DCTEST_TEST_EXCLUDE_NONE=On

2021-04-08 18:45 UTC, pcanal commented
The windows error is unrelated (hang in a test that does not use http).

2021-04-08 19:03 UTC, pcanal commented
Thank you!

2021-04-08 19:03 UTC, merged