[ntuple] std::pair RField support
root-project/root pull request #8103
Opened 2021-05-05 23:23 UTC by mxxo

Motivation: `std::pair` is used by one of the NanoAOD auxiliary trees (`ParameterSets`).

The `std::pair` implementation largely follows `RRecordField`. There is a
question about whether `RField<std::pair<T1,T2>>::GetValueSize()` should
equal `sizeof(std::pair<T1,T2>)`, since currently the former does not add
trailing padding bytes, which are implementation defined. 

E.g the following test fails:

```cpp
auto field = RField<std::pair<int64_t, float>>("pairField");
// sizeof check fails, RPairField does not take into account 4 trailing padding bytes
EXPECT_EQ((sizeof(std::pair<int64_t, float>)), field.GetValueSize());
```
```
Expected equality of these values:
  (sizeof(std::pair<int64_t, float>))
    Which is: 16
  field.GetValueSize()
    Which is: 12
```

2021-05-12 13:41 UTC, jblomer requested changes
Many thanks!  That's a very useful addition.

I wonder if the field specialization for pairs can directly inherit from the `RRecordField`

2021-05-15 15:50 UTC, mxxo commented
I'm not if if `RField<std::pair<T1, T2>> : public RRecordField` would work because then pairs constructed through `RFieldBase::Create` wouldn't have the right type name. But `RPairField : public RRecordField` might work and get rid of some of the duplication! Do you think the padding issue is a big deal?

2021-05-22 14:07 UTC, jblomer commented
Oh, yes, the padding. Unfortunately yes: `RField<T>::GetValueSize()` must be equal to `sizeof(T)`.  The `GetValueSize()` is used to allocate the memory for the in-place construction of the type.

2022-05-11 08:46 UTC, jblomer commented
Many thanks!

First quick comment: please also update the RNTuple format specification on how `std::pairs` are mapped to columns.

2022-05-16 06:31 UTC, jblomer requested changes
As discussed in the I/O meeting, we should treat `std::pair` in general different from a record. We probably need a new type erased base class (`RPairField` or `RTupleField`) that uses `TClass` or cling to create the in-memory objects.

2022-05-24 09:31 UTC, jalopezg-r00t commented
Closing in favor of #10635.  Many thanks for the initial PR, @mxxo.

2022-05-24 09:31 UTC, closed without merging