Rename fLineStyle member in TStyle
root-project/root pull request #8181
Opened 2021-05-17 08:13 UTC by linev

It duplicates member name from inherited TAttLine class and makes
impossible to store/restore TStyle object from JSON. Solves
https://root-forum.cern.ch/t/error-restoring-tstyle-from-json/44879/

2021-05-17 09:19 UTC, Axel-Naumann commented
Doesn't this need a bump of the `ClassDef` version number, @pcanal ?

2021-05-17 09:25 UTC, linev commented
I also have same question
From one side, on binary level it remains absolutely the same.
And if we change class version, how ROOT will get idea that old `fLineStyle` should be converted into new `fLineStyles`?

2021-05-17 11:37 UTC, pcanal requested changes
You need to also add a I/O customization rule to actually fill the new data member with the date from the old member.

2021-05-17 11:40 UTC, linev commented
@pcanal Are there such examples?

2021-05-17 11:44 UTC, pcanal commented
I also this is not forward compatible.  (Unless we patch all the old release to know about the new version, they will lose the line style information.   

I may be more beneficial to solve the underlying JSON I/O problem (not supporting base/derived class aliasing)

2021-05-17 12:06 UTC, linev commented
> It may be more beneficial to solve the underlying JSON I/O problem (not supporting base/derived class aliasing)

That do you mean?
Provide different layout for created JSON structures?
It will have huge side effect on JSROOT - one have to rewrite it from scratch complete JavaScript code.

2021-05-17 12:07 UTC, linev commented
> Doesn't this need a bump of the ClassDef version number

This does not work.

2021-05-17 12:10 UTC, linev commented
I convert into draft, while simple member name change does not work.
Also increase of class version does not help.

2021-05-17 12:48 UTC, Axel-Naumann commented
>  It will have huge side effect on JSROOT - one have to rewrite it from scratch complete JavaScript code.

Depends on how you do it. If you use the name as before, but `Derived::fMember` in case the derived re-uses a member name from a base, then it should be strictly an improvement, and backwards compatible?

2021-05-17 12:52 UTC, linev commented
> If you use the name as before, but Derived::fMember in case the derived re-uses a member name from a base, then it should be strictly an improvement, and backwards compatible?

It will require search for member names in all base classes for each write operation - huge performance degradation.

2021-05-17 12:58 UTC, Axel-Naumann commented
That depends on the implementation. If you create a map member-name => value-as-string then it's easy to find dupe member names.

2021-06-01 15:45 UTC, pcanal approved these changes
This nees a more compete solution but get around the immediate problem.

2021-06-01 15:58 UTC, merged