[rntuple] Factor out common code in the sealed pages path and add support for sealed pages to DAOS
root-project/root pull request #8309
Opened 2021-06-01 12:11 UTC by jalopezg-r00t

First, this PR factors out common parts of the code in commit/load of (sealed) pages.  Specifically, this affects:
- `CommitPageImpl` and `CommitSealedPageImpl`.
- `PopulatePageFromCluster()` and `LoadSealedPage()`. Locating the RPageInfo from the cluster index is now a member function of RPageRange.

Second, it provides support for sealed pages in the DAOS backend.

Closes issue #8079.

2021-06-02 09:58 UTC, jblomer requested changes

2021-06-02 09:58 UTC, jblomer commented on tree/ntuple/v7/src/RPageStorageDaos.cxx
> +      fDaosContainer->ReadObject({static_cast<decltype(daos_obj_id_t::lo)>(pageInfo.fLocator.fPosition), 0},
Wrap in bracelets (because of the multi-line if block).

2021-06-02 12:55 UTC, jalopezg-r00t commented
Oops!  Sorry for the noise; should be ready to merge now.  :-)

2021-06-03 11:42 UTC, jblomer requested changes

2021-06-03 11:42 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
> +      /// Find the page in the RPageRange that contains the given element.
```suggestion
      /// Find the page in the RPageRange that contains the given element. The element must exist.
```

2021-06-03 12:40 UTC, jblomer approved these changes

2021-06-03 15:08 UTC, merged