[ntuple] Provide a common set of performance counters in `RPage{Sink,Source}`
root-project/root pull request #8397
Opened 2021-06-10 10:59 UTC by jalopezg-r00t

This pull-request extends `RPageSink` and `RPageSource` to provide a common set of performance counters that can be enabled in a subclass via `EnableDefaultMetrics()`.  Afterward, the set might be extended in a subclass via a call to `fMetrics.MakeCounter<...>()`.

This not only removes boilerplate code from subclasses, but also provides a useful set of regular/computed counters.  A subclass, however, is still responsible for updating the base counters.

Alternatively, subclasses may still ignore the default set of metrics and provide their own `RNTupleMetrics` object by overriding the `GetMetrics()` member function.

Closes issue #8360.

2021-06-10 17:14 UTC, mxxo reviewed
> Hey Javier I think everything looks pretty good! You could also take the prefix argument out of `EnableDefaultMetrics` and pass it in the initializer list: `fMetrics("RPageSinkFile")` to match what would happen if a derived class doesn't call `EnableDefaultMetrics` but this is not a big deal.

Thanks!  It's up to Jakob to decide that, but I would prefer leaving as-is, i.e. everything is taken care of in the call to `EnableDefaultMetrics()`.

2021-06-11 09:55 UTC, jblomer requested changes
Great, many thanks! Just two tiny suggestions for the comments.

2021-06-11 09:55 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
> +   /// Afterward, this set of counters can be extended by a subclass by calling `fMetrics.MakeCounter<...>()`.
```suggestion
   /// This set of counters can be extended by a subclass by calling `fMetrics.MakeCounter<...>()`.
```

2021-06-11 09:55 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
> +   /// A subclass using the default set of metrics is always responsible for updating the counters
```suggestion
   /// A subclass using the default set of metrics is responsible for updating the counters
```

2021-06-11 09:55 UTC, jblomer commented on tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
> +   /// Returns the default metrics object.  Subclasses might alternatively provide their own metrics object by overriding this.
```suggestion
   /// Returns the default metrics object.  Subclasses might alternatively override the method and provide their own metrics object.
```

2021-06-11 12:25 UTC, jblomer approved these changes

2021-06-12 15:23 UTC, merged