[ntuple] DAOS object class customization (1/2): refactor RDaosXxx classes
root-project/root pull request #8402
Opened 2021-06-10 14:29 UTC by jalopezg-r00t

The first in the series of two pull-requests to allow users to customize the DAOS object class.

This PR applies the required changes to the `RDaosXxx` classes.  Also, libdaos_mock is extended to provide an implementation for the object class name to ID conversion functions.

Related to issue #8205.

2021-06-11 10:09 UTC, jblomer requested changes
Nice improvement!

2021-06-11 12:00 UTC, jalopezg-r00t commented on tree/ntuple/v7/inc/ROOT/libdaos_mock/daos.h
>  	OC_SX,
Yes, thanks for spotting!  I kept the entire enumerator block.

2021-06-11 12:26 UTC, jblomer approved these changes

2021-06-12 16:35 UTC, jalopezg-r00t commented
I made additional changes to one of the commits in the follow-up pull request.  As this was not merged yet, I also touched the corresponding part here.

@jblomer, could you please review commit 97c90bb5be7181443665be9b3ee44e82c9829f98?  Let me know if you have any suggestion.

2021-06-14 11:49 UTC, jalopezg-r00t commented
@phsft-bot build just on ROOT-debian-i386/cxx14

2021-06-14 11:50 UTC, jalopezg-r00t commented
@phsft-bot build just on ROOT-debian10-i386/cxx14

2021-06-14 15:27 UTC, jblomer requested changes
I left a review on 6efaf8e

2021-06-14 16:50 UTC, jalopezg-r00t commented
> That's pretty dangerous. Who know how long class names will be in the future. The implementation just seems to use `strcpy`. I think that's something we can discuss with Johann -- if there is a DAOS defined limit that we can use. I'd very much prefer that. Lacking such a limit, I'd use a much larger one for ours, e.g. 64 or 128.

I completely agree, that's why I left a comment and asked you to re-review ;-)  I will ask Johann, or otherwise use a larger buffer.

2021-06-15 15:41 UTC, jblomer reviewed
Could you pinpoint what's the change since the last review?  In general, I think it's easier if you add on commits rather than force push an updated history.

2021-06-16 07:20 UTC, jalopezg-r00t commented
> Could you pinpoint what's the change since the last review? In general, I think it's easier if you add on commits rather than force push an updated history.

I have updated the value (and documentation) of the `kOCNameMaxLength` constant.  Sorry, I squashed the commits as if the PR history was going to be merged, but I agree it is harder for you to review!  For subsequent PRs, I will add independent commits and will do the interactive rebase only after the review.  :-)

2021-06-16 08:11 UTC, jblomer approved these changes

2021-06-16 12:37 UTC, jalopezg-r00t commented
@phsft-bot build just on windows10/cxx14

2021-06-16 18:41 UTC, merged