[ntuple] DAOS object class customization (2/2):  provide `RNTupleWriteOptionsDaos`
root-project/root pull request #8452
Opened 2021-06-16 19:41 UTC by jalopezg-r00t

This pull-request is a follow-up of #8402.  `RNTupleWriteOptionsDaos`, i.e. a subclass of `RNTupleWriteOptions`, may now be used to provide DAOS-specific options.  Currently, we only support setting the object class used for user data OIDs.

## Changes or fixes:
- Contains the required changes to support backend-dependent options: classes derived from `RNTupleWriteOptions` may carry additional options.
- String serialization/deserialization routines moved to the `ROOT::Experimental::Internal::RNTupleSerialization` namespace, where they can be reused.
- RPageStorageDaos: the provided object class, if given, is used for generating the OIDs that relate to user data.  `OC_SX` is always used to store metadata (i.e. header/footer and anchor).  The object class must be known to read the ntuple; thus, the object class name is stored in the anchor.
- Changed the default object class for user data to the more conservative `OC_SX` (before was `OC_RP_XSF`).  `OC_SX` distributes data over all the targets and is probably a more sane default.

This PR closes issue #8205.

2021-06-17 14:28 UTC, mxxo approved these changes
Hey Javier, just looking at the write options changes everything looks good. It looks like you've been very careful to make potential null dereferences of `fOptions` impossible. I believe this is the first time `dynamic_cast` is used in `RNTuple`, is that is a milestone?

2021-06-18 08:16 UTC, jblomer requested changes
Very well! One tiny comment.

2021-06-18 09:13 UTC, jalopezg-r00t commented
Thanks for the quick review, @mxxo and @jblomer!  Let's see if we can merge this today :-).

2021-06-18 13:15 UTC, jblomer approved these changes

2021-06-18 20:25 UTC, merged