Added TTree::GetEntry() and TTree::GetEvent() Backward incompatibility note
root-project/root pull request #8535
Opened 2021-06-24 15:32 UTC by AdvaitDhingra

# This Pull request:

Adds a note that states that TTree:.GetEntry() and TTree::GetEvent() no longer have 0 as the default value for the first parameter. 

## Changes or fixes:

Just added a small note.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

2021-06-24 15:39 UTC, Axel-Naumann requested changes

2021-06-24 15:39 UTC, Axel-Naumann commented on README/ReleaseNotes/v626/index.md
> +- TTree::GetEntry() and TTree::GetEvent() no longer have 0 as the default value for the first parameter `entry`.
```suggestion
- `TTree::GetEntry()` and `TTree::GetEvent()` no longer have 0 as the default value for the first parameter `entry`. We are not aware of correct uses of this function without providing an entry number. If you have one, please simply pass `0` from now on.
```

2021-06-24 15:39 UTC, Axel-Naumann commented on README/ReleaseNotes/v626/index.md
While you're at it :-) can you remove the empty lines in this enumeration? You can see here https://root.cern/doc/master/release-notes.html#deprecation-and-removal that it adds extra vertical space for the bullet point. (This is also where your change will show up once merged!)

```suggestion
- `TTreeProcessorMT::SetMaxTasksPerFilePerWorker` has been removed. `TTreeProcessorMT::SetTasksPerWorkerHint` is a superior alternative.
```

2021-06-28 14:49 UTC, AdvaitDhingra commented
@Axel-Naumann is this ready to be merged?

2021-06-28 14:52 UTC, pcanal approved these changes

2021-06-28 14:54 UTC, merged