[TGMainFrame] disengage SaveFrame code from GUI so that it can also run from script
root-project/root pull request #8673
Opened 2021-07-14 14:50 UTC by ferdymercury

# This Pull request:

## Changes or fixes:

Adds an option to call SaveFrame from batch script, without having to interact, giving the filename as argument.

## Checklist:

- [x] tested changes locally
- [x] updated the docs (if necessary)

2021-07-14 15:46 UTC, bellenot commented
Note that you can already do it:
```
   TImage *img = TImage::Create();
   img->FromWindow(frame->GetId());
   img->WriteImage(outfilename);
```

2021-07-14 15:46 UTC, bellenot commented
@phsft-bot build

2021-07-21 09:07 UTC, ferdymercury commented
Failing test is unrelated (it's happening in other PRs too)

2021-08-05 06:22 UTC, bellenot requested changes

2021-08-05 06:22 UTC, bellenot commented on gui/gui/inc/TGFrame.h
> +   virtual Bool_t SaveFrameAsCodeOrImage(const TString fileName);
```suggestion
   virtual Bool_t SaveFrameAsCodeOrImage(const TString &fileName);
```

2021-08-05 06:22 UTC, bellenot commented on gui/gui/src/TGFrame.cxx
> +Bool_t TGMainFrame::SaveFrameAsCodeOrImage(const TString fileName)
```suggestion
Bool_t TGMainFrame::SaveFrameAsCodeOrImage(const TString &fileName)
```

2021-08-05 09:25 UTC, bellenot requested changes
Sorry, coding conventions (I know it was already in the original code)...

2021-08-05 09:25 UTC, bellenot commented on gui/gui/src/TGFrame.cxx
> +      {
```suggestion
      if (!res) {
```

2021-08-05 09:25 UTC, bellenot commented on gui/gui/src/TGFrame.cxx
> +      else {
```suggestion
      } else {
```

2021-08-05 09:25 UTC, bellenot commented on gui/gui/src/TGFrame.cxx
> +   else {
```suggestion
   } else {
```

2021-08-05 09:29 UTC, ferdymercury commented
> Sorry, coding conventions (I know it was already in the original code)...

Sure, no problem. I suggested a new feature recently which would auto-format these https://github.com/root-project/root/issues/8797, I tend to forget about these because I have QtCreator configured with the default sytle.

2021-08-05 11:41 UTC, bellenot approved these changes
LGTM, thanks!

2021-08-05 11:42 UTC, merged