Deflate axis
root-project/root pull request #8760
Opened 2021-07-28 07:46 UTC by couet

fix https://github.com/root-project/root/issues/8598
It is reasonable to call automatically LabelsDeflate at drawing time when plotting histogram with labels.

2021-08-03 13:32 UTC, lmoneta requested changes
Thank you Olivier for the PR. 
Checking on the fact that an axis can be extended and is alphanumeric is the correct thing, because you can have histograms with labels and the users explicitly does not want the axis to be inflated/deflated.

2021-08-03 13:32 UTC, lmoneta commented on hist/histpainter/src/THistPainter.cxx
> +   // Deflate the labels in case of alphanumeric labels
The correct condition is:
```
if (fXaxis.CanExtend() && fXaxis.IsAlphanumeric()) fH->LabelsDeflate("X");
if (fYaxis.CanExtend() && fYaxis.IsAlphanumeric()) fH->LabelsDeflate("Y");
```

and should we add also the case for the Z axis (for TH3 objects) ?

2021-08-19 14:13 UTC, couet commented
@lmoneta 
Hello Lorenzo, I implemented your suggestions. I will merge as soon as you approve it.

2021-08-20 07:49 UTC, lmoneta approved these changes
LGTM now ! 
Thank you Olivier for the update !

2021-08-20 08:16 UTC, merged