[GSoC][TMVA][SOFIE] Fix protobuf
root-project/root pull request #8852
Opened 2021-08-17 01:06 UTC by axmat

# This Pull request:
Fixes `fatal error: 'google/protobuf/port_def.inc' file not found` error when building the tests of TMVA-Sofie with protobuf v3.17.3.

## Checklist:

- [ x] tested changes locally

2021-08-17 06:37 UTC, bellenot approved these changes

2021-08-17 06:38 UTC, bellenot commented
@phsft-bot build

2021-08-17 06:44 UTC, bellenot requested changes
Could you use `${CMAKE_CURRENT_SOURCE_DIR}` instead of `../../`? Like for example  `${CMAKE_CURRENT_SOURCE_DIR}/tmva/src/` instead of `../../src/` and `${CMAKE_CURRENT_SOURCE_DIR}/core/foundation/inc` instead of `../../../core/foundation/inc` and so on?

2021-08-17 12:22 UTC, bellenot commented
@phsft-bot build just on ROOT-ubuntu2004/default with flags -Dtmva-sofie=On

2021-08-17 12:57 UTC, bellenot approved these changes
LGTM

2021-08-18 11:18 UTC, lmoneta commented
@axmat Can you please update the PR using the comments suggested by Bertrand, so we can then merge this one ?
Thanks

2021-08-18 13:12 UTC, axmat commented
@lmoneta I have already updated the PR, see last commit

2021-08-18 13:30 UTC, lmoneta commented
Thank you! I missed it. Looks good, I will merge then

2021-08-18 13:30 UTC, merged