Added typedefs Float16_t and Double32_t to TDataType
root-project/root pull request #9008
Opened 2021-09-16 20:02 UTC by Triple-S

# This Pull request: 
Adds the typedefs Float16_t and Double32_t to the builtin types in TDataType.

## Changes or fixes:
The change is required to read tree branches of those types using TTreeReader and TTreeReaderValue<Float16_t> / TTreeReaderValue<Double32_t>. Otherwise attempting to read such branches results in an error message that no dictonary for Float16_t / Double32_t exists.

## Checklist:
- [x] tested changes locally
- [x] updated the docs (if necessary)

This PR fixes #

2021-09-16 20:24 UTC, pcanal commented on core/meta/src/TDataType.cxx
> +      fgBuiltins[kDouble_t] = fgBuiltins[kDouble32_t] = new TDataType("double");
`kFloat_t` and `kFloat16_t `(and `Double_t` and `Double32_t`) are *not* interchangeble`.  See other use in the same file.
```suggestion
      fgBuiltins[kFloat_t] = new TDataType("float");
      fgBuiltins[kDouble_t] = new TDataType("double");
      fgBuiltins[kFloat16_t] = new TDataType("Float16_t");
      fgBuiltins[kDouble32_t] = new TDataType("Double32_t");
```
might work.

2021-09-16 20:24 UTC, pcanal requested changes
See command and If you could also add a test for this features (eg. a TTreeReader usage) that would be great.

2021-09-16 20:40 UTC, Triple-S commented
Thanks for the suggestion. I tested it and it works as well. Since in the names the c++ typenames were used instead of the ROOT typedefs, I assumed the class would always expext the c++ typename which is the same for Float_t and Float16_t as well as Double_t and Double32_t.

I will also add a small test using the TTreeReader soon.

2021-09-16 21:30 UTC, Triple-S commented
> See command and If you could also add a test for this features (eg. a TTreeReader usage) that would be great.

I realized there was already a test for using TTreeReader with the truncated datatypes, however it was not properly working and thereby unable to detect the problem since it stored the Float16_t / Double32_t data as regular Float_t / Double_t. The reason is that the used TTree::Branch method is unable to automatically detect the Float16_t / Double32_t datatype since like Float_t / Double_t they are typedefs of float / double which results in typeid(Float_t) = typeid(Float16_t) = typeid(float), same for the double types. For these reasons, the truncated datatypes always need to be specified via the leaflist. I changed the test accordingly.

2021-09-16 21:51 UTC, pcanal commented
@phsft-bot build

2021-09-16 23:48 UTC, pcanal commented
@phsft-bot build

2021-09-17 05:52 UTC, Triple-S commented
It seems to me that the test projectroot.roottest.root.io.double32.roottest_root_io_double32_make fails just because its reference file needs to be updated now. At least I don't see any critical problem with that test.
The test projectroot.roottest.root.tree.cache.roottest_root_tree_cache_TooSmall failed once too, but on my local machine it is working. Unfortunately I can no longer access the build logs with my CERN account. Most probably because it was converted to a "Lightweight Account" so I am unable to investigate this further.

2021-09-17 11:30 UTC, pcanal commented
Unfortunately the projectroot.roottest.root.io.double32.roottest_root_io_double32_make failure is a real issue.  It, surpringly, fails to merge some consecutive `Double32_t` data member that it was able to before (so the issue appear in `TStreamerInfo::Compile`):
```
-   i= 3, ff2             type= 29, offset= [deleted from log], len=4, method= [deleted from log] [optimized]
-   i= 4, ff4             type= 49, offset= [deleted from log], len=1, method= [deleted from log]
+   i= 3, ff2             type= 29, offset= [deleted from log], len=3, method= [deleted from log]
+   i= 4, ff3             type=  9, offset= [deleted from log], len=1, method= [deleted from log]
+   i= 5, ff4             type= 49, offset= [deleted from log], len=1, method= [deleted from log]
```

2022-09-27 12:18 UTC, pcanal commented
Note that the complete version of this PR is at https://github.com/root-project/root/pull/11261

2022-09-27 12:18 UTC, closed without merging