[PyROOT] Get names and types of all overloads' signature
root-project/root pull request #9138
Opened 2021-10-18 17:06 UTC by vepadulano

This PR introduces a machinery to get the names and types (separately) of the signature of each overload of a particular `CPPOverload` object. This allows for example for something like.

**EDIT**

Here is the latest status of this feature after some discussion:

```python
>>> import ROOT
>>> ROOT.gInterpreter.Declare("""
 int foo(int a, float b);
 int foo(int a);
 float foo(float b);
 double foo(int a, float b, double c);
... """)
True
>>> ROOT.foo
<cppyy.CPPOverload object at 0x7fc470789fd0>
>>> from pprint import pprint
>>> pprint(ROOT.foo.func_overloads_names)
{'double ::foo(int a, float b, double c)': ('a', 'b', 'c'),
 'float ::foo(float b)': ('b',),
 'int ::foo(int a)': ('a',),
 'int ::foo(int a, float b)': ('a', 'b')}
>>> pprint(ROOT.foo.func_overloads_types)
{'double ::foo(int a, float b, double c)': {'input_types': ('int',
                                                            'float',
                                                            'double'),
                                            'return_type': 'double'},
 'float ::foo(float b)': {'input_types': ('float',), 'return_type': 'float'},
 'int ::foo(int a)': {'input_types': ('int',), 'return_type': 'int'},
 'int ::foo(int a, float b)': {'input_types': ('int', 'float'),
                               'return_type': 'int'}}
```

2025-01-30 12:06 UTC, vepadulano commented
A clear use case for this functionality has not surfaced since the opening of the PR. This can be closed now, to be reopened in case it becomes necessary.

2025-07-23 08:49 UTC, siliataider commented
Reopening and bringing this up to date, a clear use case has surfaced in fact: #19437

2025-07-25 08:36 UTC, siliataider commented
We should be able to merge this now, @vepadulano ?

2025-07-25 09:23 UTC, vepadulano commented
> We should be able to merge this now, @vepadulano ?

Yes, but given it's my own PR I can't approve it. Let's ask @guitargeek for an approval. This is in the context of RDF Pythonizations. It may be that this code is not going to be necessary once we have a CppInterop-based CPyCppyy, but currently we need it.

2025-07-25 09:31 UTC, guitargeek requested changes
Thank you very much @siliataider!

Could you please just revert the unrelated code formatting changes in `CPPOverload.cxx`? CPyCppyy has its own code style incompatible with the one of ROOT, and it would be better to not do unnecessary formatting changes in a codebase that is already hard to keep in sync.

2025-07-25 14:09 UTC, merged