Fix warning of unused variable in roofit
root-project/root pull request #9368
Opened 2021-12-02 16:37 UTC by ikabadzhov

# This Pull request:

Casted variable rc to void in roofit/multiprocess/src/Messenger.cxx to disable the warning.
It is used only in assert statement besides the cast.

## Changes or fixes: roofit/multiprocess/src/Messenger.cxx

## Checklist:

- [ ] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

2021-12-03 10:55 UTC, lmoneta approved these changes

2021-12-03 14:01 UTC, guitargeek commented
You can close this PR, we are already taking care of it: https://github.com/root-project/root/pull/9349/files#diff-03f30bc721fb7eb65916ce4552fb544751ad9dfde16e608227267692c0bc16a4

Whenever you see such warnings in an actively developed part of ROOT you can assume that somebody else will take care of it :)

2021-12-03 14:02 UTC, guitargeek requested changes
Just and empty change request to block this PR from merging.

2021-12-06 11:10 UTC, guitargeek commented
This has already been fixed in https://github.com/root-project/root/pull/9349

2021-12-06 11:10 UTC, closed without merging