[DF] Prefer US spelling for initialize/finalize
root-project/root pull request #9509
Opened 2022-01-06 17:50 UTC by eguiraud

2022-01-07 08:25 UTC, eguiraud commented
Rebased to fix a minor conflict.

2022-01-07 08:29 UTC, Axel-Naumann requested changes

2022-01-07 08:29 UTC, Axel-Naumann commented on tree/dataframe/inc/ROOT/RDataSource.hxx
> +   R__DEPRECATED(6,30,"Use Initialize (with a z) instead.") void Initialise() { Initialize(); }
Doesn't this need to be `virtual` to not break expert users' derived classes? And even then... someone needs to call it?

2022-01-07 08:29 UTC, Axel-Naumann commented on tree/dataframe/src/RLoopManager.cxx
> -   fDataSource->Initialise();
You probably need to call both versions here, for backward compatibility? You can even test that by moving only half the data sources to the new spelling and checking whether both new and old still work.

2022-01-09 13:49 UTC, eguiraud commented
As per discussion with Axel:

- [ ] instead of `R__DEPRECATE`, use a runtime printout: it's not possible to have `R__DEPRECATE` fire for users that inherit from `RDataSource` but not for ROOT builds, and maintain backwards-compatibility. But it's possible with a runtime error.
- [ ] put a R__DEPRECATE in there even if it does not fire, e.g. as an attribute of an unused dummy struct.

2022-01-10 10:33 UTC, Axel-Naumann commented on tree/dataframe/inc/ROOT/RDataSource.hxx
> +         Initialize();
```suggestion
         // `Initialise()` was not overridden and threw, the data source uses the new spelling: good!
         Initialize();
```

2022-01-10 10:34 UTC, Axel-Naumann commented on tree/dataframe/inc/ROOT/RDataSource.hxx
> +              "Initialise is deprecated. Please implement Initialize (with a z) instead of Initialise.");
```suggestion
              "Initialise is deprecated. Please rename it to \"Initialize\" (with a z).");
```
?

2022-01-10 10:36 UTC, Axel-Naumann approved these changes
LGTM! Can you already prepare a PR to merge at the time of v6.30, i.e. removing the deprecation etc, and can you maybe reference that from the comment near `NeverUsedJustAReminder`?

2022-01-10 13:44 UTC, merged