[RF] Remove safeDeleteList functionality of RooAbsCollection
root-project/root pull request #9685
Opened 2022-01-25 09:34 UTC by gartrog

This is presumbaly a bit controversial.

safeDeleteList remove elements in order in a RooAbsCollection,
starting with the ones that only have clients and no servers.

This is a slow process, and takes 25% of CPU time on large workspace
manipulation workflows, as it takes place at each workspace::import
call. It can also lead to slow ~RooWorkspace.

The point is, I don't think this logic is needed at all.
~RooAbsArg takes care of properly breaking all the client-server links,
both uplinks and downlinks, for every object. I couldn't find a logical
case where a crash would occur if the safeDeleteList logic were to be
removed.

All RooFit tests pass after this patch. No problem for my heavy
workspace manipulation worflows either.

2022-01-25 09:56 UTC, hageboeck commented
If it works, it's all-the-more good to have complicated destructor magic out of the way.

2022-01-25 09:56 UTC, hageboeck commented
@phsft-bot build

2022-01-25 21:16 UTC, guitargeek commented
Hi @gartrog, thanks for this! I agree that the order doesn't matter, as the RooAbsArg destructor is taking care that there are no dangling pointers in the client and server list.

Just one little request: can you please rename `safeDeleteList` to `deleteList` now? And adapt the function documentation to make sense even after the "safe" deletion is removed?

If the ASAN build doesn't complain after merging this, the PR should also be backported to 6.26. It would be a waste to have this nice speedup not in the release.

2022-01-25 21:16 UTC, guitargeek requested changes
Just one little request: can you please rename safeDeleteList to deleteList now? And adapt the function documentation to make sense even after the "safe" deletion is removed?

2022-01-25 23:21 UTC, gartrog commented
Should be done @guitargeek

2022-01-26 08:55 UTC, guitargeek commented
Thanks a lot!

@phsft-bot build

2022-01-26 08:55 UTC, guitargeek commented
@phsft-bot build

2022-01-26 17:05 UTC, guitargeek approved these changes
LGTM, thank you very much! It's about time that this overhead gets removed.

2022-01-26 17:06 UTC, merged