[RF] Address memory leaks in RooLagrangianMorphPdf
root-project/root pull request #9717
Opened 2022-01-26 17:15 UTC by goblirsc

# This Pull request:
The `RooLagrangianMorphFunc` loads its input objects from a nested set of `TFolders` stored in a `TFile`.  
This MR adds protection (inspired by [ROOT-9275](https://sft.its.cern.ch/jira/browse/ROOT-9275) to avoid memory leaks in the initialisation of the `RooLagrangianMorphFunc`, which for large `RooFit` workspaces with many morphing functions can otherwise become unfeasible to use. 

## Changes or fixes:
- add a `cleanUpFolder` helper method to an existing anoymous namespace to `RooLagrangianMorphFunc.cxx`, which ensures ownership is enabled for `TFolder`s loaded from `TFile`s and optionally deletes the folders after setting them up 
- add a templated `loadFromFileResidentFolder` method to the same anonymous namespace in `RooLagrangianMorphFunc.cxx`, refactoring the procedure of loading an object from a nested `TFolder` structure that was previously performed in various locations in the class. The method exploits the `cleanUpFolder` method to prevent memory leaks in the access procedure. 

## Checklist:

- [ x ] tested changes locally - confirmed leak rate massively reduced in local testing. Draft test script (not yet merged) provided by @rahulgrit retains same output as before the changes
- [ ] updated the docs (if necessary) - no changes to user-accessible code. Inline doxygen documentation of new methods. 

Tagging @rahulgrit @guitargeek

2022-01-27 11:11 UTC, guitargeek requested changes
Hi @goblirsc, thanks a ton for spotting the memory leaks and opening a PR to fix them!

I have a few suggestions to improve your fix. There are two anti-patterns in your fix:
  * manual memory management with `delete` instead of using smart pointer
  * relying on a "cleanup" function that needs to be called at the end of an objects lifetime. This is dangerous, because if one adds new code branches with `if-else`, one might forget to call the cleanup function and create a leak.

It would be better to do all of this at the initialization of the folder object (see [RAII on Wikipedia](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization)). What about introducing these functions instead of `cleanUpFolder`?

```C++
TFolder * flagOwningFolder(TFolder* folder)
{                                                                                       
  // start by assigning ownership to the folder itself
  folder->SetOwner();
  // And we need to do the same for all nested sub-folders.
  for (auto* subdir : *folder->GetListOfFolders()){
    if (auto thisfolder = dynamic_cast<TFolder*>(subdir)){
      // no explicit deletion here, will be handled by parent
      flagOwningFolder(thisfolder);      
    }                                    
  }       
  return folder;
}
      
std::unique_ptr<TFolder> getOwningFolder(TDirectory * inFile, std::string const& folderName) {
   return std::unique_ptr<TFolder>{flagOwningFolder(inFile->Get<TFolder>(folderName.c_str()))};
```

And then in the code, you can just use it like `auto folder = getOwningFolder(inFile, folderName);` and you don't need to remember calling any cleanup function: the `SetOwner` recursion is done in the initialization, and `delete` is called by the `std::unique_ptr` that owns the parent folder.

Would this work for you?

2022-01-27 11:12 UTC, guitargeek commented
@phsft-bot build

2022-01-27 11:16 UTC, goblirsc commented
> Hi @goblirsc, thanks a ton for spotting the memory leaks and opening a PR to fix them!
> 
> I have a few suggestions to improve your fix. There are two anti-patterns in your fix:
> 
> * manual memory management with `delete` instead of using smart pointer
> * relying on a "cleanup" function that needs to be called at the end of an objects lifetime. This is dangerous, because if one adds new code branches with `if-else`, one might forget to call the cleanup function and create a leak.
> 
> It would be better to do all of this at the initialization of the folder object (see [RAII on Wikipedia](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization)). What about introducing these functions instead of `cleanUpFolder`?
> 
> ```c++
> TFolder * flagOwningFolder(TFolder* folder)
> {                                                                                       
>   // start by assigning ownership to the folder itself
>   folder->SetOwner();
>   // And we need to do the same for all nested sub-folders.
>   for (auto* subdir : *folder->GetListOfFolders()){
>     if (auto thisfolder = dynamic_cast<TFolder*>(subdir)){
>       // no explicit deletion here, will be handled by parent
>       flagOwningFolder(thisfolder);      
>     }                                    
>   }       
>   return folder;
> }
>       
> std::unique_ptr<TFolder> getOwningFolder(TDirectory * inFile, std::string const& folderName) {
>    return std::unique_ptr<TFolder>{flagOwningFolder(inFile->Get<TFolder>(folderName.c_str()))};
> ```
> 
> And then in the code, you can just use it like `auto folder = getOwningFolder(inFile, folderName)` and you don't need to remember calling any cleanup function: the `SetOwner` recursion is done in the initialization, and `delete` is called by the `std::unique_ptr` that owns the parent folder.
> 
> Would this work for you?

Hi @guitargeek,

thanks a lot, I agree this is a much nicer approach! Will update the PR in a little bit. 

Cheers, Max

2022-01-27 13:11 UTC, guitargeek commented
Great, thanks for the prompt update!

2022-01-27 13:11 UTC, guitargeek commented
@phsft-bot build

2022-01-28 09:53 UTC, guitargeek approved these changes
LGTM, thanks a lot again for the fixes and the quick follow-up to the review!

2022-01-28 09:55 UTC, merged