[relnotes] Mention cling opt; cmake 3.16; C++14; rm memstat, alien depr. [skip-CI]
root-project/root pull request #9940
Opened 2022-02-21 11:09 UTC by Axel-Naumann

2022-02-21 11:29 UTC, jalopezg-r00t approved these changes
LGTM, but see comments.  :-)

2022-02-21 12:47 UTC, bellenot requested changes

2022-02-21 12:47 UTC, bellenot commented on README/ReleaseNotes/v626/index.md
> +ROOT's "alien" package has been deprecated and will be removed in 6.18. Please contact ALICE software support if you still rely on it.
> "alien" package has been deprecated and will be removed in 6.18 
6.18? Are you sure? I suppose you meant 6.28?

2022-02-22 11:07 UTC, jalopezg-r00t commented on README/ReleaseNotes/v626/index.md
> +
Stale newline here.  :-)
```suggestion
```

2022-02-22 11:12 UTC, bellenot approved these changes
LGTM

2022-02-22 13:37 UTC, merged