Avoid pointer subtraction with null pointers
root-project/root pull request #9969
Opened 2022-02-24 12:09 UTC by hahnjo

Clang 13 complains that this has undefined behavior.

2022-02-24 13:28 UTC, linev reviewed
This is external code - from https://github.com/civetweb/civetweb
It should be fixed there - otherwise any changes will be lost with next `civetweb` update

2022-02-24 15:24 UTC, Axel-Naumann commented
`core/clib/res/mmprivate.h` is ours. Could you have that "survive" in this / a PR and propose the other one upstream?

2022-02-25 08:22 UTC, hahnjo commented
> `core/clib/res/mmprivate.h` is ours.

I'm relatively sure this also comes from somewhere, judging by the occurrences that I found with a quick web search ;-)

> Could you have that "survive" in this / a PR and propose the other one upstream?

I've opened https://github.com/civetweb/civetweb/pull/1056 to upstream the fix into `civetweb`. My plan would be to wait a few days, the maintainer seems to be very responsive. If we cannot get it in, I'll back out the other fix to get that merged.

2022-02-28 10:30 UTC, hahnjo commented
> > Could you have that "survive" in this / a PR and propose the other one upstream?
> 
> I've opened [civetweb/civetweb#1056](https://github.com/civetweb/civetweb/pull/1056) to upstream the fix into `civetweb`. My plan would be to wait a few days, the maintainer seems to be very responsive. If we cannot get it in, I'll back out the other fix to get that merged.

Merged on Friday, I've updated the PR to move the `#include` where I put it for upstream.

2022-03-07 16:33 UTC, hahnjo commented
ping @linev @Axel-Naumann good to merge?

2022-03-07 17:32 UTC, pcanal requested changes
Could some text be added to explain why the subtraction was needed and is no longer needed?  (i.e. It was clearly intentional and the reason it was there may or may not be relevant anymore)

2022-03-07 18:27 UTC, hahnjo commented
> Could some text be added to explain why the subtraction was needed and is no longer needed? (i.e. It was clearly intentional and the reason it was there may or may not be relevant anymore)

The subtraction was never needed, this was a way to cast a pointer into an integer via a `ptrdiff_t`. I can elaborate on this, but I'm not sure this really adds value to archeological investigations that might ever come across this...

2022-03-07 18:56 UTC, pcanal commented
> The subtraction was never needed, this was a way to cast a pointer into an integer via a ptrdiff_t. I can elaborate on this, but I'm not sure this really adds value to archeological investigations that might ever come across this...

This plausible albeit a bit odd (i.e. why didn't they do the straight cast in the first place?  I find it more likely that there has been a change in the C++ standard (from 1994 to now :) ) that allows the straight cast to work ), I agree that it might not be helpful to dig any further.  I would add the above fact/claim/opinion :) at the very least in the git log.

2022-03-07 19:01 UTC, linev commented
@Axel-Naumann @pcanal I have nothing against PR and will approve it.
My remark was - here just copy of code from civetweb. If problem will not be fixed there, change will be lost with next update.

2022-03-07 19:02 UTC, linev approved these changes

2022-03-07 19:24 UTC, Axel-Naumann commented
> If problem will not be fixed there, change will be lost with next update.

Understood, and just to call this out: this has been fixed by @hahnjo also upstream. Congrats, @hahnjo !

2022-03-08 10:51 UTC, hahnjo commented
> > The subtraction was never needed, this was a way to cast a pointer into an integer via a ptrdiff_t. I can elaborate on this, but I'm not sure this really adds value to archeological investigations that might ever come across this...
> 
> This plausible albeit a bit odd (i.e. why didn't they do the straight cast in the first place? I find it more likely that there has been a change in the C++ standard (from 1994 to now :) ) that allows the straight cast to work ), I agree that it might not be helpful to dig any further. I would add the above fact/claim/opinion :) at the very least in the git log.

Yes, `uintptr_t` likely didn't exist in 1994. It's still optional in current C++ standards as far as I can tell, but ROOT and many other projects use it throughout their code base, so its existence is likely a given on all relevant platforms. Regarding the straight cast not being possible, I remember reading some time ago that the original `malloc` implementation in Unix casted pointers to `int` in various places, so it definitely was possible and I can't tell why it wasn't done here. I've added a sentence to the commit message explaining that we're now directly going to `uintptr_t` instead of taking the detour into `ptrdiff_t`.

2022-03-08 15:48 UTC, pcanal approved these changes

2022-03-08 15:48 UTC, pcanal commented
thanks.

2022-03-08 16:02 UTC, merged